#! /bin/bash

if [ $1 = "--help" ] || [ $1 = "-h" ]; then
  echo "$ connectbt <mac-address>"
  echo "Connect to a bluetooth device via bluetoothctl."
  echo "The device has to be paired/trusted via bluetoothctl beforehand."
  echo "Example: $ connectbt B8:D5:0B:EA:D9:A6"
else
  #fkill pulseaudio; # Uncomment if pa is not working
  pulseaudio --start; # Makes sure pa is running
  echo -e "power on\nquit" | bluetoothctl > /dev/null

  while [ 1 -eq 1 ]
  do
    echo -e "connect "$1"\nquit" | bluetoothctl | grep "# connect"
    sleep 1
    # break once [bluetooth] changes to [<device>]
  done
fi

