#! /bin/bash
BIN=extractmoep
OUT=~/ct/music

if [[ $1 = "--help" ]] || [[ $1 = "help" ]]; then
  echo "$ $BIN"
  echo "Extract and move monstercat eps"
  echo "Eps will be moved to: $OUT"
  echo ""
  echo "Modes:"
  echo "  automatic - Automatically applies to all files matching the format below"
  echo "  single - Manually set the file to use with as \$1 (because it does not match the format)"
  echo ""
  echo "Parameters:"
  echo "  [\$1]: File to use for single mode"
  echo ""
  echo "Format:"
  echo "  '<ep-name> EP (320 MP3).zip' -> '<ep-name> EP (320 MP3)'"
  exit
fi

if [[ -n $(echo $1 | grep zip) ]]; then
  DIR_ZIP=$1
  DIR=$(echo ${DIR_ZIP%.zip})

  echo "Running $BIN in $(pwd) in single mode"
  echo "---"
  echo "Starting: $DIR_ZIP"
  extract "$DIR_ZIP" > /dev/null 2>&1

  echo "cleanup"
  rm "$DIR_ZIP"

  echo "move files"
  mv "$DIR" ~/ct/music/
elif  [[ -n "$1" ]]; then # invalid $1
  echo "The passed parameters does not match the format."
  echo "A file with the .zip extension is required."
  exit
else
  echo "Running $BIN in $(pwd) in automatic mode"

  for F in *"EP"*".zip"; do
    echo "---"
    echo "Starting: $F"
    extract $F > /dev/null 2>&1

    echo "cleanup"
    rm "$F"
  done

  echo "move files"
  mv *"EP"* ~/ct/music/
fi


