#! /bin/bash

NOTRELEVANT="--exclude=.git --exclude=node_modules --exclude=.local --exclude=.mozilla --exclude=.vim/sessions --exclude=.vim/tmp --exclude=.vim/backup --exclude=.vim/view --exclude=.vim/bundle --exclude=.cache --exclude=.ccache --exclude=cache --exclude=.z --exclude=jest_rs --exclude=.node-gyp --exclude=.electron-gyp --exclude=chromium --exclude=.npm --exclude=TorBrowser"
NONTEXT="--exclude=music --exclude=comics --exclude=manga --exclude=non-beets --exclude=ct/movies"


if [[ $1 = "--help" ]] || [[ $1 = "help" ]]; then
  echo "$ F"
  echo "Select text file with fzf"
  echo "Filters out a lot of non-text files or files that you normally would not want to edit"
  echo ""
  echo "Non-text files:"
  echo "  $NONTEXT *.jpg"
  echo "Unrelevant files:"
  echo "  $NOTRELEVANT"
  exit
fi

du -a $NOTRELEVANT $NONTEXT ~ | awk '{$1=""; print}' | grep -vi .jpg | fzf

