#! /bin/bash

# Todo:
# Fallback like
# 192.168.172.0
# if network unavailable

if [[ $1 = "--help" ]] || [[ $1 = "help" ]]; then
  echo "$ ipa"
  echo "Get current ip address"
  exit
fi

ifconfig | grep 192 | awk '{ print $2 }'

