#! /bin/bash



DL_DIR=~/Downloads
C_DIR=~/comics

if [[ $1 = "--help" ]] || [[ $1 = "help" ]]; then
  echo "$ mv-comics"
  echo "Move comics from the $DL_DIR to it's corresponding"
  echo "directory in $C_DIR."
  exit
fi

#for COMIC in `find $DL_DIR/*.cbr -print0`
#  do {
#    echo $COMIC
#  }
#done

while IFS= read -r -d '' n; do
  COMIC=$(printf '%q\n' "$n" | sed "s/\\\//g")

  DIR=$(basename $(~/scripts/format-comic-name.js "$COMIC" | cut -d "." -f1 | awk -F "-" '{$(NF--)=""; print}' | sed -e 's/[[:space:]]*$//' | sed "s/ /-/"))
  
  [ -d "$C_DIR/$DIR" ] && ~/scripts/rename-comic "$COMIC" "$C_DIR/$DIR"

done < <(find $DL_DIR/*.cbr -print0)

