#! /bin/bash

BROWSER=$BROWSER
ALT_BROWSER=firefox-developer-edition

if [[ $1 = "--help" ]] || [[ $1 = "help" ]]; then
  echo "$ open-in-browser"
  echo "Open piped in url in the via dmenu selected browser"
  echo ""
  echo "Parameters:"
  echo "  pipe: url to open in the selected browser"
  echo ""
  echo "Example:"
  echo "$ echo "https://jneidel.com" | open-in-browser"
  exit
fi

STDIN=$(cat)

#OPEN_BROWSER=$(printf "$BROWSER\n$ALT_BROWSER" | dmenu -i -p "open in:")
OPEN_BROWSER=$ALT_BROWSER

$OPEN_BROWSER $STDIN

