#! /bin/bash

if [[ $1 = "--help" ]] || [[ $1 = "help" ]]; then
  echo "$ recommend <what> <who> <where>"
  echo "Add a recommendation to ~/notes/recommendations"
  echo ""
  echo "Parameters:"
  echo "\$1: What was recommended"
  echo "\$2: Who recommended it"
  echo "\$3: Where was it recommended"
  echo ""
  echo "Example:"
  echo "$ recommend 'Perfect Blue' 'Super Eyepatch Wolf' 'Why perfect blue is terrifying'"
  exit
fi

WHAT=$1
WHO=$2
WHERE=$3

echo "$1 - $2, $3" >> ~/notes/recommendations

