#! /bin/sh

TMP_MP3=/tmp/soundcloud-tag.mp3
TMP_COVER=/tmp/soundcloud-tag.jpg
OUT_DIR=~/Downloads
DEFAULT_ALBUM="Mixed"

if [ "$1" = "--help" ] || [ "$1" = "help" ]; then
  echo "$ soundcloud-tag <url>"
  echo "Download and tag a track from soundcloud"
  echo ""
  echo "Parameters:"
  echo "  \$1: url of soundcloud track to be downloaded"
  echo ""
  echo "Example:"
  echo "  $ soundcloud-tag https://soundcloud.com/izzy-cham/mastering-4hades"
  echo ""
  echo "Possibly unwanted behavior:"
  echo "  - Default album name is: $DEFAULT_ALBUM"
  echo "  - Artist is not the artist but the soundcloud account name"
  exit
fi

URL="$1"
[ -z "$URL" ] && {
  echo "Please pass a soundcloud track url to download"
  exit
}
[ -z "$(echo "$URL" | grep -F 'soundcloud.com')" ] && {
  echo "The url does not point to soundcloud.com"
  exit
}

echo "# downloading"
HTML="$(curl -s "$URL")"

echo "## mp3"
youtube-dl --audio-format "mp3" -o "$TMP_MP3" --no-continue "$URL" | grep -F "[download]" | grep -F -v "$TMP_MP3"

echo "## cover"
COVER=$(echo "$HTML" | grep -E "image\" content=\"https[^\"]+" -o | cut -d\" -f3 | tail -n 1)
curl -s "$COVER" > $TMP_COVER

echo "# tagging"
ARTIST_TITLE=$(echo "$HTML" | grep -E "<title>.*</title>" | cut -d\| -f1 | cut -d\> -f2 | cut -d- -f2 | sed "s|^ ||" | sed "s|by|-|" | sed "s|&amp;|\&|")
ARTIST=$(echo "$ARTIST_TITLE" | cut -d- -f2 | sed 's|^ ||' | sed 's|\s*$||')
TITLE=$(echo "$ARTIST_TITLE" | cut -d- -f1 | sed 's|\s*$||')

echo "## ARTIST=$ARTIST"
id3tag -a "$ARTIST" $TMP_MP3 1> /dev/null
mid3v2 --TPE2 "$ARTIST" $TMP_MP3 1> /dev/null

echo "## TITLE=$TITLE"
id3tag -s "$TITLE" $TMP_MP3 1> /dev/null

id3tag -A "$DEFAULT_ALBUM" $TMP_MP3 1> /dev/null

echo "# writing"
OUT_FILE="$OUT_DIR/$ARTIST - $TITLE.mp3"
echo "## OUT_FILE=$OUT_FILE"

# see: https://stackoverflow.com/a/18718265
ffmpeg -i $TMP_MP3 -i $TMP_COVER -map 0:0 -map 1:0 -c copy -id3v2_version 3 -metadata:s:v title="Album cover" -metadata:s:v comment="Cover (front)" -y -loglevel quiet "$OUT_FILE"
