#! /bin/sh

LOCAL_MUSIC=~/music
MNT_POINT=/media/hd

if [ "$1" = "--help" ] || [ "$1" = "help" ]; then
  echo "$ sync-music"
  echo "Sync ~/music with /dev/sdb mounted on /media/usb"
  exit
fi

sudo rsync -avr --delete $LOCAL_MUSIC/ $MNT_POINT

