#! /bin/bash

# flags
VERBOSE="-q"
VIDEO="--fullscreen --play-and-exit"
PLAYLIST="--no-loop --no-repeat --no-random"
DNC="--compressor-rms-peak 0 --compressor-attack 50 --compressor-release 300 --compressor-threshold -20 --compressor-ratio 20 --compressor-knee 1 --compressor-makeup-gain 12" # src: https://www.geekality.net/2013/11/01/settings-for-vlc-dynamic-range-compression/

# --no-sout-mono-downmix - if using stero speakers

if [[ $1 = "--help" ]] || [[ $1 = "help" ]]; then
  echo "$ vv"
  echo "Open vlc with better defaults"
  echo ""
  echo "Flags:"
  echo "  verbosity: $VERBOSE"
  echo "  video:     $VIDEO"
  echo "  playlist:  $PLAYLIST"
  echo "  dynamic range compression: $DNC"
  echo ""
  echo "Parameters:"
  echo "  [\$1]: audio delay in ms, for bluetooth speakers (--audo-desync)"
  exit
fi

if [[ -n $1 ]]; then
  DELAY=$1
  #vlc $VERBOSE $VIDEO $PLAYLIST "--audio-desync=-$DELAY" "--sub-delay=-$($(($DELAY/100.0)))" "${@:2}"
  mpv --profile=movie "${@:2}"
  # ${@:2} src: https://stackoverflow.com/a/9057392
else
  vlc $VERBOSE $VIDEO $PLAYLIST
fi

