#! /bin/bash

if [[ $1 = "--help" ]] || [[ $1 = "help" ]]; then
  echo "$ vx <script-name>"
  echo "Create a new executable file and open it in vim."
  echo ""
  echo "Parameters:"
  echo "  \$1: name of the new script"
  echo ""
  echo "Example:"
  echo "$ vx connect.sh"
  exit
elif [[ -z $1 ]]; then
  echo "Missing parameter: script-name"
  exit
fi

FILE=$1
echo "#! /bin/bash

if [[ \$1 = \"--help\" ]] || [[ \$1 = \"help\" ]]; then
  echo \"$ $FILE <>\"
  echo \"\"
  echo \"\"
  echo \"Parameters:\"
  echo \"  \\\$1: \"
  echo \"\"
  echo \"Example:\"
  echo \"  $ $FILE\"
  exit
fi
" >> $FILE

chmod +x $FILE
vim $FILE

