#! /bin/bash

if [[ $1 = "--help" ]] || [[ $1 = "help" ]]; then
  echo "$ watch-daemon"
  echo "Test various condition in regular intervals"
  echo ""
  echo "Parameters:"
  echo "  \$1: "
  echo ""
  echo "Example:"
  echo "$ watch-daemon"
  exit
fi

if [[ -n $(xinput --list | grep "Apple Inc. Apple Keyboard" ) ]]; then
  setup-keys 
  # how do I only exec this the first time the keyboard is connected
fi

# watch for available bluetooth devices?

