#! /bin/bash

DIR="/etc/NetworkManager/system-connections"

if [ "$1" = "--help" ] || [ "$1" = "help" ]; then
  echo "$ wifi-pass"
  echo "Print wifi password for currently connected wifi"
  exit
fi

NAME=$(nmcli device | grep "wifi " | grep -F connected | awk '{ print $4 }')

sudo su -c "cat '$DIR/$NAME'*" | grep "^psk" | cut -d= -f2 | tee >(xclip -sel clip)
