#! /bin/sh

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ] || [ -z "$1" ]; then
  cat << EOF
$ mimepreview EXTENSION
Return the preview handler for the given extension

Parameters:
  \$1: file extension to get the handler for

Example:
  $ mimepreview pdf
  #=> pdftotext
EOF
  exit
fi

[ -f "$1" ] && { echo "Don't pass in file, file extensions only" ; exit 12 ; }
EXT="$1"

# exit 1 means the handler does not like to be run in the background (&)
case $EXT in
  md) echo "glow -s dark";;
  epub) echo epub-toc;;
  pdf) echo "pdftotext -";;
  *) echo cat;;
esac
exit 0 # explicit 0 exit for handlers fine to run in the background
