#! /bin/bash

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  cat << EOF
$ mimetype FILE
Classify file type and return a file extension

Parameters:
  \$1: name of the file

Example:
  $ mimetype mime
  #=> sh
  $ mimetype song.mp3
  #=> mp3
EOF
  exit
fi

raw_file="$1"
if echo $raw_file | grep "^~" >/dev/null; then
  raw_file="$(echo $raw_file | sed "s|~|$HOME|")"
fi

FILE="$(readlink -f "$raw_file")"

classify_file() {
  basename="$1"

  case $(basename "$basename") in
    tabs|links)
      echo browser-tabs
      exit 0;;
    tmux.yml)
      echo tmux-project
      exit 0;;
  esac

  fileext=
  arrayOfSupportedExtendedExtensions=(bz2 gz gpg part) # like tar.bz2; tar.gz; mkv.gpg; pdf.part
  if printf '%s\0' "${arrayOfSupportedSecondExtensions[@]}" | grep -F -x -z -- "${basename##*.}" >/dev/null; then
    # contains, source: https://stackoverflow.com/a/47541882

    # get first extension
    fileext="${basename##*.}"
    basename=${basename%.*}

    # get second extension
    fileext="${basename##*.}.$fileext"
    basename=${basename%.*}
  elif echo "$basename" | grep -F . >/dev/null; then
    fileext=${basename##*.}
    basename=${basename%.*}
  fi
  fileext="$(echo $fileext | tr '[:upper:]' '[:lower:]')" # to lowercase

  if [ -z "$fileext" ] || echo "$fileext" | grep " " >/dev/null; then
    DETERMINED_FILE_TYPE=
    if file -b "$1" | grep "Unicode text" >/dev/null; then
      DETERMINED_FILE_TYPE="Unicode text"
    else
      DETERMINED_FILE_TYPE="$(file -b "$1" | cut -d, -f1)"
    fi
    if grep -F "cannot open" <<< $DETERMINED_FILE_TYPE >/dev/null; then
      echo "[ERR] file does not exist: $FILE"
      exit 2
    fi

    case "$DETERMINED_FILE_TYPE" in
      "POSIX shell script"|"POSIX shell script text executable") echo sh;;
      "Bourne-Again shell script"|"Bourne-Again shell script text executable") echo bash;;
      "UTF-8 Unicode text"|"Unicode text"|"ASCII text"|"JSON data"|"JSON text data"|data|"XML 1.0 document"|"CSV ASCII text") echo txt;;
      "a /bin/octave script") echo octave;;
      "RAR archive data") echo rar;;
      "HTML document") echo html;;
      "empty"|"makefile script") echo txt;;
      "directory") exit 1;; # constantly produces logs without any real errors
      *) echo [ERR] mimetype not configured: $DETERMINED_FILE_TYPE
        echo "unconfigured mimetype: $DETERMINED_FILE_TYPE" >$ORG_INBOX/mimetype-$(date +%s)
        exit 1;;
    esac
  else
    echo $fileext
  fi
}

classify_file "$FILE"
