#! /bin/sh

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ] || [ -z "$1" ]; then
  cat << EOF
$ mimeedit EXTENSION
Return the edit handler for the given extension

Parameters:
  \$1: file extension to get the handler for

Example:
  $ mimeedit file.md
  #=> $EDITOR
  $ mimeedit file.docx
  #=> libreoffice
EOF
  exit
fi

[ -f "$1" ] && { echo "Don't pass in file, file extensions only" ; exit 12 ; }
EXT="$1"

# exit 1 means the handler does not like to be run in the background (&)
case $EXT in
  ods|odt|docx|xlsx|xltx) echo libreoffice;;
  pdf) echo masterpdfeditor4;;
  sc) echo sc-im; exit 1;;
  *) echo $EDITOR; exit 1;;
esac
exit 0 # explicit 0 exit for handlers fine to run in the background
