#! /bin/sh

DIR=`dirname $0`
LOG_FILE=$XDG_DATA_HOME/xdg-open.log

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ] || [ -z "$1" ]; then
  cat <<EOF
$ xdg-open URI
Wrapper for mime script to handle URIs and route xdg-open calls

Parameters:
  \$1: URI of resource to be opened

Example:
  $ xdg-open file:///home/jneidel/org/3_areas/fs/book-note-example.png
  $ xdg-open https://y.com.sb/watch?v=fES9ZrLXY9s
EOF
  exit
fi

command -v $BROWSER >/dev/null || { echo "$BROWSER is not installed or \$BROWSER is not set" 1>&2; exit 127; }

URI="$@"

handle_uri() {
  case `echo $URI | cut -d: -f1` in
    http|https) $BROWSER "$URI";;
    file) $DIR/mime open `echo $URI | cut -d/ -f3- `;;
    *) $DIR/mime open "$URI";;
  esac
}

handle_uri || {
  echo "Handling failed for URI: '$URI'" >>$LOG_FILE
  false
}
