#! /bin/sh

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  cat <<EOF
$ active-projects
The number of active org projects
EOF
  exit
fi

command -v find >/dev/null || { echo "find is not installed" 1>&2; exit 127; }

number_of_projects=$(find $ORG_PROJECTS -mindepth 1 -maxdepth 1 -type d -name "[^.]*" | wc -l)

# You can only realistically manage about 10 active projects at a time.
if [ "$number_of_projects" -gt 10 ]; then
  echo "󰻷$number_of_projects"
else
  echo "$number_of_projects"
fi
