#! /bin/sh

FILE="/home/jneidel/org/3_resources/exercise, fitness, sports, training/My Sustainable Training Routine.org"

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  cat <<EOF
$ append-health-tracking-date
Appends current date to org file: $FILE
To be called through cron.

Example:
  $ append-health-tracking-date
EOF
  exit
fi

#       Date | Squat sets/load | Nordic curls | Push ups | Chin ups | Hollow hold | Yoga | Notes |
printf "| %s |                 |              |          |          |             |      |                                            |\n" "$(date '+%Y-%m-%d %a')" >>"$FILE"
