#! /bin/sh

FILE="/home/jneidel/org/3_resources/exercise, fitness, sports, training/My Sustainable Training Routine.org"

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  cat <<EOF
$ append-health-tracking-date
Appends current date to org file: $FILE
To be called through cron.

Example:
  $ append-health-tracking-date
EOF
  exit
fi

#       Date | Squat load | Nordic curls | Push ups | Pull ups | Plank | Yoga ||
printf "| %s |            |              |          |          |       |      |\n" "$(date '+%Y-%m-%d %a')" >>"$FILE"
