#! /bin/sh

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  cat <<EOF
$ gen-note DIR
Easily add a new note to a directory.

Filename is determined by the supplied title.
Empty files are ignored.
EOF
  exit
fi

hash awk generate-orgmode-metadata emacs-open || exit 127

dir="$1"
[ ! -z "$dir" ] && cd "$dir"
tmp=$(mktemp --suffix=.org)

file_contents_without_metadata() {
  grep -ve "#+" -e "^$" $tmp
}

generate-orgmode-metadata >$tmp

emacs-open title-insert $tmp -t

if [ -z "$(file_contents_without_metadata)" ]; then
  echo "Discarded empty file."
  exit 0
fi

filename=
filetitle=`grep -Po "^#\+title: \K.*" $tmp`
if [ -z "$filetitle" ]; then
  filename="$dir/qc_$(date +%s).org"
else
  if echo $filetitle | grep -F / >/dev/null; then
    fileTitle="$(echo $filetitle | tr '/' '_')"
  fi
  filename="$dir/$filetitle.org"
fi

cp $tmp "$filename"
echo "Wrote to: $filename"
