#! /bin/sh

DURATIONS_FILE="$ORG_AREAS/org/weekly review/durations.txt"

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  cat <<EOF
$ weekly-review
Guide me through the Weekly Review

Manipulate the timer with the words:
- pause
- resume
EOF
exit
fi

items_in_inbox=

# helpers
print_header() {
  printf "\033[1;32m$1\033[0m\n"
}
print_control() {
  printf "\033[1;34m$1\033[0m"
}

start_time=$(date +%s)
calc_total_time() {
  end_time=$(date +%s)
  secs_passed=$(($end_time-$start_time))
  mins_passed=$(($secs_passed/60))
  mins_passed_leftover_sec=$(($secs_passed%60))

  print_control "Time passed: ${mins_passed}m ${mins_passed_leftover_sec}s\n"

  echo "$(date +%b%d): ${mins_passed}m, $items_in_inbox items" >>"$DURATIONS_FILE"
  echo "Stats were added to: $DURATIONS_FILE"
}
is_paused=0
passed_before_pause=0
pause_timer() {
  if [ "$is_paused" -eq 1 ]; then
    print_control "Timer is already paused\n"
  else
    is_paused=1
    pause_time=$(date +%s)
    passed_before_pause=$(($pause_time-$start_time))
    print_control "[Timer paused]\nContinue the review process with 'resume'\n"
  fi
}
resume_timer() {
  if [ "$is_paused" -eq 0 ]; then
    print_control "Timer is not paused\n"
  else
    is_paused=0
    resume_time=$(date +%s)
    start_time=$(($resume_time-$passed_before_pause))
    print_control "[Timer resumed]\n"
  fi
}

step=0
next_step() {
  step=$(($step+1))
}
next_step

prompt_continue() {
  print_control "Continue? "
  read ans
  case $ans in
    pause)
      pause_timer
      prompt_continue;;
    resume)
      resume_timer
      prompt_continue;;
    *)
      if [ "$is_paused" -eq 1 ]; then
        print_control "\nCan't continue with the timer paused\n"
        prompt_continue
      else
        next_step
        printf "\n"
      fi
      ;;
  esac
}

split_below() {
  local step_name="$1"
  local cmd="$2"

  tmux split-window -v -l 70%
  tmux send-keys "clear && figlet $step_name" "Enter" "$cmd" "Enter"
}

# parts of the review
email() {
  print_header "$step. Clear out your email"
  cat <<EOF
outcome:
  - empty kudu inbox

EOF
  kitty --class mosh --name kudu mosh k >/dev/null 2>&1 &
  prompt_continue
}

desk() {
  print_header "$step. Clear out your desk!"
  cat <<EOF
outcome:
  - no paper notes or other TODO items on the desk

EOF
  prompt_continue
}

camscanner() {
  print_header "$step. Process CamScanner"
  cat <<EOF
outcome:
  - scanned all clipping in the drawer
  - Daily planner pages
  - all images in "to process" folder have had their text extracted

EOF
  $BROWSER https://www.camscanner.com/file/recent >/dev/null 2>&1 &
  prompt_continue
}

calendar() {
  print_header "$step. Check your calendar\n"
  cat <<EOF
outcome:
  - past events are in archive.rem

EOF
  lf -remote "send cd '$ORG_CALENDAR/main'" &

  split_below "Calendar" "remint"

  printf "\nShow event calendar next\n"
  prompt_continue

  split_below "Events" "events; remint"

  prompt_continue
}

messenger() {
  print_header "$step. Clear out messengers"
  cat <<EOF
outcome:
  - empty signal
  - empty whatsapp

EOF
  prompt_continue
}

otter() {
  print_header "$step. Clear out otter"
  cat <<EOF
outcome:
  - no unprocessed transcripts

EOF
  prompt_continue
}

browser_tabs() {
  print_header "$step. Close all browser tabs"
  cat <<EOF
outcome:
  - only start page open

EOF
  prompt_continue
}

github() {
  print_header "$step. Clear your GitHub notifications"
  cat <<EOF
outcome:
  - no notifications
  - up-to-date on GitHub newsfeed

EOF
  $BROWSER https://github.com/dashboard-feed >/dev/null 2>&1 &
  $BROWSER https://github.com/notifications?query=is%3Aunread >/dev/null 2>&1 &

  prompt_continue
}

newsboat() {
  print_header "$step. Clear out newsboat"
  cat <<EOF
outcome:
  - no unread feeds

EOF
  split_below "Newsboat" "new"

  prompt_continue
}

bulletjournal() {
  print_header "$step. Copy notes from Bullet Journal"
  cat <<EOF
outcome:
  - exported everything useful

EOF

  prompt_continue
}

files() {
  print_header "$step. Clear temp directories"
  cat <<EOF
outcome:
  - empty ~, Downloads

EOF
lf -remote "send cd '$HOME/Downloads'" &

prompt_continue
}

pre_org_inbox() {
  fetch-annotations &
  signal-to-inbox &
}
org_inbox() {
  print_header "$step. Clear your org inbox"
  cat <<EOF
outcome:
  - $ORG_INBOX is empty

EOF
  items_in_inbox="$(ls $ORG_INBOX/* | wc -l)"

  lf -remote "send cd '$ORG_INBOX'" &
  prompt_continue
}

task_manager() {
  # excluded because this is seperate for me
  # tasks need their own review process and
  # I need to think about what I want to do over the next week,
  # which I'm not capable off if the weekly review is as long as it currently is
  print_header "$step. Choose your tasks for the week"
  cat <<EOF
outcome:
  - taskwarrior has next weeks tasks scheduled and inbox is emtpy

EOF
split_below "Tasks" "task list"

prompt_continue
}

copy_accountability() {
  print_header "$step. Copy accountability logs from signal"
  cat <<EOF
outcome:
  - Accountability tasks for all budies copied into org

EOF
  prompt_continue
}

gallery() {
  print_header "$step. Extract any notes from your image gallery"
  cat <<EOF
outcome:
  - Note/todo photos or screenshots are deleted

EOF
  prompt_continue
}

dotfiles() {
  # justification: effort grows exponentially with the number of changes, uncommitted changes at risk of being lost
  print_header "$step. Commit all changes in the dotfiles"
  cat <<EOF
outcome:
  - green git status

EOF
  split_below "dotfiles" "dot"
  prompt_continue
}

backups() {
  # justification: needs to be done regularly to avoid loss of data
  print_header "$step. Backup the homeserver"
  cat <<EOF
outcome:
  - sync started

EOF
  split_below "Backups" "ho"
  prompt_continue
}

email
github
backups
dotfiles
messenger
otter
gallery
desk
bulletjournal
camscanner
newsboat
pre_org_inbox
browser_tabs
calendar
copy_accountability
files
org_inbox

echo "Congrats! You're done"
calc_total_time
