#! /bin/sh

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  cat <<EOF
$ is-focus-challenge
Determine if there is an ongoing focus challenge.

If yes: zero exit code
If no: non-zero exit code

Flags:
  -v: inverse
EOF
  exit
fi

hash rem || exit 127

ordered_calendar_entries() {
  LOOKBACK_TIME_SPAN=48
  remind -t$LOOKBACK_TIME_SPAN -g $DOTREMINDERS $(date -d "$LOOKBACK_TIME_SPAN days ago" +%Y-%m-%d) 2>/dev/null
}

most_recent_focus="$(ordered_calendar_entries | grep -Fi "focus" | tail -n1)"
most_recent_no_media="$(ordered_calendar_entries | grep -Fi "no media" | tail -n1)"

return_active_focus() {
  echo "⛔👉 Focus challenge is active 👈⛔" >&2
  if [ "$IS_INVERSE" -eq 0 ]; then
    exit 0
  else
    exit 1
  fi
}
return_active_no_media() {
  echo "⛔📺 No media challenge is active 📻⛔" >&2
  if [ "$IS_INVERSE" -eq 0 ]; then
    exit 0
  else
    exit 1
  fi
}
return_inactive() {
  if [ "$IS_INVERSE" -eq 0 ]; then
    exit 1
  else
    exit 0
  fi
}

IS_INVERSE=0
[ "$1" = "-v" ] && IS_INVERSE=1

if echo $most_recent_focus | grep -ie "start" -e "🚀" >/dev/null; then
  return_active_focus
elif echo $most_recent_no_media | grep -ie "start" -e "🚀" >/dev/null; then
  return_active_no_media
elif echo $most_recent_focus | grep -ie "end" -e "🏁" >/dev/null || echo $most_recent_no_media | grep -ie "end" -e "🏁" >/dev/null; then
  return_inactive
else
  echo "🤷 Focus challenge evaluation was inconclusive 🤷" >&2
  exit 10
fi
