#! /bin/sh

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  cat <<EOF
$ isfaturday
Return non-zero exit code if it is not
EOF
  exit
fi

command -v rem >/dev/null || { echo "remind is not installed" 1>&2; exit 127; }

rem | grep "Faturday" >/dev/null
