#! /bin/zsh

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ] || [ -z "$ORG_RESOURCES" ]; then
  cat <<EOF
$ select-resource
Interactively select a resource in $ORG_RESOURCES
EOF
  exit
fi

hash gum || exit 127

declare -a resources
while IFS= read -r dir; do
  [[ -z "$dir" ]] && continue
  resources+=("$dir")
done < <(find "$ORG_RESOURCES" -maxdepth 1 -mindepth 1 -type d -name "[^.]*" | rev | cut -d/ -f1 | rev)

gum filter ${resources[*]}
