#! /bin/zsh

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ] || [ -z "$ORG_PROJECTS" ]; then
  cat <<EOF
$ select-design
Interactively select a design in $ORG_PROJECTS/.design

If caller is not a tty, print list of options instead.
EOF
  exit
fi

hash gum || exit 127

has_tty=true
if [ ! -t 0 ]; then
    has_tty=false
fi

declare -a designs
while IFS= read -r dir; do
  [[ -z "$dir" ]] && continue
  designs+=("$dir")
done < <(find "$ORG_PROJECTS/.design" -maxdepth 2 -mindepth 2 -type d -name "[^.]*" | rev | cut -d/ -f1-2 | rev)

if $has_tty; then
  gum filter ${designs[*]}
else
  printf "%s\n" "${designs[@]}"
fi
