#! /bin/bash

# Test a list of pkgs against the locally installed pkgs

# Requires the format:
# pkg-name pkg-version link

# The output will be added to:
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
PKGS_FILE=$DIR/manual-pkgs

if [[ $1 = "--help" ]] || [[ $1 = "help" ]]; then
  echo "$ test-pkg"
  echo ""
  echo ""
  echo "Parameters:"
  echo "  \$1: "
  echo ""
  echo "Example:"
  echo "$ test-pkg"
  exit
fi

while read line; do
  PKG=$(echo $line | cut -d " " -f 1)
  VERSION=$(echo $line | cut -d " " -f 2)
  LINK=$(echo $line | cut -d " " -f 3)

  MATCH=$(yay -Q | grep $PKG)
  if [[ -n $MATCH ]]; then
    MATCH_VERSION=$(echo $MATCH | cut -d " " -f 2)
    if $DIR/version-gt $MATCH_VERSION $VERSION; then
      OUT_STR="$PKG $VERSION $LINK"
      if [[ -z $(cat $PKGS_FILE | grep "$OUT_STR" ) ]]; then
        echo $OUT_STR >> $PKGS_FILE
      fi
    fi
  fi
done

