#! /bin/bash

# Run script for test-pkg and reformat-arch-news

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

PKGS_FILE="$DIR/manual-pkgs"
touch $PKGS_FILE # eliminate file does no exist error 

curl -SsfL https://www.archlinux.org/feeds/news/ | reformat-arch-news.js | test-pkg

sort -o $PKGS_FILE $PKGS_FILE

