#! /bin/sh

if [ "$1" = "--help" ] || [ "$1" = "help" ]; then
  cat <<EOF
$ disable-mullvad-for <command>
Wrapper that executes a command after making sure that the vpn
is deactivated.

This is because scp, git push (to ssh), beet import and a few other commands
have a really long delay with mullvad activated.

Parameters:
  \$1: command to be executed

Example:
$ disable-mullvad-for git push
$ disable-mullvad-for beet import *
EOF
  exit
fi


if mullvad lockdown-mode get | grep ": on" >/dev/null; then
  mullvad lockdown-mode set off >/dev/null
  mullvad disconnect
  printf "\033[1;31mturned mullvad off\n\033[0m"

  transmission.sh >/dev/null && transmission-kill

  sleep 3
  echo "running '$@'"
  "$@"
  EXIT_CODE=$?

  mullvad lockdown-mode set on > /dev/null
  mullvad connect
  printf "\033[1;32mturned mullvad back on again\n\033[0m"

  if [ "$EXIT_CODE" -gt 0 ]; then
    false
  else
    true
  fi
else
  echo "running '$@'"
  "$@"
fi
