#! /bin/sh

if [ "$1" = "--help" ] || [ "$1" = "help" ]; then
  echo "$ disable-mullvad-for <command>"
  echo "Wrapper that executes a command after making sure that the vpn"
  echo "is deactivated."
  echo ""
  echo "This is because scp, git push (to ssh), beet import and a few other commands"
  echo "have a really long delay with mullvad activated."
  echo ""
  echo "Parameters:"
  echo "  \$1: command to be executed"
  echo ""
  echo "Example:"
  echo "$ disable-mullvad-for git push"
  echo "$ disable-mullvad-for beet import *"
  exit
fi


if [ ! "$(mullvad block-when-disconnected get)" = "Network traffic will be allowed when the VPN is disconnected" ]; then
  mullvad block-when-disconnected set off > /dev/null
  mullvad disconnect
  printf "\033[1;31mturned mullvad off\n\033[0m"

  transmission.sh > /dev/null && transmission-kill

  sleep 3
  echo "running '$@'"
  # switch stdout/stderr, grep stderr on KeybordInterrupt = $?>1
  "$@" 3>&1 1>&2 2>&3 | grep "KeyboardInterrupt"
  EXIT_CODE=$?
  echo "EXIT CODE: $EXIT_CODE"

  mullvad block-when-disconnected set on > /dev/null
  mullvad connect
  printf "\033[1;32mturned mullvad back on again\n\033[0m"

  if [ "$EXIT_CODE" -gt 1 ]; then
    false
  else
    true
  fi
else
  echo "running '$@'"
  $@
fi

