#! /bin/sh

if [ "$1" = "--help" ] || [ "$1" = "help" ]; then
  echo "$ mullvad-toogle"
  echo "Toggle mullvads block-when-disconnected option"
  exit
fi

if [ "$(mullvad lockdown-mode get)" = "Network traffic will be allowed when the VPN is disconnected" ]; then
  mullvad lockdown-mode set on > /dev/null
  printf "lockdown-mode set \033[1;32mon\n"
  mullvad connect
  echo "mullvad connect"
else
  transmission.sh > /dev/null && transmission-kill

  mullvad lockdown-mode set off > /dev/null
  printf "lockdown-mode set \033[1;31moff\n"
  mullvad disconnect
  echo "mullvad disconnect"
fi
