#! /bin/sh

if [ "$1" = "--help" ] || [ "$1" = "help" ]; then
  echo "$ mullvad-toogle"
  echo "Toggle mullvads block-when-disconnected option"
  exit
fi

if [ "$(mullvad block-when-disconnected get)" = "Network traffic will be allowed when the VPN is disconnected" ]; then
  mullvad block-when-disconnected set on > /dev/null
  printf "block-when-disconnected set \033[1;32mon\n"
  mullvad connect
  echo "mullvad connect"
else
  transmission.sh > /dev/null && transmission-kill

  mullvad block-when-disconnected set off > /dev/null
  printf "block-when-disconnected set \033[1;31moff\n"
  mullvad disconnect
  echo "mullvad disconnect"
fi

