#! /bin/sh

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ] || [ -z "$1" ]; then
  cat <<EOF
$ pe-pb TICKER
Get the P/E & P/B ratios of a stock

Source: Yahoo finance

Parameters:
  \$1: ticker symbol, e.g. NFLX

Example:
  $ pe-pb nflx
  #=> 40.16;12.53
EOF
  exit
fi

command -v curl >/dev/null || { echo "curl is not installed" 1>&2; exit 127; }

TICKER="$(echo $1 | tr a-z A-Z)"

tmp=$(mktemp)
fetch() {
  curl -Ss "https://finance.yahoo.com/quote/$TICKER/" \
    -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36' >$tmp 2>/dev/null 
}
pe() {
  cat $tmp | grep -Po "Trailing P/E *</p>.*?>\K.+?(?= *</p>)" -m1 | head -n1
}
pb() {
  cat $tmp | grep -Po "Price/Book.*?</p>.*?>\K.+?(?= *</p>)" -m1 | head -n1
}

fetch
printf "%s;%s\n" $(pe) $(pb)
