#! /bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
IP=$(cat "$DIR/current-mpd-ip")

if [ "$1" = "--help" ] || [ "$1" = "help" ] || [ -z "$1" ]; then
  echo "$ mpc-vol"
  echo "Change volume to/by passed parameter, if mpd is playing."
  echo ""
  echo "Parameters:"
  echo "  \$1: volume difference (+2) or value (40)"
  echo ""
  echo "Example:"
  echo "$ mpc-vol -2"
  exit
fi

[ "$(mpcc status | grep "^\[" | cut -d] -f1 | cut -d\[ -f2)" = "playing" ] && {
  # try remote
  timeout 1 mpc -h "$IP" -p "$PORT" "vol $1" 2> /dev/null

  # but don't change local
  # mpcc vol "$1" > /dev/null
  exit 0
}

