#! /bin/sh

# Receive the cover from send-cover

REMOTE_COVER_LOCATION=/tmp/mpd-cover.jpg
COVER_LOCATION=~/tmp/cover.jpg
TMP_LOCATION=/tmp/mpd-cover.jpg

function startConky {
  conky -c ~/.config/conky/mpd.conf 2> /dev/null
}
function getConkyPid {
  ps | grep " conky" | cut -dp  -f1 | sed -e 's/^[[:space:]]*//' | sed -e 's/[[:space:]]*$//'
}
function killConky {
  kill $(getConkyPid) > /dev/null 2> /dev/null
}
function restartConky {
  killConky
  startConky
  # due to a bug, where the image file that conky loads is <100kb,
  # it will not notice changes and thus not reload the conky once
  # the image changes, so I have to manually restart the conky
}
startConky

while true # kill conky after 3min of not playing anything
  do {
    [ ! "$(mpcc status | grep "^\[" | cut -d] -f1 | cut -d\[ -f2)" = "playing" ] && {
      killConky
    }
    sleep 3m
  }
done &

while true
  do ssh pii 'cat mpd-pipe' | {
    [ -z "$(getConkyPid)" ] && startConky # stark conky if killed for not playing for 3min

    scp pii:$REMOTE_COVER_LOCATION $TMP_LOCATION

    # check if current cover size is <100kb,
    # which would cause conky not to reload it on changes
    [ $(du -sh $COVER_LOCATION | cut -dK -f1) -lt 100 ] && RESTART_CONKY=1

    cp $TMP_LOCATION $COVER_LOCATION

    [ "$RESTART_CONKY" -eq 1 ] && {
      restartConky
      RESTART_CONKY=0
    }
  }
done

# todo: dynamic ssh adress
# fix: not killable with ^c

