#! /bin/bash

CONF=~/.config/mpd/mpd.conf

if [[ $1 = "--help" ]] || [[ $1 = "help" ]]; then
  echo "$ update-mpd-ip"
  echo "Update mpds ip address to the current one"
  echo ""
  echo "Example:"
  echo "$ get-mpd-ip"
  echo "-> 192.168.178.111"
  exit
fi

IP="217.197.81.9"

sed -i -r "s/\"192\.168\.178\..+\"/\"$IP\"/" $CONF
mpd --kill
mpd 2> /dev/null

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
echo $IP > "$DIR/current-mpd-ip"

