#! /bin/bash

CONF=~/.config/mpd/mpd.conf

if [[ $1 = "--help" ]] || [[ $1 = "help" ]]; then
  echo "$ update-mpd-ip"
  echo "Update mpds ip address to the current one"
  echo ""
  echo "Example:"
  echo "$ get-mpd-ip"
  echo "-> 192.168.178.111"
  exit
fi

IP=$(ipa | tr -t "\n" " " | cut -d " " -f1)

sed -i -r "s/\"[0-9]+(\.[0-9]+){3}\"/\"$IP\"/" $CONF

mpd --kill
mpd 2> /dev/null

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
echo $IP > "$DIR/current-mpd-ip"

