#! /bin/sh

if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
  cat <<EOF
$ co BRANCH_NAME|SEARCH_QUERY
git checkout a branch, via full name or search query

Parameters:
  \$1: either
    - full name of a branch
    - search phrase, which applies the first sole match
  \$2: pass '-1' for the search phrase to apply the first result

Examples:
  $ co main
  #=> checks out 'main'

  $ git branch
  #=>
    pager
    new-homepage
  $ co age
  #=>
    Multiple matches: narrow down your query
    new-homepage
    pager
  $ co age -1
  #=> checks out 'new-homepage'
  $ co ager
  #=> checks out 'pager'
EOF
  return 0
fi

command -v git >/dev/null || { echo "git is not installed" 1>&2; exit 127; }

is_jj() {
  jj status >/dev/null 2>&1 
}

if is_jj; then
  changeid=$(jj log --no-graph -r "heads(~description('')) | trunk()" -T 'change_id.short() ++ " " ++ committer.timestamp().format("%Y-%m-%d") ++ " " ++ bookmarks ++ " " ++ description.first_line() ++ "\n"' | gum filter | cut -d\  -f1)
  jj new -r $changeid
  exit 0
fi

branch_name=$1
if [ -z "$branch_name" ]; then
  echo "No branch name was supplied. See --help"
  exit 1
fi
TMP=$(mktemp)

if ! git checkout $branch_name 2>$TMP && /bin/cat $TMP | grep -F "did not match any file(s) known to git" >/dev/null; then
  search_phrase=$branch_name
  if git branch | grep $search_phrase >$TMP; then
    if [ `wc -l $TMP | awk '{ print $1 }'` -gt 1 ]; then
      if [ "$2" = "-1" ]; then
        git checkout `head -n1 $TMP`
      else
        echo "Multiple matches: narrow down your query"
        /bin/cat $TMP
      fi
    else
      echo "Found match!"
      git checkout `cat $TMP`
    fi
  else
    echo "No match for: $search_phrase"
    git --no-pager branch
    return 1
  fi
else
  /bin/cat $TMP
fi
