#! /bin/sh

# optimize:
# https://askubuntu.com/questions/873717/using-terminal-to-have-xflux-at-a-certain-temperature-at-all-times

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  cat <<EOF
$ bluelight start|stop
Start or stop the bluelight filter

Runable via cron
EOF
  exit
fi

hash xflux || exit 127

start_xflux() {
  xflux -k 3000 -l 52 -g 13 >/dev/null 2>&1
}
kill_xflux() {
  sleep 1s
  kill -9 $(pidof xflux) 2>/dev/null
}

start() {
  start_xflux
  ~/scripts/cron/natural-brightness
}

stop() {
  start_xflux # start before killing to reset screen temperature
  kill_xflux
  ~/scripts/cron/natural-brightness
}

export DISPLAY=:0
export XAUTHORITY=/run/user/1000/Xauthority
xauth add $(xauth -f $XAUTHORITY list|tail -1)

case $1 in
  start|on) start;;
  stop|off) stop;;
esac
