#! /bin/sh

export HOME=/home/jneidel
. $HOME/.zsh/org.env

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
rm -rf printf "$ cleanup-fs
Removes irrelevant files/dirs polluting the home directory
"; exit
fi

# files
rm -f ~/.python_history 2>/dev/null
rm -f ~/.sqlite_history 2>/dev/null
rm -f ~/.bash_history 2>/dev/null
rm -f ~/.hwid 2>/dev/null
rm -f ~/.octave_hist 2>/dev/null
rm -f ~/.Xauthority 2>/dev/null
rm -f ~/1 2>/dev/null
rm -f ~/.netrc 2>/dev/null
rm -f /tmp/ddc-lock 2>/dev/null
rm -f $ORG_INBOX/.org 2>/dev/null

# empty dirs
rmdir ~/Desktop 2>/dev/null
rmdir $ORG_INBOX/screenshots 2>/dev/null

# dirs
rm -rf ~/.w3m 2>/dev/null
rm -rf ~/.????????.ib-tws 2>/dev/null
rm -rf ~/.gradle/
rm -rf ~/.m2 2>/dev/null
rm -rf ~/Jts 2>/dev/null
rm -rf ~/.mono 2>/dev/null
rm -rf ~/.pki 2>/dev/null
rm -rf ~/.mongodb 2>/dev/null
rm -rf ~/.java 2>/dev/null
rm -rf ~/.icons 2>/dev/null
rm -rf ~/.bitmonero 2>/dev/null
rm -rf ~/.shared-ringdb 2>/dev/null
rm -rf ~/.standard-v14-cache 2>/dev/null
rm -rf ~/.gnome 2>/dev/null
rm -rf ~/.zi 2>/dev/null
rm -rf ~/.designer 2>/dev/null
rm -rf ~/Games ~/Screenshots 2>/dev/null

findex $ORG_MEDIA/phone/music -type d 'rmdir "$1"' 2>/dev/null

# move files into the right place
# sentixDir="$ORG_AREAS/assets/Aktien/Der Markt/Sentix - Markt Sentiment"
# mkdir -p "$sentixDir"
# sh -c "find $ORG_INBOX -name 'Analyse20*_ergebnisse.pdf' -exec sh -c 'mv \$1 \"$sentixDir/\"' sh {} ';'"
# sh -c "find $HOME/Downloads -name 'Analyse20*_ergebnisse.pdf' -exec sh -c 'mv \$1 \"$sentixDir/\"' sh {} ';'"

true
