#! /bin/sh

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  printf "$ cleanup-fs
Removes irrelevant files/dirs polluting the home directory
"; exit
fi

# files
rm -f ~/.python_history \
  ~/.sqlite_history \
  ~/.bash_history \
  ~/1 \
  ~/.hwid \
  ~/.octave_hist \
  ~/.Xauthority 2>/dev/null

# dirs
rmdir ~/Desktop \
  ~/.lyrics \
  ~/.newsboat 2>/dev/null
rm -rf ~/.w3m \
  ~/.m2 \
  ~/Jts \
  ~/.mono \
  ~/.pki \
  ~/.mongodb \
  ~/.java \
  ~/.icons \
  ~/.bitmonero \
  ~/.shared-ringdb \
  ~/.standard-v14-cache \
  ~/.gnome 2>/dev/null

~/scripts/cron/cron-notify-send "Cleaned up fs"
