#! /bin/sh

# notify-send wrapper including the dbus address

export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus

notify-send -t 3500 -u low -i preferences-system-notifications -a cron "$@"

