#! /bin/sh

LOCK_PROGRAM_NAME="xautolock"
LOCK_PROGRAM_SCRIPT="$HOME/scripts/i3/lock/autostart-lock"

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  cat <<EOF
$ disable-lock-at-home
Turn off xautolock when in home network
EOF
  exit
fi

command -v wifiname >/dev/null || { echo "wifiname script is not in PATH" 1>&2; exit 127; }

notify() {
  $(dirname $0)/cron-notify-send $1
}
is_lock() {
  pidof $LOCK_PROGRAM_NAME
}
turn_off_lock() {
  if is_lock >/dev/null; then
    kill $(pidof $LOCK_PROGRAM_NAME)
    notify "Lock off"
  fi
}
turn_on_lock() {
  if ! is_lock >/dev/null; then
    $LOCK_PROGRAM_SCRIPT
    notify "Lock on"
  fi
}

case "$(wifiname)" in
  TimeEater47) turn_off_lock;;
  *) turn_on_lock;;
esac
