#! /bin/sh

export HOME=/home/jneidel
. $HOME/.zsh/org.env

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ] || [ -z "$ORG_PROJECTS" ]; then
  cat <<EOF
$ org-projects-to-now-json
Transform org project directories into a json for jneidel.com/now
EOF
  exit
fi

hash jq || exit 127

get_project_list() {
  potential_projects=$(mktemp)
  find "$ORG_PROJECTS" -maxdepth 2 -mindepth 2 -not -path '*/.*' -not -path '*blocked' -not -path '*trip: *' | sort -Vr >$potential_projects

  ignored_projects=$(mktemp)
  find "$ORG_PROJECTS" -mindepth 3 -type f -name ".now-ignore" | rev | cut -d/ -f2- | rev | sort -V >$ignored_projects

  diff $potential_projects $ignored_projects --old-line-format='%L'
}

get_description() {
  index_file="$1"

  description_without_headers="$(head -n30 "$index_file" 2>/dev/null | grep -ve '^#+')"
  description_without_sections="$description_without_headers"
  if grep '^\*' -m1 "$index_file" >/dev/null 2>&1; then
    description_without_sections="$(echo "$description_without_headers" | grep -m1 '^\*' -B30 | head -n-1)"
  fi
  trimmed_oneline_description="$(echo "$description_without_sections" | sed 's/^[[:space:]]*//; s/[[:space:]]*$//')"

  echo $description_without_sections | $HOME/scripts/urlencode | sed 's/^%0A$//'
}

assemble_json() {
  json=$(mktemp)
  cat <<EOF >$json
{
"date_updated": "$(date '+%b%d at %H:%M')",
"projects": [
EOF

  get_project_list | while read -r project; do
    index_file="${project}/$ORG_INDEX_FILE_NAME"
    title="$(basename "$project" | sed 's/\.org$//')"
    status="$(basename "$(dirname "$project")")"
    # if echo $project | grep -ve "🟨" >/dev/null; then
    #   status="$(grep -Po '#\+(status|STATUS): \K.*' "$index_file" 2>/dev/null)"
    # fi
    description="$(get_description "$index_file")"

    printf '  { "title": "%s", "status": "%s", "description": "%s" },\n' "$title" "$status" "$description" >>$json
  done

  sed '$s/},/}/' -i $json # valid json: last line in array has no trailing ,
  echo "]}" >>$json

  if ! cat $json | jq >/dev/null; then # validate json
    echo "org-projects-to-now-json json validation failed at $(date) in $json" >>"$ORG_INBOX/org-projects-to-now-json errors"
    exit 1
  fi

  cat $json
}

upload_json() {
  json=$(mktemp)
  assemble_json >$json

  echo "Uploading to jneidel.*/now/now.json"
  scp -q $json u:~/html/jneidel.com/now/now.json
  scp -q $json u:~/html/jneidel.de/now/now.json
}
# assemble_json
~/scripts/cron/waitforinternet && upload_json
