#! /bin/sh
# todo: -x print-unread before and after to display new entries to user

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  printf "$ reload-newsboat
Reload newsboat caches in the background.
To be run via cron.
"; exit
fi

command -v newsboat >/dev/null || { echo "newsboat is not installed"; exit 1; }

ppid=$(ps -o ppid= -p $$)
if ps -p $ppid -o command | tail -n1 | grep -vi cron >/dev/null; then
  exit 1
fi

reload() {
  local NAME=$1
  newsboat -u ~/.config/newsboat/urls-$NAME -c ~/.config/newsboat/cache-$NAME.db --quiet -x reload &
}

reload clean
reload manga
reload pod
reload misc

reload_ent() {
  TMP=$(mktemp)
  cat ~/projects/bad_habits/gpg_key_pass | gpg --pinentry-mode loopback --batch --passphrase-fd 0 --output $TMP -d ~/.sensitive/.config/newsboat/cache-ent.db.gpg >/dev/null 2>&1
  newsboat -u ~/.sensitive/.config/newsboat/urls-ent -c $TMP --quiet -x reload
  mv $TMP /tmp/cache-ent.db
  gpg -er 75EEDD9E /tmp/cache-ent.db >/dev/null
  rm /tmp/cache-ent.db
  mv /tmp/cache-ent.db.gpg ~/.sensitive/.config/newsboat/
}
# reload_ent &

~/scripts/cron/cron-notify-send "Ran reload-newsboat" -t 1000
