#! /bin/sh
# todo: -x print-unread before and after to display new entries to user

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  printf "$ reload-newsboat
Reload newsboat caches in the background.
To be run via cron.
"; exit
fi

command -v newsboat >/dev/null || { echo "newsboat is not installed"; exit 1; }

newsboat -u ~/.config/newsboat/urls-clean -c ~/.config/newsboat/cache-blog.db --quiet -x reload &
newsboat -u ~/.config/newsboat/urls-manga -c ~/.config/newsboat/cache-manga.db --quiet -x reload &
newsboat -u ~/.config/newsboat/urls-pod -c ~/.config/newsboat/cache-pod.db --quiet -x reload &
newsboat -u ~/.config/newsboat/urls-music -c ~/.config/newsboat/cache-music.db --quiet -x reload &

~/scripts/cron/cron-notify-send "Ran reload-newsboat" -t 1000
