#! /bin/sh

FILE=~/code/notes/priority-journal

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  cat <<EOF
$ remind-journal
Send pestering notifications about filling out your journal if file hasn't been touched today

To be run via cron
EOF
  exit
fi

if [ `find $FILE -daystart -atime 0 | wc -l` -eq 0 ]; then
  ~/scripts/cron/cron-notify-send "Priority Journal" -t 10000 -u critical
fi
