#! /bin/sh

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  cat <<EOF
$ stop-bluelight
EOF
  exit
fi

command -v xflux >/dev/null || { echo "xflux is not installed" 1>&2; exit 127; }

xflux -k 3000 -l 52 -g 13 >/dev/null 2>&1 &
sleep 1s
kill -9 $(pidof xflux) 2>/dev/null
