#! /bin/sh

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  cat <<EOF
$ stop-bluelight
EOF
  exit
fi

command -v xflux >/dev/null || { echo "xflux is not installed" 1>&2; exit 127; }

export DISPLAY=:0
XAUTHORITY=/run/user/1000/Xauthority
xauth add $(xauth -f $XAUTHORITY list|tail -1)

# start xflux before killing to reset screen temperature
xflux -k 3000 -l 52 -g 13 >/dev/null 2>&1
sleep 1s
kill -9 $(pidof xflux) 2>/dev/null
