#! /bin/sh

. "$(dirname $0)/shared-environment"

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  cat <<EOF
$ scnext
Start the next sprint by creating the necessary files from templates.
EOF
  exit
fi

cd $DIR

ITERATION=`cat $SPRINT_NR`
NEXT_ITERATION=`printf "%03d" "$(($ITERATION+1))"`

echo "Incrementing iteration to: $NEXT_ITERATION"

# Todo: templates auslagern damit reusable by others
planning() {
  FILE=sprint-planning-$NEXT_ITERATION.md
  [ -e "$FILE" ] && return
}
review() {
  FILE=sprint-review-$ITERATION.md
  [ -e "$FILE" ] && return
}
retro() {
  FILE=sprint-retro-$ITERATION.md
  [ -e "$FILE" ] && return
}

# printf $NEXT_ITERATION >$SPRINT_NR
