#! /bin/sh

. "$(dirname $0)/shared-environment"

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  cat <<EOF
$ sco
s[lack]c[entral]o[pen]
Open everything concerning the current sprint.
EOF
  exit
fi

command -v $EDITOR >/dev/null || { echo "$EDITOR is not installed or \$EDITOR variable not set" 1>&2; exit 127; }

cd $DIR

ITERATION=`cat $SPRINT_NR`
PREV_ITERATION=`printf "%03d" "$(($ITERATION-1))"`

$EDITOR -c "vsp sprint-planning-checklist.md | sp ../future-habits.md | wincmd h | tabe sprint-review-$PREV_ITERATION.md | vsp sprint-review-checklist.md | sp z_fail-log.md | wincmd h | sp sprint-planning-$PREV_ITERATION.md | wincmd k | tabe sprint-retro-$PREV_ITERATION.md | vsp sprint-retro-checklist.md | wincmd h | tabn" sprint-planning-$ITERATION.md
