#! /bin/sh

. "$(dirname $0)/shared-environment"

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  cat <<EOF
$ scp
Open the current sprint planning

Parameter:
  next: open the upcoming sprints file
EOF
  exit
fi

command -v $EDITOR >/dev/null || { echo "$EDITOR is not installed or \$EDITOR variable not set" 1>&2; exit 127; }

cd $DIR

ITERATION=`cat $SPRINT_NR`

if [ "$1" = "next" ] || [ "$1" = "n" ]; then
  NEXT_ITERATION="$(( $ITERATION +1 ))"
  $EDITOR sprint-planning-$NEXT_ITERATION.md
else
  $EDITOR sprint-planning-$ITERATION.md
fi
