#! /bin/sh

DIR=/sys/class/backlight
XOB=/tmp/xobpipe

case "$(cat /etc/hostname)" in
  jneidel-x240) ARCH=intel_backlight ;;
  jneidel-x270) ARCH=intel_backlight ;;
  jneidel-e495) ARCH=amdgpu_bl0 ;;
  *) ARCH=intel_backlight
    echo "Hostname not configured; assuming $ARCH";;
esac

MAX=$(cat $DIR/$ARCH/max_brightness)
MIN=10

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  cat <<EOF
$ backlight COMMAND
Interact with the backlight.

Commands:
  get: get current brightness
  set BRIGHTNESS: set the brightness
  max: set the max brightness ($MAX)
  min: set the min brightness ($MIN)
  percent +/-N: set the brightness using percentages (+02, -5)

Example:
  $ backlight set 250
  $ backlight p +1 # increase brightness by 10%
  $ backlight p +02 # increase brightness by 2%
EOF
  exit
fi

FILE=$DIR/$ARCH/brightness
# you might need to run
#   sudo chown $USER
# on the brightness file, otherwise you wont be able to write it,
# not even with sudo

set_brightness() {
  if [ -n "$1" ] && [ "$1" -gt -1 ] && [ "$1" -lt "$(($MAX+1))" ]; then
    echo $1 >$FILE
    notification
  else
    echo "Invalid number passed to set"
    echo "It needs to be between 0 and $MAX"
    exit 1
  fi
}

notification() {
  BRIGHTNESS=$(get_brightness)
  BRIGHTNESS_PERCENT=$(($BRIGHTNESS*100/$MAX))
  echo $BRIGHTNESS_PERCENT >$XOB
}

get_brightness() {
  cat $FILE
}

percent() {
  if [ -z "$1" ]; then
    echo "No argument passed to percent"
    exit 1
  elif [ "$(echo $1 | cut -c 1)" = "+" ]; then
    PERCENTAGE=$(echo $1 | cut -d + -f 2)
    RES=$(echo "$(get_brightness)+(0.$PERCENTAGE*($MAX-5))" | bc | cut -d . -f 1)
    echo "r $RES"
    if [ "$RES" -lt -1 ]; then
      RES=0
    elif [ "$RES" -gt "$MAX" ]; then
      RES=$MAX
    elif [ "$(get_brightness)" -eq 0 ]; then
      RES=10
    fi
    set_brightness $RES
  elif [ "$(echo $1 | cut -c 1)" = "-" ]; then
    PERCENTAGE=$(echo $1 | cut -d - -f 2)
    RES=$(echo "$(get_brightness)-(0.$PERCENTAGE*($MAX-5))" | bc | awk '{printf "%f", $0}' | cut -d . -f 1)
    if [ "$RES" -lt -1 ] || [ "$RES" -eq -1 ] || [ "$RES" -eq -0 ]; then # weird edge cases, but I want display to go black
      RES=0
    elif [ "$RES" -gt "$MAX" ]; then
      RES=$MAX
    fi
    set_brightness $RES
  else
    PERCENTAGE=$1
    if [ "$PERCENTAGE" -gt 100 ] || [ "$PERCENTAGE" -lt 1 ]; then
      echo "Percentage need to be in range 1-100"
      exit 1
    fi

    RES=$(echo $(($MAX*$PERCENTAGE/100)) | awk '{printf "%f", $0}' | cut -d . -f 1)
    set_brightness $RES
  fi
}

case $1 in
  s|set) set_brightness $2;;
  g|get) get_brightness;;
  max) set_brightness $MAX;;
  min) set_brightness $MIN;;
  p|perc|percent) percent $2;;
  *) echo "Please pass a command. Pass 'help' for help.";;
esac
