#! /bin/sh

DIR=/sys/class/backlight

case "$(cat /etc/hostname)" in
  jneidel-x240) ARCH=intel_backlight ;;
  jneidel-e495) ARCH=amdgpu_bl0 ;;
  *) echo "Hostname not configured"; exit 1 ;;
esac


if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  printf "$ backlight <command>
Interact with the backlight.

Commands:
  set <brightness>: set brightness
  get: get current brightness
  max: set the max brightness
  min: set the min brightness
  percent: set the brightness using percentages (+2, -5)

Example:
  $ backlight set 250 # set brightness to max
  $ backlight p +1 # increase brightness by 10%
"
  exit
fi

FILE=$DIR/$ARCH/brightness
# you might need to run
#   sudo chown $USER
# on the brightness file, otherwise you wont be able to write it,
# not even with sudo
MAX=$(cat $DIR/$ARCH/max_brightness) # 851 on x240
MIN=10

set_brightness() {
  if [ -n "$1" ] && [ "$1" -gt -1 ] && [ "$1" -lt "$(($MAX+1))" ]; then
    echo $1 > $FILE
  else
    echo "Invalid number passed to set"
    echo "It needs to be between 0 and $MAX"
    exit 1
  fi
}

get_brightness() {
  cat $FILE
}

percent() {
  if [ -z "$1" ]; then
    echo "No argument passed to percent"
    exit 1
  elif [ "$(echo $1 | cut -c 1)" = "+" ]; then
    PERCENTAGE=$(echo $1 | cut -d + -f 2)
    RES=$(echo "$(get_brightness)+(0.$PERCENTAGE*($MAX-5))" | bc | cut -d . -f 1)
    if [ "$RES" -lt -1 ]; then
      RES=0
    elif [ "$RES" -gt "$MAX" ]; then
      RES=$MAX
    fi
    set_brightness $RES
  elif [ "$(echo $1 | cut -c 1)" = "-" ]; then
    PERCENTAGE=$(echo $1 | cut -d - -f 2)
    RES=$(echo "$(get_brightness)-(0.$PERCENTAGE*($MAX-5))" | bc | awk '{printf "%f", $0}' | cut -d . -f 1)
    if [ "$RES" -lt -1 ] || [ "$RES" -eq -1 ] || [ "$RES" -eq -0 ]; then # weird edge cases, but I want display to go black
      RES=0
    elif [ "$RES" -gt "$MAX" ]; then
      RES=$MAX
    fi
    set_brightness $RES
  else
    PERCENTAGE=$1
    if [ "$PERCENTAGE" -gt 100 ] || [ "$PERCENTAGE" -lt 1 ]; then
      echo "Percentage need to be in range 1-100"
      exit 1
    fi

    RES=$(echo $(($MAX*$PERCENTAGE/100)) | awk '{printf "%f", $0}' | cut -d . -f 1)
    set_brightness $RES
  fi
}

notification() {
  BRIGHTNESS=$(get_brightness)
  BRIGHTNESS_PERCENT=$(($BRIGHTNESS*100/MAX))
  HEAD="Brightness: $BRIGHTNESS_PERCENT ($BRIGHTNESS)"
  BODY="$(get-progress-string.sh 28 '▪' ' ' "$BRIGHTNESS_PERCENT")"

  notify-send -i brightness -h string:x-canonical-private-synchronous:brightness -u normal -t 1000 "$HEAD" "$BODY"
}

case $1 in
  s|set) set_brightness $2; notification;;
  g|get) get_brightness;;
  max) set_brightness $MAX;;
  min) set_brightness $MIN;;
  p|perc|percent) percent $2; notification;;
  *) echo "Please pass a command. Pass 'help' for help.";;
esac

