#! /bin/sh

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  cat <<EOF
$ gpt
Open AI chat in my browser
EOF
  exit
fi

# $BROWSER "https://claude.ai/chats" >/dev/null 2>&1
# $BROWSER "https://chatgpt.com/" >/dev/null 2>&1
# $BROWSER "https://chat.deepseek.com/" >/dev/null 2>&1
