#! /bin/sh

if [ "$1" = "--help" ] || [ "$1" = "help" ]; then
  echo "$ open_clip_mpv"
  echo "Play clipboard content in mpv"
  exit
fi

CLIP_CONTENT="$1"
[ -z "$1" ] && CLIP_CONTENT=$(get-clip)

if [ -t 1 ]; then
  echo $CLIP_CONTENT
fi

if echo $CLIP_CONTENT | grep -e invidious -e yewtu >/dev/null; then
  CLIP_CONTENT="$(echo $CLIP_CONTENT | sed 's|//.*invidious.*/|//www.youtube.com/|' | sed 's|//yewtu\.be/|//www.youtube.com/|')"
fi

if echo $CLIP_CONTENT | grep ".mp3" >/dev/null; then
  tmux new-window -n mpv -d "exec mpv --no-audio-display --no-video --profile=music '$CLIP_CONTENT'"
else
  tsp mpv --profile=overlay --fs "$CLIP_CONTENT" 2>/dev/null >/dev/null
fi
