#! /bin/sh

PIC_DIR=~/org/0_inbox/screenshots
FORMAT='screenshot_%y-%m-%d_%H:%M:%S.png'
mkdir -p $PIC_DIR

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  cat << EOF
$ screenshot [-s]
Take a screenshot

Flags:
  -s: select screen snippet (+3s delay)
  -s [delay]: select with custom delay (in secs)
EOF
  exit
fi

command -v scrot >/dev/null || { echo "scrot is not installed"; exit 1; }

mkdir -p $PIC_DIR

DELAY="1"
[ -n "$2" ] && DELAY="$2"

if [ "$1" = "-s" ]; then
  notify-send "screen shot in ${DELAY}s" -t 1000 -i camera
  sleep "$DELAY"s && \
  /bin/scrot "$FORMAT" -e "notify-send \"took screenshot\" -t 1000 -i camera; mv \$f $PIC_DIR" -z --freeze --select
else
  /bin/scrot "$FORMAT" -e "notify-send \"took screenshot\" -t 1000 -i camera; mv \$f $PIC_DIR" -z
fi
