#! /bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
DRY=
[ "$1" = "-d" ] && DRY=true
source $DIR/lib.sh

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  cat <<EOF
$ export-configs
Export the dotfiles onto the local machine.

Which files will be exported is specified in 'mappings'.
Only groups in 'used-groups' will be applied though.

Flags:
  -d: to dry-run without exporting anything
EOF
  exit
fi

if [ -z "$DRY" ]; then
  printf "Really overwrite local files? (y/N): "
  read ans
  if [ "$ans" != "y" ] && [ "$ans" != "Y" ]; then
    exit 0
  fi
fi

CATEGORY=""
function install-files {
  IFS=$'\n'
  for IN in $(cat /dev/stdin); do
    # categories
    [ ${IN:0:1} = "[" ] && {
      IN=${IN:1:-1} # strip []
      CATEGORY=$IN
      [ $(grep -f $IN_USE_TMP <<< $CATEGORY ) ] && echo "## $CATEGORY"
      continue
    }

    # category not in use
    [ ! $(grep -f $IN_USE_TMP <<< $CATEGORY ) ] && continue

    LOCAL="$HOME/$IN"
    REPO="$BASE/$IN"

    # directories
    [ -d "$REPO" ] && {
      copy-dir $REPO $LOCAL
      continue
    }

    # files
    [ -f "$REPO" ] && {
      copy-file $REPO $LOCAL
      continue
    }

    # commands
    CMD=$(echo "$IN" | cut -d " " -f1)
    REST=$(echo "$IN" | cut -d" " -f2-)
    case $CMD in
      create)
        create-dir "$HOME/$REST";;
      clean)
        copy-dir "$BASE/$REST" "$HOME/$REST";; # don't clean local
      run)
        run-command $IN;;
      *)
        echo "skipped:      $IN"
    esac
  done
}

cat $MAPPINGS |
  grep -v "^#" |
  grep -v "^\s*$" |
  install-files
