#! /bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
DRY=
[ "$1" = "-d" ] && DRY=true
source $DIR/lib.sh

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  cat <<EOF
$ import-configs
Import the dotfiles from the local machine into this directory.

Which files to import is specified in 'mappings'.
Only groups in 'used-groups' will be applied though.

Flags:
  -d: to dry-run without importing anything
EOF
  exit
fi

CATEGORY=""
function get-files {
  IFS=$'\n'
  for IN in $(cat /dev/stdin); do
    # categories
    [ ${IN:0:1} = "[" ] && {
      IN=${IN:1:-1} # strip []
      CATEGORY=$IN
      [ $(grep -f $IN_USE_TMP <<< $CATEGORY ) ] && echo "## $CATEGORY"
      continue
    }

    # category not in use
    [ ! $(grep -f $IN_USE_TMP <<< $CATEGORY ) ] && continue

    REPO="$DIR/$IN"
    LOCAL="$HOME/$IN"

    # directories
    [ -d "$LOCAL" ] && {
      copy-dir $LOCAL $REPO
      continue
    }

    # files
    [ -f "$LOCAL" ] && {
      copy-file $LOCAL $REPO
      continue
    }

    # commands
    CMD=$(echo "$IN" | cut -d " " -f1)
    REST=$(echo "$IN" | cut -d" " -f2-)
    case $CMD in
      create)
        create-dir "$DIR/$REST";;
      clean)
        clean-copy-dir "$HOME/$REST" "$DIR/$REST";;
      run)
        run-command $IN;;
      *)
        echo "skipped:      $IN"
    esac
  done
}

cat $MAPPINGS |
  grep -v "^#" |
  grep -v "^\s*$" |
  get-files

exit 0
