#! /bin/bash

CD=~/.config/conky # ConfigDir

fkill conky
conky -c $CD/conky.conf # &&

conky -c $CD/cmus.conf
# fix current track: ${font Bitstream Vera Sans:size=10}$color2$alignr${execi 5 ~/.tmux/cmus-current-track}

