#! /bin/bash

if [[ $1 = "--help" ]] || [[ $1 = "help" ]]; then
  echo "$ tsp-active"
  echo "If tsp has active jobs, output the nr"
  exit
fi

ACTIVE_JOBS=$(tsp | awk '{ print $2 }' | sed "/State/d" | sed "/finished/d" | wc -l)

if [[ $ACTIVE_JOBS -eq 0 ]]; then
  echo "-"
else
  echo $ACTIVE_JOBS
fi

