#!/bin/bash

draw() {
  kitten icat --stdin no --transfer-mode memory --place "${w}x${h}@${x}x${y}" "$1" </dev/null >/dev/tty
  exit 1
}

file="$1"
extension="${file##*.}"
w="$2"
h="$3"
x="$4"
y="$5"

case "$(file -Lb --mime-type "$file")" in 
  image/*)
    draw "$file"
    ;;
  video/*)
    # vidthumb is from here:
    # https://raw.githubusercontent.com/duganchen/kitty-pistol-previewer/main/vidthumb
    draw "$(vidthumb "$file")"
    ;;
  application/octet-stream)
    case "$extension" in
      cr3|CR3)
        CACHE="$HOME/.cache/lf/thumbnail.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | awk '{print $1}')"
	    [ ! -f "${CACHE}.jpg" ] && \
          exiftool -b -PreviewImage "$file" >"${CACHE}.jpg"
	    draw "${CACHE}.jpg"
        ;;
      *)
        echo "unknown application/octet-stream type (configure in preview-kitty)"
    esac
    ;;
  *)
    echo "unknown mime type (configure in preview-kitty)"
esac

pistol "$file"
