#! /bin/bash

if [[ $1 = "--help" ]] || [[ $1 = "help" ]]; then
  echo "$ bluetooth"
  echo "Print name of currently connected bluetooth device"
  exit
fi

if [[ $(btstatus) = "" ]]; then
  exit 1
else
btstatus | cut -d "-" -f 2- | awk '{ print "  "$1" " }'
fi

