#! /bin/bash

# Source: https://askubuntu.com/q/274349

if [[ $1 = "--help" ]] || [[ $1 = "help" ]]; then
  echo "$ cpu-usage"
  echo "Print current cpu usage percentage"
  exit
fi

top -b -n1 | grep "Cpu(s)" | awk '{printf( "%d%%", $2 + $4 )}'

