#! /bin/sh

if [ "$1" = "--help" ] || [ "$1" = "help" ]; then
  echo "$ diskspace"
  echo "Get free diskspace for the /home partition"
  exit
fi

DISKSPACE=$(df -h | fgrep /home | awk '{ printf $4 }')

echo " $DISKSPACE"

