#! /bin/sh

if [ "$1" = "--help" ] || [ "$1" = "help" ]; then
  echo "$ i3-status"
  echo ""
  echo ""
  echo "Parameters:"
  echo "  \$1: "
  echo ""
  echo "Example:"
  echo "$ i3-status"
  exit
fi

OUT=$(
  i3-msg -t get_workspaces | sed "s/},{/\n/g" | while read WORKSPACE; do
    NAME=$(echo $WORKSPACE  | cut -d\" -f6 | cut -d: -f2)

    if [ -n "$(echo $WORKSPACE | fgrep '"focused":true')" ]; then
      COLOR="#ffff00" # yellow
    elif [ -n "$(echo $WORKSPACE | fgrep '"urgent":true')" ]; then
      COLOR="#cf004b" # magenta
    else
      COLOR="#005fd7" # blue
    fi

    printf "%%{B$COLOR} $NAME "
  done
)

echo $OUT

