#! /bin/bash

if [[ $1 = "--help" ]] || [[ $1 = "help" ]]; then
  echo "$ load-average"
  echo "Get the current 1min load average"
  exit
fi

[ $(uptime | awk '{ print $9 }' | tr -d ,) = "average:" ] &&
  uptime | awk '{ print $10 }' | tr -d , || # Sometimes in the 10th position
  uptime | awk '{ print $9 }' | tr -d , # Usual

