#! /bin/bash

# Returns boolean whenever mullvad is connected.

OUT=$(timeout 0.1s mullvad status | grep "Tunnel status: Connected") 
if [[ $OUT = "" ]]; then
  echo OFF
else
  #echo -e "\033[0;31mtrue\033[0m"
  #echo "$(tput setaf 1)$(tput setab 7)true$(tput sgr 0)"
  echo ON
fi

