#! /bin/sh

MAIN=6cbedc02-fec7-92c9-0c0a-d0d35034b311
UNI=a540d5aa-850c-4add-90e9-258d42834fb7

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  printf "$ todays-events
Print todays entries in khal.

Flags:
  -r: Rightalign text, conky output
"; exit
fi

command -v khal >/dev/null || { echo "khal is not installed"; exit 1; }

print_list() {
  KHAL_FLAGS="--day-format '' -o --notstarted"
  KHAL_FORMAT="[{start-time}-{end-time}] {title}"

  if [ "$1" = "conky" ]; then
    KHAL_FLAGS="$KHAL_FLAGS -a $MAIN -a $UNI"
    KHAL_FORMAT="{title} [{start-time}-{end-time}]"
  fi

  TMP=$(mktemp)
  echo "khal list Today Today $KHAL_FLAGS -f '$KHAL_FORMAT'" > $TMP

  NOW=$(date +%s)
  sh $TMP | while read -r line; do {
    # once a future events has been found, skip checking
    [ -n "$DONE" ] && {
      echo $line
      continue
    }

    # strip events that are in the past
    END_TIME=$(echo $line | cut -d\[ -f2 | cut -d\- -f2 | cut -d] -f1 | xargs date +%s -d)
    [ "$NOW" -lt "$END_TIME" ] && {
      echo $line
      DONE=1
    }
  }; done
}

if [ "$1" = "-r" ]; then # for conky
  print_list conky |
  grep -v "No events" |
  sed "s/:00//g; s/ /_/g; s/Ü/?/g" |
  xargs printf "%60s\n" |
  tr "_" " " |
  sed "s:?:Ü:g" # Ü takes up 2 chars for %60s
else # for shell
  print_list
fi

exit 0

