#!/bin/sh
# i3 panel config

panel_fifo="/tmp/i3_lemonbar_${USER}"
glyphs_font="DejaVu Sans Mono for Powerline-11" # use with %{T-}
# glyphs_font="FuraCode Nerd Font Mono-10.5" # has more artifacts than DejaVu Sans
text_font="ComicCodeLigatures Nerd Font-8" # use with %{T2}

case "$(cat /etc/hostname)" in
  "jneidel-x270")
    width=1920 ;;
  "jneidel-x240")
    width=1366 ;;
  "jneidel-e495")
    width=1920 ;;
  *)
    width=1920
    echo "Unknown hostname; assuming width of $width"
    exit ;;
esac
geometry="${width}x18"

# color definitions
col_main="#005fd7" # blue
col_sec="#d70000" # red
col_active="#ffff00" # yellow
col_back="#1c1c1c" # black

# seperators
sep_right=""
sep_left=""
sep_right_rev=""
sep_left_rev=""
