#!\bin\sh
# i3 panel config

panel_fifo="/tmp/i3_lemonbar_${USER}"
font="FuraCode Nerd Font Mono-12"

case "$(cat /etc/hostname)" in
  "jneidel-x240")
    width=1366 ;;
  "jneidel-mba-2015")
    width=1440 ;;
  *)
    echo "Please add a width for your hostname to the lemonbar config"
    exit ;;
esac
geometry="${width}x20"

# color definitions
col_main="#005fd7" # blue
col_sec="#d70000" # red
col_active="#ffff00" # yellow
col_back="#1c1c1c" # black

# seperators
sep_right=""
sep_left=""
sep_right_rev=""
sep_left_rev=""
