#! /bin/sh

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  cat << EOF
$ discover
List all devices (ip addresses) on the local network

For example to find your pi's ip
EOF
  exit
fi

command -v nmap >/dev/null || { echo "nmap is not installed"; exit 127; }

ipa() {
  ip a | fgrep "inet " | \
    grep -ve " tun" -e " lo" | head -n1 | \
    awk '{ print $2 }' | cut -d"/" -f1
}
IP=`ipa || echo "localhost"`

nmap -sP "$IP/24" | grep -v "Host is up"
