#! /bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
STATUS_FILE="$DIR/mpd-server-status"

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  printf "$ is-mpd-server <++>
<++>

Parameters:
  \$1: <++>
  [\$1]: <++>

Example:
  $ is-mpd-server <++>
"
  exit
fi

if [ ! -e "$STATUS_FILE" ]; then
  echo "sever status file does not exist at $STATUS_FILE"
  exit 1
fi

if [ "$(cat $STATUS_FILE)" -gt 0 ]; then
  true
else
  false
fi

