#! /bin/sh

DIR=`dirname $0`
STATUS_FILE="$DIR/mpd-server-status"
LOCAL_FILE="$DIR/mpd-local-status"

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  printf "$ is-mpd-server
Whether remote server (0 exit) is active or local one (1 exit)
"
  exit
fi

[ ! -e "$STATUS_FILE" ] && printf '0' >$STATUS_FILE
[ ! -e "$LOCAL_FILE" ] && printf '0' >$LOCAL_FILE

if [ `cat $LOCAL_FILE` -eq 0 ] && [ `cat $STATUS_FILE` -eq 1 ] && ! $DIR/is-mpd-playing-local; then
  true
else
  false
fi
