#! /bin/sh

MUSIC_DIR="$(grep '^music_directory' $HOME/.config/mpd/mpd.conf | awk -F\" '{ print $2 }')"

if [ "$1" = "--help" ] || [ "$1" = "help" ]; then
  echo "$ mpd-cover"
  echo "Open cover of current mpd track in $IMAGE_VIEWER_BIN"
  exit
fi

. ~/scripts/mpd/shared-mpd-variables

command -v ffmpeg >/dev/null || { echo "ffmpeg is not installed"; exit 1; }
command -v sxiv >/dev/null || { echo "sxiv is not installed"; exit 1; }

TMP_FILE=$(mktemp --suffix .jpg)
displayCover() {
  kill $(pgrep sxiv) 2>/dev/null # kill previous instance
  ln -sf $TMP_FILE /tmp/mpd-cover.jpg
  sxiv -f /tmp/mpd-cover.jpg >/dev/null 2>&1 &
}

if [ "$IS_SERVER" -eq 0 ]; then
  command -v mpc-get >/dev/null &&
    MPC_CMD="mpc-get file" ||
    MPC_CMD="mpc status -f %file% | head -n 1"

  SONG_FILE="$MUSIC_DIR/$($MPC_CMD)"

  if ffmpeg -y -i "$SONG_FILE" $TMP_FILE >/dev/null 2>&1; then
    displayCover
  else
    echo "[local] Song does not have a cover"
  fi
else
  if ssh $REMOTE_NAME "sh scripts/get-cover-once"; then
    scp $REMOTE_NAME:/tmp/mpd-cover.jpg $TMP_FILE >/dev/null
    displayCover
  else
    echo "[server] Song does not have a cover"
  fi
fi
