#! /bin/bash

# todo: handle mpd error: No route to host
#  and use localhost instead

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
IP=$(cat "$DIR/current-mpd-ip")

PORT=5555

if [[ $1 = "--help" ]] || [[ $1 = "help" ]]; then
  echo "$ ncmpcpps"
  echo "Connect ncmpcpp to mpd running on this devices ip address"
  echo ""
  echo "Connection params:"
  echo "  -h $IP"
  echo "  -p $PORT"
  exit
fi

# timeout 1.2 mpc -h "$IP" -p "$PORT" status > /dev/null 2> /dev/null

# [ $(echo $?) -eq 0 ] && \
#   ncmpcpp -h "$IP" -p "$PORT" 2> /dev/null || \
  ncmpcpp -p "$PORT" 2> /dev/null # try local if pi timedout

