#! /bin/sh

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  cat << EOF
$ pauseaftersong [COUNT]
Pause mpd after the next player interaction (next, pause/play)

Args:
  COUNT: amount of soungs to still play, default: 1

References:
  - if you want to stop pause after a given time has passed use: sleeptimer
  - see mpd player events to see what counts as interactions

Examples:
  pauseaftersong 3
  #=> pause after finishing current song and the two ones after
EOF
  exit
fi

command -v mpcc >/dev/null || { echo "mpcc is not in PATH"; exit 127; }
command -v control-mpd >/dev/null || { echo "control-mpd is not in PATH"; exit 127; }

run() {
  mpcc idle player && control-mpd pause
}
runTimes() {
  cmd="mpcc idle player"
  for n in $(seq $1); do # if invalid count given, exec once (default)
    [ "$n" -gt 1 ] &&
      cmd="$cmd; mpcc idle player"
  done
  cmd="$cmd; control-mpd pause"
  sh -c "$cmd"
}

if [ -n "$1" ]; then
  runTimes $1 >/dev/null &
else
  run >/dev/null &
fi
clear
