#! /bin/bash

source ~/scripts/mpd/shared-mpd-variables
STATUS_FILE="$DIR/mpd-server-status"

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  printf "$ ping-mpd-server
Ping the mpd server and write its status to a file.
To be run regularly run in the background (cron).

Status to: $STATUS_FILE
"; exit
fi

if timeout 1 mpc -h $IP -p $PORT "status" 2> /dev/null >/dev/null; then
  echo "1" > $STATUS_FILE
  true
else
  echo "0" > $STATUS_FILE
  false
fi

