#! /bin/sh

# Receive the cover from send-cover

REMOTE_NAME=pi
REMOTE_COVER_LOCATION=/tmp/mpd-cover.jpg
REMOTE_PIPE=~/tmp/mpd-pipe
COVER_LOCATION=~/tmp/cover.jpg
TMP_LOCATION=/tmp/cover.jpg

if ! ssh $REMOTE_NAME '[ -e "$HOME/tmp/mpd-pipe" ] || exit 1'; then
  printf "Remote pipe does not exist.\nIs 'send-cover' running on the server?\n"
  exit 1
fi

echo "Writing cover to: $TMP_LOCATION"

startConky() {
  conky -c ~/.config/conky/mpd.conf 2> /dev/null
}
getConkyPid() {
  ps | grep " conky" | cut -dp  -f1 >> ~/tmp/conky_log
  ps | grep " conky" | cut -dp  -f1 | sed -e 's/^[[:space:]]*//' | sed -e 's/[[:space:]]*$//'
}
killConky() {
  kill $(getConkyPid) > /dev/null 2> /dev/null
}
startConky

while true # kill conky after 3min of not playing anything
  do {
    [ ! "$(mpcc status | grep "^\[" | cut -d] -f1 | cut -d\[ -f2)" = "playing" ] && {
      killConky
    }
    sleep 3m
  }
done &

while true
  do ssh $REMOTE_NAME "cat $REMOTE_PIPE" | {
    [ -z "$(getConkyPid)" ] && startConky # stark conky if killed for not playing for 3min

    scp $REMOTE_NAME:$REMOTE_COVER_LOCATION $TMP_LOCATION

    cp $TMP_LOCATION $COVER_LOCATION
  }
done

# todo: dynamic ssh adress
# fix: not killable with ^c
  #test $? -gt 128 && break
  # https://unix.stackexchange.com/questions/42287/terminating-an-infinite-loop
