#! /bin/sh

# DIR=`dirname $0`
DIR=~/scripts/mpd

LOCAL_IP=0.0.0.0
LOCAL_PORT=5555

REMOTE_IP=192.168.178.69
REMOTE_PORT=6600

if "$DIR/is-mpd-server" && ! "$DIR/is-mpd-playing-local"; then
  IS_SERVER=1
  CONNECT="-h $REMOTE_IP -p $REMOTE_PORT"
else
  IS_SERVER=0
  CONNECT="-h $LOCAL_IP -p $LOCAL_PORT"
fi

REMOTE_NAME=home
REMOTE_DIR="/root/media/music"
LOCAL_DIR="$ORG_MEDIA/music"

command -v mpc >/dev/null || { echo "mpc is not installed"; exit 1; }
