#! /bin/sh

# DIR=`dirname $0`
DIR=~/scripts/mpd

LOCAL_IP=0.0.0.0
LOCAL_PORT=5555

IS_SERVER=0
CONNECT="-h $LOCAL_IP -p $LOCAL_PORT"

REMOTE_NAME=home
REMOTE_DIR="/root/media/music"
LOCAL_DIR="$ORG_MEDIA/music"

command -v mpc >/dev/null || { echo "mpc is not installed"; exit 1; }
