#! /bin/sh

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  cat << EOF
$ sleeptimer TIME
Set a sleeptimer to stop mpv/mpd after

Parameters:
  \$1: timer given to sleep

Example:
  $ sleeptimer 20m
EOF
  exit
fi

TIMER="$1"

hash mpvctl control-media || exit 127

pause() {
  if mpvctl get name >/dev/null; then
    mpvctl key Q # quit, save state
  else
    control-media pause
  fi
}

sleep "$TIMER" && pause
