#! /bin/bash

DIR="$(dirname $0)"

OP=$DIR/oneplus-ip
S6=$DIR/s6-ip
S21=$DIR/s21-ip
PORT=2121
SSHPASS=1234

NET_NAME=`wifiname`
if [ "$NET_NAME" = "Not connected" ]; then
  echo "Not connected to any network"
  exit 1
  # test with ethernet connection
fi
NET_NAME=`echo $NET_NAME | sed 's| |_|g'`

IP_FILE=$S21
[ "$1" = "s6" ] && IP_FILE=$S6
[ "$1" = "op" ] && IP_FILE=$OP
touch $IP_FILE

IP=`grep $NET_NAME <$IP_FILE | cut -d\  -f2`

if [ -z "$IP" ]; then
  echo "$NET_NAME is not configured in $IP_FILE"
  printf "edit file? (Y/n)"
  read ans
  if [ "$ans" != "n" ]; then
    echo "$NET_NAME 192.168.<++>.<++>" >>$IP_FILE
    nvim $IP_FILE
    IP=`grep $NET_NAME <$IP_FILE | cut -d\  -f2`
  else
    exit 1
  fi
fi
