#! /bin/bash

# Todo: ip based on network name
# time eater: 192.168.178.91
# jneidel-hotspot: 192.168.43.126

DIR="$(dirname $0)"

ONEPLUS=$DIR/oneplus-ip
S6=$DIR/s6-ip
PORT=2121

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  printf "$ ftpp
Connect to phone via sftp
"; exit
fi

command -v sftp >/dev/null || { echo "sftp is not installed"; exit 1; }

IP_FILE=$ONEPLUS
[ "$1" = "s6" ] && IP_FILE=$S6

IP=$(< $IP_FILE)
sftp -P $PORT -i $HOME/.ssh/private $IP
