#! /bin/sh

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ] || [ ! -e "$1" ]; then
  printf "$ format-lsf-ics LSF_Plan.ics
Cleanup/format lecture ics file from lsf.htw-berlin.de

1. Shorten SUMMARY
  from: B12Netzwer - B12.1 Netzwerke (SL) (Seide)
  to:   B12Netzwer (Seide)
2. Move LOCATION tag into the DESCRIPTION

Parameters:
  \$1: LSF-Plan.ics file to format

Example:
  $ format-lsf-ics ./LSF_Plan.ics
"
  exit
fi

# command -v <++> >/dev/null || { echo "<++> is not installed"; exit 1; }

FILE="$1"

# cleanup summary
cat "$FILE" | fgrep "SUMMARY" | while read LINE; do {
  TITLE="$(echo $LINE | cut -d: -f2 | cut -d- -f1 | sed 's|[[:space:]]$||')";

  UEBUNG="";
  if echo $LINE | fgrep "(Ü)" >/dev/null; then
    UEBUNG="(Ü) ";
  fi;

  PROF=$(echo $LINE | rev | cut -d\  -f1 | rev);

  if [ -z "$TITLE" ] || [ -z "$PROF" ] || [ -z "$(echo $LINE | grep '-')" ]; then
    echo "Invalid TITLE or PROF."
    echo "Has the file already been formatted?"
    break
  fi

  sed -i "s/$LINE/SUMMARY:$TITLE $UEBUNG$PROF/g" $FILE
} done

# remove unneeded html tags in description
# sed -i "s|<p><strong> </strong></p>||" "$FILE"

# move location to description
if cat "$FILE" | grep "LOCATION" >/dev/null; then
  sed -i "/DESCRIPTION:/d" "$FILE"
  sed -i "s/LOCATION/DESCRIPTION/" "$FILE"
fi
