#! /bin/sh

UNI_DIR=$HOME/projects/uni

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ] || [ -z "$1" ]; then
  cat << EOF
$ newmodule NAME
Setup a new module directory in $UNI_DIR

Parameters:
  \$1: name of the module
EOF
  exit
fi

MODULE_NAME="$1"
MODULE_DIR="$UNI_DIR/$MODULE_NAME"

mkdir -p "$MODULE_DIR/folien/done" "$MODULE_DIR/books" "$MODULE_DIR/ueb" "$MODULE_DIR/abgaben"
printf "# orga\n\n\n" >> "$MODULE_DIR/orga.md"
printf "# resources\n\n\n" >> "$MODULE_DIR/resources.md"
printf "# glossary\n\n\n" >> "$MODULE_DIR/glossary.md"

echo "Created module at $MODULE_DIR"
