#! /bin/bash

DIR="$HOME/projects/uni"
TODO_FILE_PATTERN="1_todo.md"

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  cat << EOF
$ todo
Print a list of uni todo collected from:
  1. the main todo list
  2. course specific lists
EOF
  exit
fi

list() {
  KW=$(kw)
  ACTIVE_KW=""
  printf "\033[1;34m$KW\033[0m:\n"

  PREV_MODULE=""

  PREV_IFS="$IFS"
  IFS=$'\n'
  for line in $(cat $DIR/1_list.md | grep -ve '^>'); do
    [ "${line:0:1}" = "#" ] && {
      ACTIVE_KW=`echo $line | cut -d\  -f3`
      continue
    }

    [ -z "$ACTIVE_KW" ] && continue
    if [ "$ACTIVE_KW" -ne "$KW" ] || [ "$ACTIVE_KW" = "uni" ] || [ "$ACTIVE_KW" = "aufgaben" ]; then
      continue
    fi

    MODULE=`echo $line | cut -d\  -f2`
    if [ -n "$PREV_MODULE" ] && [ "$PREV_MODULE" != "$MODULE" ]; then
      echo ""
    fi
    PREV_MODULE="$MODULE"

    echo $line
  done
}
list 2>/dev/null
echo ""

IFS="$PREV_IFS"
find "$DIR" -maxdepth 2 -iname "$TODO_FILE_PATTERN" | while read -r file; do
  TODOS=`cat $file | sed '1d;2d' | grep -ve "^\s*$" -e "^#" -e "^>" | sed 's|^[- ]*|- |'`
  if [ -n "$TODOS" ]; then
    cat << EOF
$(printf "\033[1;34m$(basename $(dirname $file))\033[0m:\n" )
$TODOS

EOF
  fi
done
