#! /bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# blank to run normally, anything to dryrun
DRY=

source $DIR/copy-configs

if [ "$1" = "--help" ] || [ "$1" = "help" ]; then
  echo "$ import-configs"
  echo "Copy the local dotfiles to this repo."
  echo "Uses the mapping/commands from $MAPPINGS"
  exit
fi

CATEGORY=""
function get-files {
  IFS=$'\n'
  for IN in $(cat /dev/stdin); do
    # categories
    [ ${IN:0:1} = "[" ] && {
      IN=${IN:1:-1} # strip []
      CATEGORY=$IN
      continue
    }

    # category not in use
    [ ! $(grep -f $IN_USE_TMP <<< $CATEGORY ) ] && continue

    REPO="$DIR/$IN"
    LOCAL="$HOME/$IN"

    # directories
    [ -d "$LOCAL" ] && {
      copy-dir $LOCAL $REPO
      continue
    }

    # files
    [ -f "$LOCAL" ] && {
      copy-file $LOCAL $REPO
      continue
    }

    # commands
    CMD=$(echo "$IN" | cut -d " " -f1)
    REST=$(echo "$IN" | cut -d" " -f2-)
    case $CMD in
      create)
        create-dir "$DIR/$REST";;
      clean)
        clean-copy-dir "$HOME/$REST" "$DIR/$REST";;
      *)
        echo "skipped:      $IN"
    esac
  done
}

cat $MAPPINGS |
  grep -v "^#" |
  grep -v "^\s*$" |
  get-files

exit 0

