#! /bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# blank to run normally, anything to dryrun
DRY=

source $DIR/copy-configs

if [ "$1" = "--help" ] || [ "$1" = "help" ]; then
  echo "$ install-configs"
  echo "Copy the dotfiles into the local locations"
  echo "Uses the mapping/commands from ./mappings"
  exit
fi

CATEGORY=""
function install-files {
  IFS=$'\n'
  for IN in $(cat /dev/stdin); do
    # categories
    [ ${IN:0:1} = "[" ] && {
      IN=${IN:1:-1} # strip []
      CATEGORY=$IN
      continue
    }

    # category not in use
    [ ! $(grep -f $IN_USE_TMP <<< $CATEGORY ) ] && continue

    LOCAL="$HOME/$IN"
    REPO="$DIR/$IN"

    # directories
    [ -d "$REPO" ] && {
      copy-dir $REPO $LOCAL
      continue
    }

    # files
    [ -f "$REPO" ] && {
      copy-file $REPO $LOCAL
      continue
    }

    # commands
    CMD=$(echo "$IN" | cut -d " " -f1)
    REST=$(echo "$IN" | cut -d" " -f2-)
    case $CMD in
      create)
        create-dir "$HOME/$REST";;
      clean)
        copy-dir "$DIR/$REST" "$HOME/$REST";; # don't clean local
      *)
        echo "skipped:      $IN"
    esac
  done
}

cat $MAPPINGS |
  grep -v "^#" |
  grep -v "^\s*$" |
  install-files
