#! /bin/sh

DIR=`dirname $0`
. $DIR/ledger.lib.sh

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ] || [ -z "$2" ]; then
  cat <<EOF
$ fifty-fifty TITLE AMOUNT DATE
Add a 50/50 transaction to the ledger file
Paid from the wallet account

Parameters:
  \$1: title of the transaction
  \$2: amount for the whole
  \$3: $(date_doc_string)

Example:
  $ fifty-fifty "Baumarkt" "18.5+5.6"
  $ fifty-fifty "Baumarkt" "18.5+5.6" 22
  $ fifty-fifty "Baumarkt" "18.5+5.6" t03
EOF
  exit
fi

hash node || exit 127

TITLE="$1"
amount_input="$2"
calculate_split_amounts $amount_input
date_input="$3"
parse_date_input "$date_input"

print() {
  cat <<EOF
$DATE ! $TITLE
  ex                       $AMOUNT_SPLIT_1
  [pot:leben]             -$AMOUNT_SPLIT_1
  person:francis           $AMOUNT_SPLIT_2
  [person:francis]        -$AMOUNT_SPLIT_2
  [owed]                   $AMOUNT_SPLIT_2
  [reserve]               -$AMOUNT_SPLIT_2
  wallet                  -$AMOUNT_TOTAL
  [wallet]                 $AMOUNT_TOTAL

EOF
}

print >>$LEDGER_FILE && echo "Written to $LEDGER_FILE"
