#! /bin/sh

DIR=`dirname $0`
. $DIR/ledger.lib.sh

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ] || [ -z "$1" ]; then
  cat <<EOF
$ gas AMOUNT DATE
Add gas transaction to ledger file
Paid from shared account

Parameters:
  \$1: amount for the whole
  \$2: $(date_doc_string)

Example:
  $ gas 40.59
  $ gas 40.59 21
  $ gas 40.59 t03
EOF
  exit
fi

hash node || exit 127

amount_input="$1"
calculate_split_amounts $amount_input
date_input="$2"
parse_date_input "$date_input"

print() {
  cat <<EOF
$DATE Tanken
  ex:car:gas               $AMOUNT_SPLIT_1
  [pot:leben]             -$AMOUNT_SPLIT_1
  shared                  -$AMOUNT_TOTAL
  [shared]                 $AMOUNT_TOTAL
  bal                      $AMOUNT_SPLIT_2
  [bal]                   -$AMOUNT_SPLIT_2

EOF
}

print >>$LEDGER_FILE && echo "Written to $LEDGER_FILE"
