#! /bin/sh

DIR=`dirname $0`
. $DIR/ledger.lib.sh

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ] || [ -z "$2" ]; then
  cat <<EOF
$ groceries TITLE AMOUNT DATE
Add groceries to ledger file
Paid in cash

Parameters:
  \$1: title of the transaction
  \$2: amount for the whole
  \$3: $(date_doc_string)

Example:
  $ groceries "Edeka" "18.5+5.6"
  $ groceries "Edeka" "18.5+5.6" 02
  $ groceries "Edeka" "18.5+5.6" t02
EOF
  exit
fi

hash node || exit 127

TITLE="$1"
amount_input="$2"
calculate_split_amounts $amount_input "70/30"
date_input="$3"
parse_date_input "$date_input"

print() {
  cat <<EOF
$DATE $TITLE
  ex:food:groceries        $AMOUNT_SPLIT_1
  [pot:leben]             -$AMOUNT_SPLIT_1
  person:francis           $AMOUNT_SPLIT_2
  [person:francis]        -$AMOUNT_SPLIT_2
  [owed]                   $AMOUNT_SPLIT_2
  [reserve]               -$AMOUNT_SPLIT_2
  wallet                  -$AMOUNT_TOTAL
  [wallet]                 $AMOUNT_TOTAL

EOF
}

print >>$LEDGER_FILE && echo "Written to $LEDGER_FILE"
