#! /bin/sh

DIR=`dirname $0`
. $DIR/ledger.lib.sh

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ] || [ -z "$2" ]; then
  cat <<EOF
$ shared TITLE AMOUNT DATE
Add a shared transaction to the ledger file
Paid from the shared account

Parameters:
  \$1: title of the transaction
  \$2: amount for the whole
  \$3: $(date_doc_string)

Example:
  $ shared "Baumarkt" "18.5+5.6"
  $ shared "Baumarkt" "18.5+5.6" 22
  $ shared "Baumarkt" "18.5+5.6" t22
EOF
  exit
fi

hash node || exit 127

TITLE="$1"
amount_input="$2"
calculate_split_amounts $amount_input
date_input="$3"
parse_date_input "$date_input"

print() {
  cat <<EOF
$DATE ! $TITLE
  ex                       $AMOUNT_SPLIT_1
  [pot:leben]             -$AMOUNT_SPLIT_1
  bal                      $AMOUNT_SPLIT_2
  [bal]                   -$AMOUNT_SPLIT_2
  shared                  -$AMOUNT_TOTAL
  [shared]                 $AMOUNT_TOTAL

EOF
}

print >>$LEDGER_FILE && echo "Written to $LEDGER_FILE"
