#! /bin/sh

DURATIONS_FILE="$ORG_AREAS/geld/inbox/durations.txt"
STATE_FILE="$ORG_AREAS/geld/inbox/.inbox-leerung-state"

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  cat <<EOF
$ ustva
Guide me through the UStVA process

Manipulate the timer with the words:
- pause
- resume
EOF
exit
fi

hash tmux pdfextract pdfinfo mime || exit 127

start_time=$(date +%s)

# helpers
print_header() {
  printf "\033[1;32m$1\033[0m\n"
}
print_control() {
  printf "\033[1;34m$1\033[0m"
}
print_running() {
  printf "\033[1;31m$1\033[m"
}
print_paused() {
  printf "\033[1;32m$1\033[m"
}

step=0
actual_step=0
next_step() {
  step=$(($step+1))
  actual_step=$(($actual_step+1)) # not set by state, see skip_step_based_on_state
}
next_step

should_skip_based_on_state() {
  if [ "$step" != "$actual_step" ]; then
    actual_step=$(($actual_step+1))
    return 1
  fi
}

# state management
update_state() {
  current_time=$(date +%s)
  passed_time=$(($current_time-$start_time))
  echo "$step $passed_time" >"$STATE_FILE"
}

get_step_from_state() {
  { cat "$STATE_FILE" 2>/dev/null || echo 1; } | cut -d\  -f1
}
get_duration_from_state() {
  { cat "$STATE_FILE" 2>/dev/null || echo " 0"; } | cut -d\  -f2
}

if [ -f "$STATE_FILE" ]; then
  printf "Existing state found: Step $(get_step_from_state). after $(get_duration_from_state)s.\nDo you want to resume from state? (Y/n): "
  read resume_from_state
  if [ "$resume_from_state" = "n" ] || [ "$resume_from_state" = "N" ]; then
    printf "Please confirm to discard the existing state (Y/n): "
    read discard_state
    if [ "$discard_state" != "n" ] && [ "$discard_state" != "N" ]; then
      rm "$STATE_FILE"
    fi
  fi
  step=$(get_step_from_state)
  current_time=$(date +%s)
  start_time=$(($current_time-$(get_duration_from_state)))
fi

# time keeping
calc_total_time() {
  end_time=$(date +%s)
  secs_passed=$(($end_time-$start_time))
  mins_passed=$(($secs_passed/60))
  mins_passed_leftover_sec=$(($secs_passed%60))

  print_control "Time passed: ${mins_passed}m ${mins_passed_leftover_sec}s\n"

  echo "$(date +%b%d): ${mins_passed}m" >>"$DURATIONS_FILE"
  echo "Stats were added to: $DURATIONS_FILE"
  rm "$STATE_FILE"
}
is_paused=0
passed_before_pause=0
pause_timer() {
  if [ "$is_paused" -eq 1 ]; then
    print_paused "Timer is already paused\n"
  else
    is_paused=1
    pause_time=$(date +%s)
    passed_before_pause=$(($pause_time-$start_time))
    print_paused "[Timer paused]\nContinue the review process with 'resume'\n"
    update_state
  fi
}
resume_timer() {
  if [ "$is_paused" -eq 0 ]; then
    print_running "Timer is not paused\n"
  else
    is_paused=0
    resume_time=$(date +%s)
    start_time=$(($resume_time-$passed_before_pause))
    print_running "[Timer resumed]\n"
  fi
}

prompt_continue() {
  update_state

  print_control "Continue? "
  read ans
  case $ans in
    pause)
      pause_timer
      prompt_continue;;
    resume)
      resume_timer
      prompt_continue;;
    *)
      if [ "$is_paused" -eq 1 ]; then
        print_control "\nCan't continue with the timer paused\n"
        prompt_continue
      else
        next_step
        printf "\n"
      fi
      ;;
  esac
}

split_below() {
  local step_name="$1"
  local cmd="$2"

  tmux split-window -v -l 70%
  tmux send-keys "clear && figlet $step_name" "Enter" "$cmd" "Enter"
}

# ustva specific logic
case "$(date +%m)" in
  01|02|03) q=4; month_1_in_question=10; month_2_in_question=11; month_3_in_question=12;;
  04|05|06) q=1; month_1_in_question=01; month_2_in_question=02; month_3_in_question=03;;
  07|08|09) q=2; month_1_in_question=04; month_2_in_question=05; month_3_in_question=06;;
  10|11|12) q=3; month_1_in_question=07; month_2_in_question=08; month_3_in_question=09;;
esac
year_in_question=$(date +%Y)
[ "$q" -eq 4 ] && year_in_question=$(date +%Y -d "last year")
echo "Doing the UStVA for Q$q of $year_in_question ($(date -d "2000-$month_1_in_question-01" +%b)-$(date -d "2000-$month_3_in_question-01" +%b))"

process_kontoauszug() {
  month="$1"
  month_long=$(date -d "2000-$month-01" +%B)
  file=`find $ORG_AREAS/geld/inbox -name "1334251000_${year_in_question}_Nr.*_Kontoauszug_vom_$year_in_question.*.${month}_*.pdf" | head -n1`
  if [ -z "$file" ]; then
    echo "Kontoauszug for $month not found, skipping."
  else
    mime open "$file" &
    pdfextract "$file" "$(($(pdfinfo "$file" | awk '/^Pages:/ {print $2}')-1))" "$ORG/.paperless_import/Kontoführungsgebühren GbR $month_long.pdf" >/dev/null && echo "Successfully imported Kontoführungsgebühren into paperless"
    echo "TODO: Archive Kontoauszug"
  fi
  prompt_continue
}

# parts of the process
add_gls_transactions_to_ledger() {
  should_skip_based_on_state || return
  print_header "$step. Add GLS transactions to ledger"
  cat <<EOF
outcome:
  - Paperless inbox is empty

EOF

  process_kontoauszug "$month_1_in_question"
  process_kontoauszug "$month_2_in_question"
  process_kontoauszug "$month_3_in_question"
}

process_paperless_inbox() {
  should_skip_based_on_state || return
  print_header "$step. Tag and import everything in paperless"
  cat <<EOF
outcome:
  - Paperless inbox is empty

EOF
  $BROWSER https://paperless.neidel.xyz/view/1 >/dev/null 2>&1 &
  prompt_continue
}
# https://paperless.neidel.xyz/documents?tags__id__all=12&sort=created&reverse=1&page=1

check_invoiceninja() {
  should_skip_based_on_state || return
  print_header "$step. Add any missing invoices from InvoiceNinja"
  cat <<EOF
outcome:
  - all invoices are created
  - all invoices are in ledger

EOF
  $BROWSER https://invoice.neidel.xyz/invoices >/dev/null 2>&1 &
  prompt_continue
}

submit_in_elster() {
  should_skip_based_on_state || return
  print_header "$step. Submit results to Elster"
  cat <<EOF
outcome:
  - UStVA was submitted

EOF
  $BROWSER https://www.elster.de/eportal/formulare-leistungen/alleformulare/ustvaeru >/dev/null 2>&1 &
  echo "Fill 'Steuerpflichtige Umsätze (12)' with netto income"
  echo "Fill 'Abziehbare Vorsteuerbeträge (37)' with vat expenses"
  prompt_continue
}
download_elster_formular() {
  should_skip_based_on_state || return
  print_header "$step. Download submitted Formular in Elster"
  cat <<EOF
outcome:
  - Formular was downloaded

EOF
  $BROWSER "https://www.elster.de/eportal/meineformulare#meineFormulare-uebermittelt" >/dev/null 2>&1 &
  echo "Formular -> Herunterladen"
  prompt_continue

  echo "TODO: move into correct place"
  prompt_continue
}

# run steps in order
add_gls_transactions_to_ledger
process_paperless_inbox
check_invoiceninja
submit_in_elster
download_elster_formular

echo "Congrats! You're done"
calc_total_time
