#! /bin/sh

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  cat << EOF
$ mpv MPV_ARGS
Preconfigured mpv launch:
- using ICP socket (remote control)
- delay if connected to bluetooth speaker
- adjust speed hearing uni lectures
EOF
  exit
fi

command -v /bin/mpv >/dev/null || { echo "mpv is not installed"; exit 1; }
command -v manage-mpv-sockets >/dev/null || { echo "manage-mpv-sockets script is not in PATH"; exit 127; }

SOCKET=$(manage-mpv-sockets open)
ICP_SOCK="--input-ipc-server=$SOCKET"

OPTIONS=""
if echo "$@" | grep -e "projects/uni" -e "mediathek.htw-berlin.de" >/dev/null; then
  OPTIONS="--speed=1.40"
fi

if btdevice >/dev/null; then
  echo "Adapting for bluetooth delay (-120ms)"
  /bin/mpv $ICP_SOCK $OPTIONS --audio-delay='-.120' "$@"
else
  echo "Adapting for speaker delay (+100ms)"
  /bin/mpv $ICP_SOCK $OPTIONS --audio-delay='+.100' "$@"
fi
# jbl connect ideal: -.380
