#! /bin/sh

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ] || [ -z "$1" ]; then
  cat << EOF
$ mpvctl CMD
Control mpv through the IPC socket at $SOCKET

Commands:
  play|toggle|pause: toggle playback
  seek:              seek by specified amount
  get:               get info by property name
  keypress:          send a keypress

Example:
  $ mpvctl toggle
EOF
  exit
fi

command -v mpv >/dev/null || { echo "mpv is not installed"; exit 127; }
command -v socat >/dev/null || { echo "socat is not installed"; exit 127; }
command -v manage-mpv-sockets >/dev/null || { echo "manage-mpv-sockets script is not in PATH"; exit 127; }

if SOCKET=$(manage-mpv-sockets get_playing); then
  continue
else
  echo "mpv not playing on any socket"
  exit 10
fi

send_cmd() {
  # see man at: list of input commands
  res=$(echo "{\"command\": $1}" | socat - $SOCKET)
  if echo $res | grep -F '"error":"success"' >/dev/null; then
    echo $res | jq .data
  else
    if [ -n "$res" ]; then
      echo $res 1>&2
    fi
    exit 1
  fi
}
send_keypress() {
  echo "sending keypress: $1"
  send_cmd "[\"keypress\", \"$1\"]" >/dev/null
}
send_get() {
  # see: man "Properties" for descriptions
  send_cmd "[\"get_property\", \"$1\"]"
  # pass 'property-list' for all properties
  #  https://github.com/mpv-player/mpv/issues/7562
}

notify() {
  notify-send -i $1 -u normal -t 4000 "$2" "$(send_get media-title | cut -d\" -f2)"
}
next() {
  if [ "$(send_get chapters)" -gt 0 ]; then # has chapters
    send_cmd "[\"add\", \"chapter\", \"1\"]"
  elif [ "$(send_get playlist-count)" -gt 0 ]; then # has playlist
    send_cmd "[\"playlist-next\", \"force\" ]"
  else # just regular file
    send_cmd "[\"seek\", \"60\"]"
  fi
}
prev() {
  if [ "$(send_get chapters)" -gt 0 ]; then # has chapters
    send_cmd "[\"add\", \"chapter\", \"-1\"]"
  elif [ "$(send_get playlist-count)" -gt 0 ]; then # has playlist
    send_cmd "[\"playlist-prev\", \"weak\" ]"
  else # just regular file
    send_cmd "[\"seek\", \"-60\"]"
  fi
}

case "$1" in
  play|toggle|pause)
    send_keypress space >/dev/null

    if [ `send_get pause 2>/dev/null` = "false" ]; then
      notify player_play "Play"
    else
      notify player_pause "Pause"
    fi;;
  next)
    next
    notify player_end "Next";;
  prev)
    prev
    notify player_start "Previous";;
  get) send_get "$2";;
  key|keypress) send_keypress "$2";;
esac
