#! /bin/sh
# Todo: add option to pass stuff via args

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  printf "$ bangs
Portable custom duckduckgo bangs (tpb, lg, etc.)
Open in \$BROWSER ($BROWSER).
Bangs not in the list will be referred to duckduckgo.
Should be run via keyboard shortcut.

Commands:
  list: list all available bangs
  BANG QUERY: open the given query for the given bang

Examples:
  $ bangs
  $ bangs list
  $ bangs yt 'rofi showcase'
"; exit
fi

MAIN_BROWSER=nyxt
SECONDARY_BROWSER=brave

hash rofi $MAIN_BROWSER $SECONDARY_BROWSER node || exit 127

DEFAULT_BANG="-" # ddg

bangList() {
  cat $(dirname $0)/banglist
}

if [ "$1" = "list" ]; then
  bangList
  exit 0
fi

prompt() {
  rofi -dmenu -l 0 -theme-str 'window {width: 300px;}' -p \!
}

urlEncode() {
  node -e "console.log( encodeURIComponent( process.argv[1] ) )" "$1"
}

if [ -z "$2" ]; then
  res="$(prompt)"
  [ -z "$res" ] && exit 1
  bang="${res%% *}"
  rawquery="${res#* }"
  [ "$query" = "$bang" ] && bang=$DEFAULT_BANG
else
  bang=$1
  rawquery="$2"
fi

query=`urlEncode "$rawquery"`
case "$bang" in
  y)
    ~/scripts/yt $rawquery
    exit;;
  yts)
    ~/scripts/yts $rawquery
    exit;;
  yt|j)
    $SECONDARY_BROWSER "https://duckduckgo.com/?q=!$bang%20$query" >/dev/null 2>&1 &
    exit;;
esac

if bangList | grep -m 1 "^$bang " >/dev/null; then
  bangList | grep -m 1 "^$bang " | cut -d\  -f2- | sed "s|\%s|$query|" | xargs -r -0 $MAIN_BROWSER >/dev/null 2>&1 &
else
  if [ "$bang" = "$DEFAULT_BANG" ] && [ "$DEFAULT_BANG" = "-" ]; then
    $MAIN_BROWSER "https://duckduckgo.com/?q=$query" >/dev/null 2>&1 &
  else
    $MAIN_BROWSER "https://duckduckgo.com/?q=!$bang%20$query" >/dev/null 2>&1 &
  fi
fi
