#! /bin/sh
# Todo: add option to pass stuff via args

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  printf "$ bangs
Portable custom duckduckgo bangs (tpb, lg, etc.)
Open in \$BROWSER ($BROWSER).
Bangs not in the list will be referred to duckduckgo.
Should be run via keyboard shortcut.

Commands:
  list: list all available bangs
"; exit
fi

command -v rofi >/dev/null || { echo "rofi is not installed"; exit 1; }
command -v $BROWSER >/dev/null || { echo "$BROWSER is not installed"; exit 1; }
command -v node >/dev/null || { echo "node is not installed"; exit 1; }

bangList() {
  cat $(dirname $0)/banglist
}

if [ "$1" = "list" ]; then
  bangList
  exit 0
fi

prompt() {
  rofi -dmenu -lines 0 -width 25 -p \!
}

urlEncode() {
  node -e "console.log( encodeURIComponent( process.argv[1] ) )" "$1"
}

res="$(prompt)"
[ -z "$res" ] && exit 1

bang="${res%% *}"
query="${res#* }"
[ "$query" = "$bang" ] && bang="mw" # no bang passed -> merriam webster

case "$bang" in
  y)
  ~/scripts/yt $query
  exit;;
  yts)
  ~/scripts/yts $query
  exit;;
  dot)
  $BROWSER "https://jneidel.com/dot/$query"
  exit;;
esac

query=`urlEncode "$query"`

if bangList | grep -m 1 "^$bang " >/dev/null; then
  bangList | grep -m 1 "^$bang " | cut -d\  -f2- | sed "s|\%s|$query|" | xargs -r -0 $BROWSER
else
  $BROWSER "https://duckduckgo.com/?q=!$bang%20$query"
fi
