#! /bin/sh

BOOKMARK_FILE="$HOME/scripts/personal/bookmark data/insertions"

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  cat <<EOF
$ insert-bookmark
Insert an entry from bookmark file

Takes a file with entries like this:
Credit card N26 535512345678
IBAN N26 0123456789
Social security 12341234

The last space separated value on a line will be inserted.
Everything else is description for easy matching with rofi.
EOF
  exit
fi

hash rofi xdotool || exit 127

if [ ! -f "$BOOKMARK_FILE" ]; then
  echo "Bookmark file '$BOOKMARK_FILE' does not exist"
  exit 1
fi

SELECTION=`cat "$BOOKMARK_FILE" | rofi -dmenu -i -lines 15 -eh 1 -p insert 2>/dev/null | rev | cut -d\  -f1 | rev`
xdotool type $SELECTION
