#! /bin/sh

BOOKMARK_FILE=$HOME/scripts/personal/webpages
FATURDAY_EXCLUDE_FILE=$HOME/scripts/personal/webpages-faturday-exclude

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  cat <<EOF
$ open-bookmark
Open a bookmark in $BROWSER
EOF
  exit
fi

MAIN_BROWSER=$BROWSER
SECONDARY_BROWSER=firefox

hash rofi $MAIN_BROWSER $SECONDARY_BROWSER node || exit 127


if [ ! -f "$BOOKMARK_FILE" ]; then
  echo "Bookmark file '$BOOKMARK_FILE' does not exist"
  exit 1
fi

bookmarks() {
  cat $BOOKMARK_FILE | sed "s/12345678/$(shuf -i 1-9999999 -n 1)/"
}

SELECTION=`bookmarks | rofi -dmenu -i -lines 15 -eh 1 -p open -auto-select 2>/dev/null | rev | cut -d\  -f1 | rev`

if [ -n "$SELECTION" ]; then
  if echo $SELECTION | grep -e jellyfin -e flood -e flickfocus -e jc141 -e 178.69 >/dev/null; then
    $SECONDARY_BROWSER $SELECTION >/dev/null 2>&1
  else
    $MAIN_BROWSER $SELECTION >/dev/null 2>&1
  fi
fi
