#! /bin/sh

BOOKMARK_FILE=$HOME/scripts/personal/webpages

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  cat <<EOF
$ open-bookmark
Open a bookmark in $BROWSER
EOF
  exit
fi

command -v rofi >/dev/null || { echo "rofi is not installed" 1>&2; exit 127; }
command -v $BROWSER >/dev/null || { echo "$BROWSER is not installed or var \$BROWSER is not set" 1>&2; exit 127; }

if [ ! -f "$BOOKMARK_FILE" ]; then
  echo "Bookmark file '$BOOKMARK_FILE' does not exist"
  exit 1
fi

SELECTION=`cat $BOOKMARK_FILE | rofi -dmenu -i -lines 15 -eh 1 -p insert -auto-select 2>/dev/null | rev | cut -d\  -f1 | rev`
[ -n "$SELECTION" ] && $BROWSER $SELECTION >/dev/null 2>&1
