#! /bin/sh

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  printf "$ power-menu
Issue a power command
"; exit
fi

command -v dmenu >/dev/null || { echo "dmenu is not installed"; exit 1; }

case "$(printf "suspend\nreboot/restart\nshutdown/power off\nlock" | rofi -dmenu -l 4 -theme-str 'window {width: 300px;}' -p power)" in
  "reboot/restart") reboot;;
  suspend) systemctl suspend;;
  "shutdown/power off") poweroff;;
  lock) ~/scripts/i3/lock/lock && suspend;;
esac

