#! /bin/sh

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  printf "$ power-menu
Issue a power command
"; exit
fi

command -v dmenu >/dev/null || { echo "dmenu is not installed"; exit 1; }

case "$(printf "suspend\nreboot/restart\nshutdown/power off\nlock\nhibernate" | rofi -dmenu -l 5 -theme-str 'window {width: 300px;}' -p power)" in
  "reboot/restart") reboot;;
  suspend) systemctl suspend;;
  "shutdown/power off") poweroff;;
  lock) ~/scripts/i3/lock/lock && suspend;;
  hiberate)
    dbus-send --system --print-reply --dest=org.freedesktop.login1 /org/freedesktop/login1 "org.freedesktop.login1.Manager.Hibernate" boolean:true
    # only works in a functional shell: systemctl hiberate
    # needs 'resume' kernel param to be set via grub
    # see: https://wiki.archlinux.org/title/Power_management/Suspend_and_hibernate#Required_kernel_parameters
    ;;
esac

