#! /bin/sh

if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
  cat <<EOF
$ sell-option [-t TICKER] [-e EXPIRY] [-s STRIKE] [-d DELTA] [-i IV] [-u PRICE_UNDERLYING] [-p PREMIUM] [-q QUANTITY]
Create a trading journal entry for the sale of an option.
An org-mode template.

Any flag not passed will be prompted for.

Flags:
  -t: ticker symbol
  -e: expiry, format: Dec20, Jan03'25
  -s: strike and option type, format: 23C, 55P
  -d: delta, format: .3, 0.30, 30
  -u: price of the underyling
  -q: quantity
  -p: premium of the option
  -i, -v: IV, format: .3, 0.302, 30.2

Examples:
  $ sell-option
  $ sell-option -u 23 -s 26C
  $ sell-option -t DAL -e Dec20 -s 112P -d .16 -i 41.4 -u 116.2 -q 2 -p .80
EOF
  exit
fi

hash emacs gum earn || exit 127

while getopts ":t:e:s:d:i:v:p:u:q:" opt; do
  case $opt in
    t) TICKER="$OPTARG" ;;
    e) expiry_input="$OPTARG" ;;
    s) strike_and_type="$OPTARG" ;;
    d) DELTA="$OPTARG" ;;
    i|v) IV="$OPTARG" ;;
    u) UNDERLYING_PRICE="$OPTARG" ;;
    q) QUANTITY="$OPTARG" ;;
    p) PREMIUM="$OPTARG" ;;
    \?) echo "Invalid flag passed: -$OPTARG" >&2; exit 1 ;;
    :) echo "Flag -$OPTARG requires an argument." >&2; exit 1 ;;
  esac
done

if [ -z "$strike_and_type" ]; then
  printf "Option strike and type: "
  read strike_and_type
  [ -z "$strike_and_type" ] && echo Empty strike and option type && exit 1
fi
STRIKE="$(echo $strike_and_type | rev | cut -c2- | rev)"
OPTION_TYPE="$(echo $strike_and_type | rev | cut -c1 | tr a-z A-Z)"
if [ "$OPTION_TYPE" != "P" ] && [ "$OPTION_TYPE" != "C" ]; then
  echo "Unknown option type: $OPTION_TYPE\nMust be 'C' or 'P'. Specify as '58P' or '58C'."
  exit 1
fi
IS_BULLISH=1
STRATEGY_NAME=
[ "$OPTION_TYPE" = "P" ] && STRATEGY_NAME="Short put"
[ "$OPTION_TYPE" = "C" ] && STRATEGY_NAME="Short call" && IS_BULLISH=0

if [ -z "$TICKER" ]; then
  printf "Ticker symbol: "
  read TICKER
  [ -z "$TICKER" ] && echo "Empty ticker" && exit 1
fi
TICKER=`echo $TICKER | tr a-z A-Z`

if [ -z "$expiry_input" ]; then
  printf "Option expiry date: "
  read expiry_input
  [ -z "$expiry_input" ] && echo "Empty expiry" && exit 1
fi
EXPIRY_DATE=$expiry_input
EXPIRY_YEAR=$(date +%Y)
if echo $expiry_input | grep -F \' >/dev/null; then
  EXPIRY_DATE=$(echo $expiry_input | cut -d\' -f1)
  EXPIRY_YEAR="20$(echo $expiry_input | cut -d\' -f2)"
fi
daysUntilExpiry=$(echo $(( ($(date -d "$EXPIRY_DATE $EXPIRY_YEAR" +%s) - $(date +%s)) / 86400 +1 )))
[ "$daysUntilExpiry" -lt 0 ] && echo "Expiry date is in the past: $EXPIRY_DATE $EXPIRY_YEAR, days until expiry $daysUntilExpiry" && exit 1
langfristig=0
[ "$daysUntilExpiry" -gt 40 ] && langfristig=1

if [ -z "$DELTA" ]; then
  printf "Option delta: "
  read DELTA
fi
DELTA=`echo $DELTA | sed -r 's/^\.?([0-9]+)$/0.\1/'` # normalize to 0.302

if [ -z "$QUANTITY" ]; then
  printf "Quantity (1): "
  read QUANTITY
  [ -z "$QUANTITY" ] && QUANTITY=1
fi

if [ -z "$PREMIUM" ]; then
  printf "Option premium: "
  read PREMIUM
  [ -z "$PREMIUM" ] && echo Empty option premium && exit 1
fi

if [ -z "$IV" ]; then
  printf "IV: "
  read IV
  [ -z "$IV" ] && echo Empty IV && exit 1
fi
IV=`echo $IV | sed -r 's/^\.([0-9]+)/0.\1/; s/^0\.([0-9]{2})/\1./; s/\.$//'` # normalize to 30.2%

if [ -z "$UNDERLYING_PRICE" ]; then
  printf "Price of the underlying: "
  read UNDERLYING_PRICE
fi

IMG="img/$TICKER $(date +%Y-%m-%d).png"
if gum confirm "Use currently latest screenshot as the chart image? ($(screenshot-chart get_latest))"; then
  IMG="$(screenshot-chart get_latest)"
fi

print_price_calculations() {
  if [ "$langfristig" -eq 1 ]; then
  cat <<EOF
| Premium       | $PREMIUM |
| Quantity      | $QUANTITY |
| Money at risk |      |
| Profit ca.    |      |
|---------------+------|
| LMT (50%, 14d $(date -d "+14 days" +%b%d)) | |
| LMT (80%)            | |
| STP (200%)    |      |
$(echo '#+TBLFM: @3$2=@1*2*@2*100,0;%.0f_' `: 2 from 200% stop-loss` \
'@4$2=@1*@2*100*.8-2_' `: .8 from 80% take profit, 2 as estimated commission` \
'@5$2=@1*.5;%.2f$_' `: .5 from 50% take profit for first 2 weeks` \
'@6$2=@1*.2;%.2f$_' `: .2 from 80% take profit` \
'@7$2=@1*3;%.2f$' | # 3 from 100% premium + 200% stop-loss
sed 's/[^:] /::/g')
EOF
  else
  cat <<EOF
| Premium       | $PREMIUM |
| Quantity      | $QUANTITY |
| Money at risk |      |
| Profit ca.    |      |
|---------------+------|
| LMT (80%)     |      |
| STP (200%)    |      |
$(echo '#+TBLFM: @3$2=@1*2*@2*100,0;%.0f_' `: 2 from 200% stop-loss` \
'@4$2=@1*@2*100*.8-2_' `: .8 from 80% take profit, 2 as estimated commission` \
'@5$2=@1*.2;%.2f$_' `: .2 from 80% take profit` \
'@6$2=@1*3;%.2f$' | # 3 from 100% premium + 200% stop-loss
sed 's/[^:] /::/g')
EOF
  fi
}

file_content() {
  cat <<EOF

* $TICKER $(date '+%b%d') :<++>:
** What?
[[https://optionstrat.com/build/short-put/$TICKER/-.${TICKER}$(date -d "$EXPIRY_DATE $EXPIRY_YEAR" +%y%m%d)${OPTION_TYPE}${STRIKE}][${expiry_input} ${STRATEGY_NAME} at ${STRIKE}${OPTION_TYPE}]]

Delta: $DELTA
| Price of underlying $ |  $UNDERLYING_PRICE |
| Strike price        $ |  $STRIKE |
| Option IV             |   $IV% |
| Expiry           days |   $daysUntilExpiry |
|-----------------------+-------|
| 1σ                  $ |       |
| distance from strike  |       |
$(echo '#+TBLFM: @5$2=@1*@3*sqrt(@4/365);%.2f::@6$2=('$([ "$IS_BULLISH" = 1 ] && echo '@1-@2' || echo '@2-@1')')/@5;%.2fσ')

** Why? What is supposed to happen here?
[[file:$IMG]]
<++>

** Was spricht dagegen?
<++>

Next earnings: $(gum spin --title "Fetching next earnings date" -- earn $TICKER)

** Prices
$(print_price_calculations)

| Ticker | Trade Type | Qty | Prämie | Buyback | Prämie% |   P/L | Expiry | IV | Strike | Price |   1σ | Distance | Commission | Entry Date+Time | Exit Date+Time |
|--------+------------+--------+-----+--------+------------+---------+--------+--------+----------+-----------+----------+---------+------+------------------|
| $TICKER   | $STRATEGY_NAME | $QUANTITY |    <++> |    -1 |    |     | $daysUntilExpiry | $IV% | $STRIKE | $UNDERLYING_PRICE | | | <++> | $(date "+%Y-%m-%d %H:")<++> | <++> |
$(echo '#+TBLFM: @2$6..@$6=$5<0?0:(1-($5/$4));%.2f_' `: Buyback check with <0 because 0 would mean wertlos verfallen` \
'@2$7..@$7=$5<0?0:($3*$4*100)-$14-($3*$5*100);%.2f_' \
'@2$12..@$12=$9*$11*sqrt($8/365);%.2f_' \
'@2$13..@$13=('$([ "$IS_BULLISH" = 1 ] && echo '$11-$10' || echo '$11-$10')')/$12;%.2fσ' |
sed 's/[^:] /::/g')

** Learnings
EOF
# inline comment syntax
# `: comment`
# append extra char at the end of string "_", because it will be truncated for some reason
}

FILE="$TRADES_DIR/trades.org"
file_content >>"$FILE" 2>/dev/null
emacsclient -e "(progn (tab-bar-new-tab) (find-file \"$FILE\"))" >/dev/null \
  && echo "Opened in emacs"

# (org-table-recalculate-buffer-tables) mangles P/L headlines where @2$7..@$7 is used
