#! /bin/sh

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ] || [ -z "$1" ]; then
  cat <<EOF
$ short-titles PROJECT_DIR
List articles with a description that is:
  - too short <50 chars
  - too long >60 chars

Analogous to the ahrefs Title too short/Title too long categories
EOF
  exit
fi

hash grep || exit 127

match() {
  grep -Po "title: [\"']?\K.*" content -r
}

cd $1
match | while read entry; do
  file=$(echo $entry | cut -d: -f1)
  desc="$(echo $entry | cut -d: -f2- | rev | cut -c2- | rev)"
  count=$(echo $desc | wc -c)
  if [ "$count" -lt 50 ] || [ "$count" -gt 60 ];then
    echo "$file ($count)"
  fi
done

printf "Total: %d\n" "$(match | wc -l)"
