#! /bin/sh

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  cat <<EOF
$ killlf
Kill all lf related programs
EOF
  exit
fi

kill $(pidof lf) 2>/dev/null
ps -aux | grep -e "lf/preview" -e "lf/cleaner" | awk '{ print $2 }' | xargs kill 2>/dev/null

tmux list-windows -aF "#{window_id} #{window_name}" | grep "lf$" | cut -d\  -f1 | xargs -I@ tmux kill-window -t @

true
