#! /bin/sh

MAIN=main

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  cat <<EOF
$ new-day
Open a new tmux window with stuff to get ready for the new day

To be run as a cronjob:
0 4 * * * ~/scripts/tmux/new-day
EOF
  exit
fi

~/scripts/cron/waitforinternet

if ! tmux has-session -t $MAIN 2>/dev/null; then
  exit 1
fi

tmux -u new-window -t $MAIN
tmux send-keys "mc" "enter" # calendar
tmux split-window -v -l 16
tmux send-keys "clear" "enter" "wttr" "enter" # weather

# ~/scripts/apps/anki >/dev/null 2>&1 & # vocab
