#! /bin/sh

SESSION=main

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  cat <<EOF
$ new-day
Open a new tmux window with stuff to get ready for the new day

To be run as a cronjob:
0 4 * * * ~/scripts/tmux/new-day
EOF
  exit
fi

~/scripts/cron/waitforinternet

if ! tmux has-session -t $SESSION 2>/dev/null; then
  exit 1
fi

tmux -u new-window -d -n "new day" -t $SESSION:6
tmux send-keys -t $SESSION:6 "mc; days" "enter" # calendar
