#! /bin/sh

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  printf "$ routine-tmux
Called from routine script, executed in new tmux session
"; exit
fi

command -v tmux >/dev/null || { echo "tmux is not installed"; exit 1; }

tmux -u new-session -s routine \; \
  send-keys "backlight max" "Enter" \; \
  new-window -n "meditation" -c "$HOME/projects/morning_routine/meditation/Headspace" "exec lf" \; \
  kill-pane -t 1 \; \
  move-window -s 2 -t 1 \; \
  new-window -n "affirmations" -c "/tmp" "exec vim $HOME/code/notes/affirmations.md" \; \
  new-window -n "viz" -c "$HOME" "exec watch -t -n 100 'figlet Visualizations'" \; \
  new-window -n "music" "exec ~/scripts/mpd/ncmpcpps -s playlist" \; \
  new-window -n "timer" "exec watch -t -n 1 ~/scripts/figlet-clock" \; \
  new-window -n "reading notes" -c "$HOME/code/notes/books" "exec vim" \; \
  new-window -n "book" "exec lf ~/ct/books" \; \
  # new-window -n "book" "exec epr \"$(~/scripts/queue/bookq)\"" \; \
  new-window -n "writing" "exec watch -t -n 100 'figlet Writing'" \; \
  new-window -n "c3" "exec ~/scripts/bluetooth/charge3" \; \
  select-window -t 7 \; \
  select-window -t 6 \; \
  select-window -t 5 \; \
  select-window -t 4 \; \
  select-window -t 3 \; \
  select-window -t 2 \; \
  select-window -t 1
# \; for running commands in the same session
