#! /bin/sh

MUSIC_DIR=$HOME/ct/music

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ] || [ -z "$1" ]; then
  cat << EOF
$ amv ALBUM [OUT]
Move an album to another dir, while creating the enclosing artist directory

Parameters:
  \$1: album dir
  [\$2]: out dir

Example:
  $ amv "Clispe/Lord Willin'" out
  #=> out/Clispe/Lord Willin'
EOF
  exit
fi

ALBUM=`realpath "$1"`
OUT="$2"
[ -z "$2" ] && OUT="$MUSIC_DIR/_tomove-data"

ARTIST=`basename "$(dirname "$ALBUM")"`
OUT_DIR=""
if [ "$ARTIST" = "music" ] || [ "$ARTIST" = "unheard" ]; then
  OUT_DIR="$OUT"
else
  OUT_DIR="$OUT/$ARTIST"
fi

mkdir -p "$OUT_DIR"
mv "$ALBUM" "$OUT_DIR"
echo "moved to $OUT_DIR"

rmdir $MUSIC_DIR/*
true
