#! /bin/bash

MUSIC_DIR=$ORG_MEDIA/music

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  printf "$ beetim MUSIC
Import music into your library using beet.

Parameters:
  \$1: music to be imported

Example:
  $ beetim ./JAY-Z
"
  exit
fi

command -v beet >/dev/null || { echo "beet is not installed"; exit 1; }
command -v disable-mullvad-for >/dev/null || { echo "disable-mullvad-for script is not in path"; exit 1; }
command -v findex >/dev/null || { echo "findex script is not in path"; exit 1; }
command -v fix-mp3-dates >/dev/null || { echo "fix-mp3-dates script is not in path"; exit 1; }

disable-mullvad-for beet import -I "$@" && {
  printf "Remove imported files? (y/N): "
  read -r res
  if [ "$res" = "y" ]; then
    echo "Removing $@"
    rm -r "$@"
  fi
  # findex $MUSIC_DIR/_imported -name "cover.jpg" 'echo "removing cover: $1"; rm "$1"' # remove covers
  # findex $MUSIC_DIR/_imported -name "cover.png" 'echo "removing cover: $1"; rm "$1"' # remove covers
  findex $MUSIC_DIR/_imported -name "*.mp3" 'fix-mp3-dates "$1"'
}
