#! /bin/bash
# Todo: Fix cant move into unheard, because artist dir already exists

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

FROM=~/ct/music
TO=~/ct/music/unheard

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  printf "$ mv-music
Move new albums in $FROM to $TO
"
  exit
fi

ls -d $FROM/*/ | grep -v -e Electro -e HipHop -e Monstercat -e Other -e Pop -e Rock -e Singles -e Soundtracks -e unheard -e "Various Artists" -e German | while read dir; do
  mv "$dir" "$TO"
  echo Moved $(echo $dir | rev | cut -d/ -f2 | rev)
done

