#! /bin/sh

FROM=~/ct/music
TO=~/ct/music/unheard

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  printf "$ mv-music
Move new albums in $FROM to $TO
"
  exit
fi

ls -d $FROM/*/ | grep -v -e Electro -e HipHop -e Monstercat -e Other -e Pop -e Rock -e Singles -e Soundtracks -e unheard -e "Various Artists" -e German | while read dir; do
  NAME=`basename "$dir"`
  echo Moving $NAME
  if ! mv "$dir" "$TO" 2>/dev/null; then
    printf "  "
    mv -v "$dir/"* "$TO/$NAME"
    rmdir "$dir"
  fi
done

# remove covers
find $TO -name cover.jpg | xargs -d "\n" rm 2>/dev/null || true
