#! /bin/sh

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ] || [ -z "$1" ]; then
  cat <<EOF
$ sc-to-rd SC_ALBUM_URL
Soundcloud to Real-Debrid.
Translate a soundcloud GO+ album into a list of song urls for download w/ real-debrid.

Parameters:
  \$1: soundcloud album url

Example:
  $ sc-to-rd https://soundcloud.com/madlib/sets/shades-of-blue-madlib-invades
EOF
  exit
fi

command -v youtube-dl >/dev/null || { echo "youtube-dl is not installed" 1>&2; exit 127; }

ALBUM="$1"
TMP_IDS=$(mktemp)
TMP_URLS=$(mktemp)

get_ids() {
  youtube-dl "$ALBUM" --get-filename -o "%(id)s"
}

id_to_url() {
  ID="$1"

  # src: https://stackoverflow.com/a/43390556
  curl -Ss "https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/$ID" |
    grep -Po '<link rel="canonical" href="\K.*?">' |
    cut -d\" -f1
}

echo "# get ids"
get_ids >$TMP_IDS

echo "# get urls"
for i in $(<$TMP_IDS); do
  id_to_url "$i" | tee -a $TMP_URLS
done

ALBUM_NAME="$(echo $ALBUM | rev | cut -d\/ -f1 | rev)"
echo "# writing to: $ALBUM_NAME"
cp $TMP_URLS $ALBUM_NAME
