#! /bin/sh

# Todo:
# put artist name (from url) into $ALBUM
# fix extaneous file removal at end
# check for mp3len of an album (30 preview clips)

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ] || [ -z "$1" ]; then
  cat <<EOF
$ sc2rd SC_ALBUM_URL
Soundcloud to Real-Debrid.
Translate a soundcloud GO+ album into a list of song urls for download w/ real-debrid.

Parameters:
  \$1: soundcloud album url

Flags:
  -n: no download

Requires these env variables to be set:
  REALDEBRID_USERNAME
  REALDEBRID_PASSWORD

Example:
  $ sc2rd https://soundcloud.com/madlib/sets/shades-of-blue-madlib-invades
EOF
  exit
fi

command -v yt-dlp >/dev/null || { echo "yt-dlp is not installed" 1>&2; exit 127; }
command -v rdcli >/dev/null || { echo "rdcli is not installed" 1>&2; exit 127; }

ALBUM="$1"
NO_DOWNLOAD=0
[ "$1" = "-n" ] && {
  ALBUM="$2"
  NO_DOWNLOAD=1
}
[ "$2" = "-n" ] && {
  ALBUM="$1"
  NO_DOWNLOAD=1
}

TMP_IDS=$(mktemp)
TMP_URLS=$(mktemp)

get_ids() {
  youtube-dl "$ALBUM" --get-filename -o "%(id)s"
}

id_to_url() {
  ID="$1"

  # src: https://stackoverflow.com/a/43390556
  curl -Ss "https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/$ID" |
    grep -Po '<link rel="canonical" href="\K.*?">' |
    cut -d\" -f1
}

ALBUM_NAME="$(echo $ALBUM | rev | cut -d\/ -f1 | rev)"
ALBUM_SC="$ALBUM_NAME-sc"
echo "working on $ALBUM_NAME"

if [ ! -e "$ALBUM_SC" ] && [ ! -e "$ALBUM_RD" ]; then
  echo "# get ids"
  get_ids >$TMP_IDS

  echo "# get urls"
  for i in $(cat $TMP_IDS); do
    id_to_url "$i" | tee -a $TMP_URLS
  done

  cp $TMP_URLS $ALBUM_SC
fi

if [ -n "$REALDEBRID_USERNAME" ]; then
  ALBUM_RD="$ALBUM_NAME-rd"
  if [ ! -f "$ALBUM_RD" ]; then
    echo "# converting w/ rd"
    rm "$ALBUM_RD" 2>/dev/null
    cat $ALBUM_SC | while read url; do timeout 10 rdcli -p "$url" | tee -a "$ALBUM_RD"; done
  fi

  if [ "$NO_DOWNLOAD" -eq 0 ]; then
    ALBUM_DIR="$ALBUM_NAME-data"
    mkdir -p "$ALBUM_DIR"
    echo "# download album"
    cd "$ALBUM_DIR"
    wget -nv -nc -i "../$ALBUM_RD" 2>&1 | grep -v "SSL"
    if ls *.mp3 2>/dev/null; then
      echo "# mp3len of album (sus if around: $(node -e \"console.log\(\($(ls *.mp3 | wc -l)*30/60\).toFixed\(2\)\)\"), $(ls *.mp3 | wc -l) tracks\)"
      mp3len *.mp3
    fi
    cd ..
    rmdir $ALBUM_DIR 2>/dev/null
  fi
fi

if [ "$NO_DOWNLOAD" -eq 0 ]; then
  printf "Delete extraneous files? (Y/n): "
  read ans
  if [ "$ans" != "n" ]; then
    rm "$ALBUM_SC" "$ALBUM_RD" 2>/dev/null
  fi
fi
true
