#! /bin/sh

ALBUM_AR=Singles
ALBUM=Mixed
BASE_ALBUM=$ALBUM

MUSIC_DIR="$HOME/ct/music"
SINGLES_DIR="$MUSIC_DIR/_tomove-data/Singles"

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  printf "$ single MP3_FILES
Automatic tagging and moving based on filename and defaults or arguments

Supported filename formats:
- 'artist - title.mp3'
- 'title.mp3' (uses album artist as artist)
- 'n. artist - title.mp3'
- 'n. title.mp3'

Defaults (can be changed in script file and overwritten through arguments below):
Album Artist: $ALBUM_AR
Album: $ALBUM
Track: none
Cover: if cover.jpg|png or FILENAME.jpg available

Filenames will be left intact.

Parameters:
  \$1+: mp3 files

Arguments:
  none                  : results in: $ALBUM_AR/$ALBUM
  -A ARTIST             : Set custom album artist (if empty use Artist)
                          results in: ARTIST/$ALBUM
  -a ALBUM              : Set custom album
                          results in: $ALBUM_AR/ALBUM
  -AA ALBUM_ARTIST ALBUM: Set custom album artist and album
                          results in: ALBUM_ARTIST/ALBUM

Examples:
  $ single 'Louis Cole - Blimp.mp3'
    #=> moved to $MUSIC_DIR/$ALBUM_AR/$ALBUM/Louis Cole - Blimp.mp3

  $ single -A James\ Blake '08. James Blake feat. Andre 3000 - Where's the Catch_.mp3'
    #=> moved to $MUSIC_DIR/James Blake/$ALBUM/08. James Blake feat. Andre 3000 - Where's the Catch_.mp3
  $ single -A 'Black Muffin' 'Warrior.mp3'
    #=> moved to $MUSIC_DIR/Black Muffin/$ALBUM/Warrior.mp3

  $ single -a Energy 'Sesto Sento - Apollo 11.mp3'
    #=> moved to $MUSIC_DIR/$ALBUM_AR/Energy/Sesto Sento - Apollo 11.mp3
  $ single -a 5 'Sesto Sento - Apollo 11.mp3'
    #=> moved to $MUSIC_DIR/$ALBUM_AR/Energy/Sesto Sento - Apollo 11.mp3

  $ single -AA JAY-Z 'The Blueprint' *.mp3
    #=> moved to $MUSIC_DIR/JAY-Z/The Blueprint/SONGS
"; exit
fi

command -v eyeD3 >/dev/null || { echo "eyeD3 is not installed"; exit 1; }

if [ "$1" = "-A" ]; then
  ALBUM_AR="$2"
  shift
  shift
fi
if [ "$1" = "-a" ]; then
  ALBUM="$2"
  shift
  shift
  case "$ALBUM" in # I structure my singles by atmosphere, going into one of these bins
    1|Chill ) ALBUM=1_Chill ;;
    2|Chilly) ALBUM=2_Chilly;;
    3|Normal) ALBUM=3_Normal;;
    4|Upbeat) ALBUM=4_Upbeat;;
    5|Energy) ALBUM=5_Energy;;
  esac
fi

if [ "$1" = "-AA" ]; then
  ALBUM_AR="$2"
  ALBUM="$3"
  shift
  shift
  shift
fi

echo "## Tagging these files:"
echo "   $@"
echo "## with album artist: $ALBUM_AR"
echo "## with album       : $ALBUM"

tag() {
  local file_raw="$1"
  if [ "${file_raw##*.}" != "mp3" ]; then
    echo "skipping: $file_raw - not an mp3"
    break;
  fi

  # local trackNr=""
  # if echo "$1" | grep -P "^\d+\.\s" >/dev/null; then
  #   trackNr=$(echo "$1" | grep -Po "^\d+(?=\.\s)")
  # fi
  local file="$(echo "$1" | sed 's|^[0-9]*\.\s||')" # remove leading track number
  local artist=""
  local title=""

  if echo "$1" | grep " - " >/dev/null; then
    # has artist + title
    artist="$(echo "$file" | grep -Po '.+(?= - )')" # inverse of \K: https://unix.stackexchange.com/a/437408
    title="$(echo "${file%.*}" | grep -Po '(?<= - ).+')" # \K
  else
    # only has title
    title="$(echo "${file%.*}" | sed 's|^[[:space:]]*||; s|[[:space:]]*$||')"
    [ -n "$ALBUM_AR" ] && artist="$ALBUM_AR"
  fi

  local webpCover="${file_raw%.*}.webp"
  if [ -e "$webpCover" ]; then
    # webp -> jpg cover
    ffmpeg -i "$webpCover" "${file_raw%.*}.jpg" >/dev/null 2>&1
    rm "$webpCover"
  fi

  local coverFile="${file_raw%.*}.jpg"
  [ ! -e "$coverFile" ] && coverFile="${file_raw%.*}.png"
  [ ! -e "$coverFile" ] && coverFile="cover.jpg"
  [ ! -e "$coverFile" ] && coverFile="cover.png"

  id3v2 --track "" --year "" "$file_raw"
  if [ -e "$coverFile" ]; then
    eyeD3 -2 --album-artist "$ALBUM_AR" --album "$ALBUM" --artist "$artist" --title "$title" --remove-all-comments --add-image "$coverFile":FRONT_COVER "$file_raw"
    [ "${coverFile%.*}" != "cover" ] && rm "$coverFile"
  else
    eyeD3 -2 --album-artist "$ALBUM_AR" --album "$ALBUM" --artist "$artist" --title "$title" --remove-all-comments $cover "$file_raw"
  fi
  chmod 644 "$file_raw"
  # --disc-num 0
  # --release-year 0 --release-date 0
}

for f in "$@"; do
  tag "$f"
done

rm cover.jpg cover.png 2>/dev/null # remove shared cover

if [ "$ALBUM" != "$BASE_ALBUM" ] && [ "$ALBUM_AR" != "Singles" ]; then
  printf "Add tracknumbers to album? (Y/n): "
  read ans
  if [ "$ans" != "n" ] && [ "$ans" != "N" ]; then
    tag-tracknumbers
  fi
fi

if [ "$ARTIST_AS_ALBUM_AR" = 0 ]; then
  mkdir -p $SINGLES_DIR
  mv -v "$@" $SINGLES_DIR
else
  DIR="$MUSIC_DIR/$ALBUM_AR"
  [ -d "$DIR" ] || DIR="$MUSIC_DIR/unheard/$ALBUM_AR"
  DIR="$DIR/$ALBUM"
  echo Using: $DIR
  mkdir -p "$DIR"

  mv -v "$@" "$DIR" 2>/dev/null
fi
true
