#! /bin/sh

LOCAL_MUSIC=~/ct/music
LOCAL_UNHEARD=$LOCAL_MUSIC/unheard

MNT_POINT=/media/usb
MNT_UNHEARD=$MNT_POINT/unheard

PI="pi:~/music"

if [ "$1" = "--help" ] || [ "$1" = "help" ]; then
  echo "$ sync-music"
  echo "Sync $LOCAL_MUSIC with backup drive mounted on $MNT_POINT"
  exit
fi

# sudo rsync -avr $LOCAL_MUSIC/ $MNT_POINT # --delete

rsync -avr --inplace --del $LOCAL_MUSIC/ $PI

