#! /bin/sh

ALBUM_AR=Singles
ALBUM=Mixed

MUSIC_DIR="$HOME/ct/music"
SINGLES_DIR="$MUSIC_DIR/_tomove-data/Singles"

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  printf "$ tag-single <mp3s>
Tag singles as:
Album Artist: $ALBUM_AR
Album: $ALBUM
Artist: from filename
Title: from filename
Date: none
Track: none

Parameters:
  \$1+: files

Parameter:
  -A: Set custom album artist (if empty use Artist)

Example:
  $ tag-single 'Louis Cole - Blimp.mp3'
  $ tag-single -A 'Black Muffin' 'Black Muffin - Warrior.mp3'
  $ tag-single -A 'Black Muffin - Warrior.mp3'
"; exit
fi

command -v eyeD3 >/dev/null || { echo "eyeD3 is not installed"; exit 1; }

ARTIST_AS_ALBUM_AR=0
if [ "$1" = "-A" ]; then
  ALBUM_AR="$2"
  ARTIST_AS_ALBUM_AR=1
  shift
  shift
fi
echo $@

tag() {
  local file_raw="$1"
  local file="$(echo "$1" | sed 's|^[0-9]*\.\s||')" # remove leading track number
  local artist=""
  local title=""

  if echo "$1" | grep " - " >/dev/null; then
    # has artist + title
    artist="$(echo "$file" | cut -d- -f1 | sed 's|^[[:space:]]*||; s|[[:space:]]*$||')"
    title="$(echo "${file%.*}" | cut -d- -f2 | sed 's|^[[:space:]]*||; s|[[:space:]]*$||')"
  else
    # only has title
    title="$(echo "${file%.*}" | sed 's|^[[:space:]]*||; s|[[:space:]]*$||')"
  fi

  local album_ar="$ALBUM_AR"
  [ "$ARTIST_AS_ALBUM_AR" -eq 1 ] && album_ar="$artist"

  local coverFile="${file_raw%.*}.jpg"

  # id3tag --track 0 --year "" "$file_raw" # clears all existing tags, good for dates, bad for lyrics, images
  id3v2 --track "" --year "" "$file_raw"
  if [ -e "$coverFile" ]; then
    eyeD3 -2 --album-artist "$album_ar" --album "$ALBUM" --artist "$artist" --title "$title" --remove-all-comments --add-image "$coverFile":FRONT_COVER "$file_raw"
    rm "$coverFile"
  else
    eyeD3 -2 --album-artist "$ALBUM_AR" --album "$ALBUM" --artist "$artist" --title "$title" --remove-all-comments $cover "$file_raw"
  fi
  # --disc-num 0
  # --release-year 0 --release-date 0
}

for f in "$@"; do
  tag "$f"
done

if [ "$ARTIST_AS_ALBUM_AR" = 0 ]; then
  mv -v "$@" $SINGLES_DIR
else
  DIR="$MUSIC_DIR/$ALBUM_AR"
  [ -d "$DIR" ] || DIR="$MUSIC_DIR/unheard/$ALBUM_AR"
  DIR="$DIR/Mixed"
  echo Using: $DIR
  mkdir -p "$DIR"

  mv -v "$@" "$DIR"
fi
