#! /bin/bash

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  cat <<EOF
$ unhrd [-m]
Print your amount of unheard music

Flags:
  -m: use main instead

Example:
  $ unhrd
  #=> 37.194 MB
EOF
  exit
fi

if [ "$1" = "-m" ]; then
  du -sc -B M --apparent-size -L $ORG_MEDIA/music/main "$ORG_MEDIA/materialistic music/main" | # inverted match from below
    tail -n1 | cut -dM -f1 | ~/scripts/human-number | awk '{print $1" MB"}'
  exit 0
fi

du -sc -B M --apparent-size -L $ORG_MEDIA/music/[^m]* "$ORG_MEDIA/materialistic music/unheard" | # exclude anything starting w/ m from match
  tail -n1 | cut -dM -f1 | ~/scripts/human-number | awk '{print $1" MB"}'
