#! /bin/sh

# DATA_DIR="$XDG_DATA_HOME/bitmonero"
# nice monerod --prune-blockchain --sync-pruned-blocks --max-concurrency 4 --data-dir $DATA_DIR --config-file $DATA_DIR/bitmonero.conf --log-file $DATA_DIR/bitmonero.log >/dev/null 2>&1 &
nice /bin/monero-wallet-gui >/dev/null 2>&1 &
