#! /bin/sh

AUR_HELPER=yay

if [ "$1" = "--help" ] || [ "$1" = "help" ]; then
  echo "$ pacman-load"
  echo "Download pacman updates without installing them"
  exit
fi

## yay flags:
# yy - force database reload
# uu - upgrade pkgs, allow downloading
# w  - download but dont install
# p  - print results

echo "Y" | $AUR_HELPER -Syuuw
echo "" | $AUR_HELPER -Sua # aur
