#! /bin/sh

AUR_HELPER=yay

if [ "$1" = "--help" ] || [ "$1" = "help" ]; then
  echo "$ pacman-load"
  echo "Download pacman updates without installing them"
  exit
fi

# download updates
$AUR_HELPER -Syyuuw --print-format "%n %v" | grep -f pacman-load-block-pattern -v
# yy - force database reload
# uu - upgrade pkgs, allow downloading
# w  - download but dont install
# p  - print results

