#! /bin/bash

#$AUR_HELPER=yay

if [[ $1 = "--help" ]] || [[ $1 = "help" ]]; then
  echo "$ pacu"
  echo "Update pacman packages"
  exit
fi

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
PKGS_FILE=~/pkgs
PKGS_NAMES="$DIR/pkg-names"

function version {
  echo "$@" | gawk -F. '{ printf("%03d%03d%03d%03d\n", $1,$2,$3,$4); }';
}

MATCHES=$(cat $DIR/arch-news/manual-pkgs | grep -f $PKGS_NAMES)

for NAME in $(echo $MATCHES | cut -d " " -f 1); do
  MANUAL_FULL=$(echo $MATCHES | grep $NAME)
  MANUAL_VERSION=$(echo $MANUAL_FULL | cut -d " " -f 2) 
  PKG_UPDATE_VERSION=$(cat $PKGS_FILE | grep $NAME | cut -d " " -f 2)

  if [[ $((10#$(version $PKG_UPDATE_VERSION))) -gt $((10#$(version $MANUAL_VERSION))) || $((10#$(version $MANUAL_VERSION))) -eq $((10#$(version $PKG_UPDATE_VERSION))) ]]; then
    echo $MANUAL_FULL
  fi
done

yay -Suu 

rm $PKGS_FILE
