#! /bin/sh

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  cat <<EOF
$ up
Update everything.

Not just pacman -Syu, but various other things that need regular updates.
EOF
  exit
fi

reapply_X_settings() {
  # reapply xorg settings after upgrading
  setxkbmap -option caps:escape
  xset r rate 185 100
}
cleanup() {
  reapply_X_settings
}
trap cleanup EXIT

log() {
  local category=$1
  local text="$2"
  printf "\033[1;32m[%s]\033[1;33m %s\n\033[1;0m" "$category" "$text"
}

run_yay() {
  log yay "System update"

  sudo pacman -Syu
  reapply_X_settings

  yay --color=always --noconfirm
  reapply_X_settings

  yay -Qtdq | yay -Rsn --noconfirm -
}
command -v yay >/dev/null && run_yay

run_volta() {
  log volta "Update volta apps"
  volta install node
  volta install npm
  volta install yarn
}
command -v volta >/dev/null && run_volta

run_hosts() {
  log hosts "Updating hosts"
  update-hosts
}
command -v update-hosts >/dev/null && run_hosts

run_lazy() {
  log hosts "Updating nvim plugins"
  cd /tmp
  /bin/nvim --headless '+Lazy! sync' +qa
  /bin/nvim --headless '+TSUpdate' +qa
}
command -v /bin/nvim >/dev/null && run_lazy

cleanup-fs
