#! /bin/sh

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  cat <<EOF
$ up
Update everything.

Not just pacman -Syu, but various other things that need regular updates.
EOF
  exit
fi

log() {
  local category=$1
  local text="$2"
  printf "\033[1;32m[%s]\033[1;33m %s\n\033[1;0m" "$category" "$text"
}

run_antidot() {
  log antidot "Update antidot rules"
  antidot update
}
command -v antidot >/dev/null && run_antidot

run_volta() {
  log volta "Update volta apps"
  volta install node
  volta install npm
  volta install yarn
}
command -v volta >/dev/null && run_volta

run_yay() {
  log yay "System update"
  if command -v disable-mullvad-for >/dev/null; then
    disable-mullvad-for yay --color=always --noconfirm
  else
    yay --color=always --noconfirm
  fi

  # reapply xorg settings after upgrading
  setxkbmap -option caps:escape
  xset r rate 185 100

  yay -S --color=always --noconfirm exa-git
  yay -S --color=always --noconfirm lf-git
  yay -S --color=always --noconfirm ncmpcpp-git

  yay -Qtdq | yay -Rsn --noconfirm -
}
command -v yay >/dev/null && run_yay

run_hosts() {
  log hosts "Updating hosts"
  update-hosts
}
command -v update-hosts >/dev/null && run_hosts

run_lazy() {
  cd /tmp
  /bin/nvim --headless '+Lazy! sync' +qa
}
command -v /bin/nvim >/dev/null && run_lazy
