#! /bin/sh

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  cat <<EOF
$ up
Update everything.

Not just yay -Syu, but also all other things that need regular updates.
EOF
  exit
fi

cleanup() {
  remap # Xorg remappings need to be reapplied
  cleanup-fs
}
trap cleanup EXIT

log() {
  local category=$1
  local text="$2"
  printf "\033[1;32m[%s]\033[1;33m %s\n\033[1;0m" "$category" "$text"
}

run_yay() {
  log yay "System update"

  nice -n 19 sudo pacman -Syu
  reapply_X_settings

  nice -n 19 yay --color=always --noconfirm
  nice -n 19 yay -S yt-dlp-git --noconfirm
  reapply_X_settings

  yay -Qtdq | yay -Rsn --noconfirm -
}
hash yay && run_yay

run_volta() {
  log volta "Update volta apps"
  volta install node
  volta install npm
  volta install yarn
  volta install bun
}
command -v volta >/dev/null && run_volta

run_nix() {
  log nix "Update nix packages"
  nice -n 19 nix profile upgrade --all
  nice -n 19 nix-collect-garbage
}
hash nix && run_nix

run_hosts() {
  log hosts "Updating hosts"
  update-hosts
}
hash update-hosts && run_hosts
