#! /bin/sh

if [ "$1" = "--help" ] || [ "$1" = "help" ]; then
  echo "$ btconnect <mac-address>"
  echo "Connect to a bluetooth device via bluetoothctl."
  echo ""
  echo "The device has to be trusted and paired via"
  echo "bluetoothctl manually beforehand:"
  echo "  $ bluetoothctl"
  echo "  power on"
  echo "  scan on"
  echo "  # get the mac address as it gets scanned"
  echo "  trust <mac>"
  echo "  pair <mac>"
  echo ""
  echo "Example:"
  echo "$ btconnect B8:D5:0B:EA:D9:A6"
  exit
fi

printf "power on\nquit" | bluetoothctl > /dev/null

echo "Started connecting"

while [ 1 -eq 1 ]; do
  if printf "connect %s\nquit" "$1" | bluetoothctl | grep "# quit" | grep "bluetooth" > /dev/null; then
    sleep 1
  else
    echo "Connected"
    break
  fi
done

