#! /bin/sh

if [ "$1" = "--help" ] || [ "$1" = "help" ]; then
  cat << EOF
$ btconnect MAC-ADDRESS
Connect to a bluetooth device via bluetoothctl.

The device has to be trusted and paired via
bluetoothctl manually beforehand:
  $ bluetoothctl
  power on
  scan on
  # get the mac address as it gets scanned
  trust <mac>
  pair <mac>

Example:
  $ btconnect B8:D5:0B:EA:D9:A6
EOF
  exit
fi

bluetoothctl power on
bluetoothctl connect "$1"
