#! /bin/sh

if [ "$1" = "--help" ] || [ "$1" = "help" ]; then
  echo "$ btdevice"
  echo "Display name of currently connected bluetooth device"
  echo "Error if empty"
  exit
fi

DEV=$(echo -e "quit" | bluetoothctl | fgrep quit | grep -Po "\[0;94m\[\K.*" | cut -d\] -f1)

if [ "$?" -eq 0 ] && [ "$DEV" != "bluetooth" ]; then
  echo $DEV
else
  exit 1
fi

