#! /bin/sh

if [ "$1" = "--help" ] || [ "$1" = "help" ]; then
  echo "$ btdevice"
  echo "Display name of currently connected bluetooth device"
  echo "Error if empty"
  exit
fi

if bluetoothctl info >/dev/null 2>&1; then
  dev="$(bluetoothctl info | grep Name | cut -d\  -f2-)"
  case "$dev" in
    "soundcore Motion 300") echo jneidel-hang;;
    *) echo $dev
  esac
else
  exit 1
fi
