#! /bin/sh

if [ "$1" = "--help" ] || [ "$1" = "help" ]; then
  echo "$ btdevice"
  echo "Display name of currently connected bluetooth device"
  echo "If no device is connected the output will be empty"
  exit
fi

CUR=$(echo -e "quit" | bluetoothctl | grep quit | grep "\[" | cut -d "[" -f 3 | cut -d "]" -f 1)

[[ "$CUR" != "bluetooth" ]] && echo $CUR || echo ""

