#! /bin/bash

if [[ $1 = "--help" ]] || [[ $1 = "help" ]]; then
  echo "$ btoff"
  echo "Turn off bluetooth via bluetoothctl"
  exit
fi

echo -e "power off\nquit" | bluetoothctl > /dev/null 2>&1

# kill keep alive audio stream
kill $(pgrep -f "mpv -ao pulse /home/jneidel/scripts/personal/audio.mp3 --mute --loop-file=inf") 2> /dev/null || true
