#! /bin/sh
# connect to my personal JBL Charge 3 speaker

btconnect B8:D5:0B:AD:AA:26

# stream random audio file over bluetooth to stop charge from stuttering when using it in connect mode
# kill $(pgrep -f "$HOME/scripts/personal/audio.mp3") 2>/dev/null
# /bin/mpv -ao pulse ~/scripts/personal/audio.mp3 --mute --loop-file=inf >/dev/null 2>&1 &
