#! /bin/sh

LOCK_FILE=/tmp/docked

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ] || [ -z "$1" ]; then
  cat <<EOF
$ dock [connect|disconnect]
Trigger some actions upon connect/disconnect of the dock.
EOF
  exit
fi

# set env for udev to interact with Xorg
export DISPLAY=:0
export XAUTHORITY=/run/user/1000/Xauthority

export TMUX=/tmp/tmux-1000/default
tmux_session=main

case "$1" in
  connect)
    if /home/jneidel/scripts/monitor -m on; then
      /home/jneidel/scripts/monitor off
      /home/jneidel/scripts/monitor -m on
    fi
    touch $LOCK_FILE

    sleep 4s; /home/jneidel/scripts/sxhkd/backlight set 0
    if tmux has-session -t $tmux_session; then
      tmux -u new-window -d -n "dock" -t $tmux_session:98
      tmux send-keys -t $tmux_session:98 "/home/jneidel/scripts/cron/natural-brightness; exit" "enter"
    fi
    ;;
  disconnect)
    /home/jneidel/scripts/monitor off &
    rm $LOCK_FILE /tmp/secondary-monitor 2>/dev/null
    /home/jneidel/scripts/sxhkd/backlight percent 50 &

    if tmux has-session -t $tmux_session; then
      tmux -u new-window -d -n "dock" -t $tmux_session:98
      sleep 8s; tmux send-keys -t $tmux_session:98 "/home/jneidel/scripts/cron/natural-brightness; exit
" "enter"
    fi
    ;;
esac
