#! /bin/sh

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ] || [ -z "$1" ]; then
  cat <<EOF
$ split-keyboard connect
Run some scripts on connect

Commands:
  \$1: connect
EOF
  exit
fi

hash xmodmap xset || exit 127

if [ "$1" != "connect" ]; then
  exit 1
fi

# set env for udev to interact with Xorg
export DISPLAY=:0
export XAUTHORITY=/run/user/1000/Xauthority

# does not work when called directly, despite correct X env vars
# run through ethemeral tmux background window
export TMUX=/tmp/tmux-1000/default
tmux_session=main
if tmux has-session -t $tmux_session; then
  tmux -u new-window -d -n "xset" -t $tmux_session:99
  tmux send-keys -t $tmux_session:99 "xmodmap /home/jneidel/.config/Xmodmap-remove-Hyper_R; xmodmap /home/jneidel/.config/Xmodmap; xset r rate 185 100; exit" "enter"
fi

# make firmware on microchip editable by vial
ls -tc /dev/hidraw* | head -n3 | tr "\n" " " | xargs chmod a+rw
