#! /bin/bash

if [[ $1 = "--help" ]] || [[ $1 = "help" ]]; then
  echo "$ backlight"
  echo "Interact with the backlight."
  echo ""
  echo "Commands:"
  echo "  set <brightness>: set brightness"
  echo "  get: get current brightness"
  echo "  max: get the maxium brightness"
  echo "  percent: set the brightness using percentages (+2, -5)"
  echo ""
  echo "Example:"
  echo "$ backlight set 250 # set brightness to max"
  echo "$ backlight p +1 # increase brightness by 10%"
  exit
fi

FILE=/sys/class/backlight/intel_backlight/brightness
# you might need to run
#   sudo chown jneidel
# on the brightness file, otherwise you wont be able to write it, not even with sudo
MAX=$(cat /sys/class/backlight/intel_backlight/max_brightness) # 2777

function set() {
  if [[ -n $1 && $1 -gt -1 && $1 -lt $(($MAX+1)) ]]; then
    echo $1 > $FILE
    echo $1
  else
    echo "Invalid number passed to set" 
    echo "It needs to be between 0 and $MAX"
    exit
  fi
}
function get() {
  cat $FILE
}
function percent() {
  if [[ $(echo $1 | cut -c 1) = "+" ]]; then
    PERCENTAGE=$(echo $1 | cut -d + -f 2)
    RES=$(echo "$(get)+(0.$PERCENTAGE*($MAX-5))" | bc | cut -d . -f 1)
    if [[ $RES -lt -1 ]]; then
      RES=0
    elif [[ $RES -gt $MAX ]]; then
      RES=$MAX
    fi
    set $RES
  elif [[ $(echo $1 | cut -c 1) = "-" ]]; then
    PERCENTAGE=$(echo $1 | cut -d - -f 2)
    RES=$(echo "$(get)-(0.$PERCENTAGE*($MAX-5))" | bc | awk '{printf "%f", $0}' | cut -d . -f 1)
    if [[ $RES -lt -1 || $RES -eq -1 || $RES -eq -0 ]]; then # weird edge cases, but I want display to go black
      RES=0
    elif [[ $RES -gt $MAX ]]; then
      RES=$MAX
    fi
    set $RES
  else
    echo "Invalid parameter passed to percent"
    echo "Please pass a number prefixed with '+' or '-'"
  fi
}

case $1 in
  s|set) set $2;;
  g|get) get;;
  m|max) echo $MAX;;
  p|perc|percent) percent $2;;
  *) echo "Please pass a command. Pass 'help' for help.";;
esac

