#! /bin/bash

ALIAS_NAME=vv
ALIAS_FILE=~/.zsh/apps.zsh

if [[ $1 = "--help" ]] || [[ $1 = "help" ]]; then
  echo "Usage (in ~/.newsboat/config:"
  echo "macro y set browser "path/to/this/script %u"; open-in-browser ; set browser "$BROWSER %u""
  echo ""
  echo "How it works:"
  echo "greps the alias named $ALIAS_NAME from $ALIAS_FILE and executes that command."
  exit
fi

CMD=$(grep $ALIAS_NAME $ALIAS_FILE | cut -d '"' -f 2)

$CMD "$1"

