#! /bin/sh

DATA_DIR=~/ct/dont_touch
ORDER="$DATA_DIR/order"
MOVIES="$DATA_DIR/m"

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ] || [ -z "$2" ]; then
  cat << EOF
$ add_movie_torrent NAME MAGNET
Add a movie for consumption with the newentertainment script

Parameters:
  \$1: name of the movie
  \$2: magnet link for the movie
EOF
  exit
fi

command -v webtorrent >/dev/null || { echo "webtorrent is not installed"; exit 127; }

FILE_NAME="$1"
MAGNET="$2"

format() {
cat << EOF
#! /bin/sh
stream-movie "$TORRENT"
EOF
}

FILE="$MOVIES/$FILE_NAME"
format > "$FILE"
chmod +x "$FILE"
echo "$FILE" | rev | cut -d/ -f1-2 | rev >> "$ORDER"

echo "Added file: $FILE"
