#! /bin/bash

if [ "$1" = "--help" ] || [ "$1" = "help" ]; then
  echo "$ colored-man"
  echo "Color man page"
  echo ""
  echo "Parameters:"
  echo "  \$1: man page to read"
  exit
fi

export LESS_TERMCAP_mb=$'\e[1;34m'
export LESS_TERMCAP_md=$'\e[1;33m' # headlines, hyperlinks - yellow
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_so=$'\e[1;34m' # less status - blue
export LESS_TERMCAP_se=$'\e[0m'
export LESS_TERMCAP_us=$'\e[1;31m' # commands - red
export LESS_TERMCAP_ue=$'\e[0m'

man $1

