#! /bin/sh

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ] || [ -z "$2" ]; then
  cat <<EOF
$ combine-audio-video AUDIO VIDEO [OUT]
Simple combination without transcoding.
EOF
  exit
fi

hash ffmpeg || exit 127

# TODO: print what was passed as audio and video
# gum confirm

ffmpeg -i "$VIDEO" -i "$AUDIO" -map 0:v -map 1:a -c:v copy -c:a copy "$OUT.mkv"
