#! /bin/bash

if [ "$1" = "--help" ] || [ "$1" = "help" ]; then
  echo "$ comicup"
  echo "Get new issues of subscribed comics from getcomics-dl and"
  echo "fetch their download link from getcomics.info"
  exit
fi

TMP_FILE=$(mktemp)
echo "autoStart=TRUE
autoConfirm=TRUE
" > $TMP_FILE

$HOME/code/getcomics-dl/bin/new.js | tee --output-error=warn >(grep -o "http.*$" | while read LINK; do
  curl -s "$LINK" | grep -Po "https://getcomics.info/run.php-urls/.*?\"" | head -n1 | cut -d\" -f1  | sed "s/^h/    h/" | awk '{ print "text="$0 }' >> $TMP_FILE
done)

sleep 6
cp $TMP_FILE ~/tmp/comicup.crawljob
# jdownloader

# jdownloader files in dotfiles

