#! /bin/sh

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ] || [ -z "$1" ]; then
  cat <<EOF
$ earn TICKER
Open next earning date for ticker symbol

Parameters:
  \$1: ticker

Example:
  $ earn AAPL
EOF
  exit
fi

if command -v chromium >/dev/null; then
  chromium "https://www.earningswhispers.com/stocks/$1" >/dev/null 2>&1 &
else
  $BROWSER "https://www.earningswhispers.com/stocks/$1" >/dev/null 2>&1 &
fi
