#! /bin/sh

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  cat <<EOF
$ generate-orgmode-metadata TITLE
Generate the metadata block for the top of an orgmode file.

Arguments:
  \$1: title
EOF
  exit
fi

title="$1"
id=$(uuidgen)

cat <<EOF
:PROPERTIES:
:ID: $id
:END:
#+title: $title
#+date: $(date +%Y-%m-%d)
EOF
