#! /bin/sh

if [ "$1" = "--help" ] || [ "$1" = "help" ]; then
  cat <<EOF
$ github-notifications
Get the number of notifications of your github account.
For usage in scripts.

Parameters:
  \$1: Username and access token.
    Create a new token in
      'github>settings>developer settings'
    with only notification rights.
    Format: 'username:token'

Example:
$ github-notifications jneidel:mytoken
EOF
  exit
fi

command -v jq >/dev/null || { echo "jq is not installed"; exit 1; }

if [ -z "$1" ]; then
  echo "Requires 'username:token' as a parameter"
  exit
fi

curl -sS -u "$1" https://api.github.com/notifications | jq length
