#! /bin/bash

if [ "$1" = "--help" ] || [ "$1" = "help" ]; then
  echo "$ human-number"
  echo "Make a long number more easily readable by"
  echo "inserting dots after every 3rd character."
  echo ""
  echo "Parameters:"
  echo "  stdin: number to work on"
  echo ""
  echo "Example:"
  echo "$ echo "12345678910" | human-number"
  echo "-> 12.345.678.910"
  exit
fi

cat /dev/stdin | # read from stdin
  sed 's/\(.\)/\1\n/g' | # split at every char, i.e. insert a newline after every char
  sed '/^\s*$/d' | # remove empty lines (created at the end after spliting)
  sed '1!G;h;$!d' | # reverse order
  sed ': loop; n; n; a .
#n; b loop' | # create a dot after each 3rd char
  sed '1!G;h;$!d' | # reverse order back to normal
  tr -d '\r\n' | # add a newline after every char (reverse 1st cmd)
  sed 's/^\.//' | # remove leading dot
  awk '{ print $1 }' # add newline at the end

