#! /bin/sh

INBOX=$HOME/org/0_inbox

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ] || [ -z "$1" ]; then
  cat <<EOF
$ inbox FILE
Move a file into the inbox dir

Parameters:
  \$1: file to be moved

Example:
  $ inbox ./note.md
EOF
  exit
fi

FILE="$1"
if [ -e "$1" ]; then
  mv "$FILE" "$INBOX/"
  echo "Moved '$FILE' to inbox"
fi
