#! /bin/sh

if [ "$1" = "--help" ] || [ "$1" = "help" ]; then
  cat << EOF
$ ipa
Get current ip address
Gets the first ipv4 entry in 'ip addr' that is not loopback or tun
Returns localhost if offline
EOF
  exit
fi

ipa() {
  ip a | fgrep "inet " | \
    grep -ve " tun" -e " lo" | head -n1 | \
    awk '{ print $2 }' | cut -d"/" -f1
}

[ -n "$(ipa)" ] && ipa || echo "localhost"
