#! /bin/sh

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  cat << EOF
$ it
Internet Toggle
EOF
  exit
fi

# command -v <++> >/dev/null || { echo "<++> is not installed"; exit 127; }

sudo rm /etc/resolv.conf

