#! /bin/sh

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  printf "$ lf-preview
Handle lf previews

Setup in lfrc: set previewer ~/scripts/lf-preview
"; exit
fi

~/scripts/mime/mime preview "$1"
