#! /bin/sh

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  printf "$ monitor [-m|-e] [-s] [on|off|swap]
Control the connected monitor in various ways.

Commands:
      : if none, toggle on/off (mirroring)
  on  : turn external display on
  off : turn external display off
  swap: swap between two connected external displays
        transfers mirroring from one to the other

Action flags:
  -m: mirror (default)
  -e: extend, add as a second screen

Selection flags:
  -s: use the second of the two connected monitors
      if omitted uses the first one

Example:
  $ monitor # toggle mirroring on/off
  $ monitor off
  $ monitor -m
  $ monitor -m on
  $ monitor -s -m on
  $ monitor -e
  $ monitor swap
"; exit
fi

hash xrandr || exit 127

case `cat /etc/hostname` in
  jneidel-x270)
    MAIN_RESOLUTION=1920x1080
    ;;
  jneidel-x240)
    MAIN_RESOLUTION=1366x768
    ;;
  jneidel-e495)
    MAIN_RESOLUTION=1920x1080
    MAIN=eDP-1
    ;;
  *)
    echo "Device is not configured in script, using xrandr output instead.";;
esac

[ -z "$MAIN" ] && MAIN=$(xrandr | grep primary | cut -d\  -f1)
[ -z "$MAIN_RESOLUTION" ] && MAIN_RESOLUTION=$(xrandr | grep primary | cut -d\  -f4 | awk -F+ '{ print $1 }')

# first connected monitor (apart from MAIN) it can find
MONITOR_PRIMARY=$(xrandr | grep " connected" | grep -v "$MAIN" | head -n1 | cut -d\  -f1)
MONITOR_SECONDARY=$(xrandr | grep " connected" | grep -ve "$MAIN" -e "$MONITOR_PRIMARY" | head -n1 | cut -d\  -f1)
MONITOR_RESOLUTION=1920x1080

printf "Using:
  Main     : $MAIN - $MAIN_RESOLUTION
  Primary  : $MONITOR_PRIMARY - $MONITOR_RESOLUTION
  Secondary: $MONITOR_SECONDARY
\n"

IS_MIRROR=true
MONITOR=$MONITOR_PRIMARY
while getopts "mse" opt; do
  case "$opt" in
    m) IS_MIRROR=true;;
    s) MONITOR=$MONITOR_SECONDARY;;
    e) IS_MIRROR=false;;
    :) printf '%s\n' "error: -$OPTARG requires an argument" >&2; exit 2 ;;
 esac
done
shift $((OPTIND - 1))

turn_off() {
  if [ -z "$MONITOR" ]; then
    MONITOR="$(xrandr --listmonitors | grep -v "*" | tail -n1 | cut -d\  -f3 | cut -c2-)"
    if [ -n "$MONITOR" ]; then
      echo "No monitor connected. Disabling active '$MONITOR' instead."
    fi
  fi
  if [ -n "$MONITOR" ]; then
    xrandr --output $MONITOR --off
    echo "Turned external monitor off."
    true
  else
    echo "No monitor found, doing nothing."
    false
  fi
}

add_monitor() {
  xrandr --output $MONITOR --mode $MONITOR_RESOLUTION --right-of $MAIN --scale-from $MAIN_RESOLUTION >/dev/null
}
mirror() {
  echo "mirroring"
  xrandr --output $MONITOR --mode $MONITOR_RESOLUTION --scale-from $MAIN_RESOLUTION --same-as $MAIN >/dev/null
}

turn_on() {
  if $IS_MIRROR; then
    mirror || exit 1
  else
    add_monitor || exit 1
  fi
  xwallpaper --zoom ~/.config/wallpaper.png &

  echo "Turned external monitor on"
  true
}

swap() {
  monitor_active="$(xrandr --listmonitors | grep -v "*" | tail -n1 | cut -d\  -f3 | cut -c2-)"
  if [ "$MONITOR_PRIMARY" ] && [ "$MONITOR_SECONDARY" ] && [ "$monitor_active" ]; then
    if [ "$monitor_active" = "$MONITOR_PRIMARY" ]; then
      monitor -s -m on &
      monitor off &
      touch /tmp/secondary-monitor
    else
      monitor -m on &
      monitor -s off &
      rm /tmp/secondary-monitor
    fi
  fi
  natural-brightness -q
}

if [ "$1" = "swap" ]; then
  swap
  exit 0
fi

if xrandr --listactivemonitors | grep " $MONITOR" >/dev/null; then
  if [ ! "$1" = "on" ]; then
    turn_off
  else
    false
  fi
else
  if [ ! "$1" = "off" ]; then
    turn_on
  else
    false
  fi
fi
