#! /bin/bash

if [[ $1 = "--help" ]] || [[ $1 = "help" ]]; then
  echo "$ mullvad-lan-toggle"
  echo "Toggle mullvads lan option"
  echo ""
  echo "Setting description:"
  echo "  Control the allow local network sharing setting"
  echo ""
  echo "This is a security risk if enabled"
  exit
fi

if [[ $(mullvad lan get | awk '{ print $5 }') = "block" ]]; then
  mullvad lan set allow 1> /dev/null
  printf "Lan set to: \033[1;31mallow\n"
else
  mullvad lan set block 1> /dev/null
  printf "Lan set to: \033[1;32mblock\n"
fi
