#! /bin/sh

HOSTS=/etc/hosts

if [ "$1" = "--help" ] || [ "$1" = "help" ]; then
  echo "$ netflix-toggle"
  echo "Remove/add netflix.com to/from $HOSTS"
  echo ""
  echo "Pass either 'on' or 'off' to control the setting."
  exit
fi

[ ! -e "$HOSTS" ] && {
  echo "Hosts file is not active"
  exit 1
}

remove() {
  # sudo sed -i -n "/www.netflix.com/d; /www.youtube.com/d" $HOSTS
  # printf "\033[1;31mRemoved\033[0m netflix & youtube from hosts file\n"
  echo "Removal is disallowed"
}
add() {
  sudo sh -c "printf '0.0.0.0 www.netflix.com\n0.0.0.0 www.youtube.com' >> $HOSTS"
  printf "\033[1;32mAdded\033[0m netflix & youtube to hosts file\n"
}

if [ -n "$1" ]; then
  if [ "$1" = "off" ]; then
    remove
  elif [ "$1" = "on" ]; then
    add
  fi
  exit 0
fi

if grep "www.netflix.com" $HOSTS > /dev/null; then
  remove
else
  add
fi

