#! /bin/sh

DATE_FILE=$HOME/.local/share/newentertainment_date
PENS_FILE=$HOME/.local/share/newentertainment_pensum
DIR=$HOME/ct/dont_touch
ORDER=$DIR/order
MOVED=$DIR/moved
WATCH_DIR=$HOME/ct/movies
TESTING=0

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  cat << EOF
$ newentertainment
Once a day, you can add media corresponding to the pensum of $PENSUM to your watch directory.
EOF
  exit
fi

PENSUM="$(cat $PENS_FILE || 120)"

if [ "$(date -d "$(cat $DATE_FILE)" +%s)" -gt "$(date -d 'today 0' +%s)" ]; then
  if [ "$PENSUM" -eq 0 ]; then
    echo "info: You had your share for today. Check in tomorrow."
    exit 0
  else
    echo "info: Using leftover pensum of: $PENSUM"
  fi
else
  echo "info: First usage with pens of 120"
  PENSUM=120
  printf 120 > $PENS_FILE
fi

# pensum can't behandled in a variable, as its inconsistend between functions
PENSUM_FILE=$(mktemp)
printf $PENSUM > $PENSUM_FILE
read_pensum() {
  cat $PENSUM_FILE
}
write_pensum() {
  printf $1 > $PENSUM_FILE
}

has_pensum() {
  media_type="$1"
  pensum=$(read_pensum)
  case "$media_type" in
    s60) [ "$pensum" -ge 60 ] && true || false;;
    s20) [ "$pensum" -ge 20 ] && true || false;;
    m) [ "$pensum" -ge 120 ] && true || false;;
  esac
}

decrement_pensum() {
  media_type="$1"
  case "$media_type" in
    s60) write_pensum $(($(read_pensum) - 60));;
    s20) write_pensum $(($(read_pensum) - 20));;
    m) write_pensum 0;;
  esac
  echo "pens: $media_type $(read_pensum)"
}

rm_line() {
  line="$1"
  tmp=$(mktemp)
  grep -Fv "$line" $ORDER > $tmp
  cp $tmp $ORDER
}

move() {
  file="$1"
  cd "$DIR"
  echo "move: $(basename "$1")"
  [ "$TESTING" -eq 0 ] && cp "$1" "$WATCH_DIR"
  [ "$TESTING" -eq 0 ] &&  mv "$1" "$MOVED"
}

handle_series() {
  name="$1"

  find "$DIR/$name" -regextype posix-extended -regex '.*\.(mkv|mp4|avi)' | sort | while read -r file; do
    if echo $file | fgrep "/s20/" >/dev/null; then
      media_type=s20
    else
      media_type=s60
    fi

    if has_pensum $media_type; then
      move "$file"
      decrement_pensum $media_type
    fi

    if [ "$(read_pensum)" -eq 60 ]; then
      echo "info: Breaking at half pensum: $(read_pensum)"
      return 12 # exit early
    fi
  done
}
handle_movie() {
  name="$1"
  media_type="m"

  if has_pensum $media_type; then
    move "$name"
    decrement_pensum $media_type
    [ "$TESTING" -eq 0 ] && rm_line "$1"
  fi
}

while read -r name; do
  case $name in
    s60*|s20*) handle_series "$name"
      if [ "$?" -eq 12 ]; then # reached half pens
        break
      fi ;;
    m*) handle_movie "$name" ;;
  esac
done <$ORDER

printf "$(read_pensum)" > $PENS_FILE # write to persistent pensum file
date > $DATE_FILE
