#! /bin/sh

BROWSER=$(grep "^export BROWSER=" ~/.zshrc | cut -d\= -f2)

if [ "$1" = "--help" ] || [ "$1" = "help" ]; then
  echo "$ open-in-browser-without-pluses"
  echo "Remove '+' (pluses) from url before opening them in '$BROWSER'"
  echo ""
  echo "Built for opening links in neomutt with the kitty terminal open shortcut."
  echo "See kitty config for more info."
  echo ""
  echo "Parameters:"
  echo "  \$1: url to clean"
  exit
fi

URL="$1"

echo "$1" | sed "s/+//g" | xargs -r $BROWSER

