#! /bin/sh

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ] || [ -z "$1" ]; then
  cat <<EOF
$ open-orgmode-file-at-title-insert FILE
Open the new file in insert mode, at the correct position to enter a title.

Parameters:
  \$1: file in question

Example:
  $ open-orgmode-file-at-title-insert /tmp/123.org
EOF
  exit
fi

hash emacsclient || exit 127

FILE="$1"

emacsclient -t --eval --suppress-output "(progn
  (find-file \"$FILE\")
  (goto-char 10)
  (evil-insert 1))"
