#! /bin/sh

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  printf "$ psk <++>
<++>

Parameters:
  \$1: <++>
  [\$1]: <++>

Example:
  $ psk <++>
"; exit
fi

# command -v <++> >/dev/null || { echo "<++> is not installed"; exit 1; }

kill $(ps | grep "$1" | awk '{print $1 }') 2>/dev/null

