#! /bin/sh

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  cat << EOF
$ rec [OUTPUT]
Record the screen

Parameters:
  [\$1]: Name of the output file (automatic .mkv)
    defaults to: recording_$(date +%Y-%b-%d_%H_%M_%S)

Example:
  $ vid output
EOF
  exit
fi

OUTPUT="recording_$(date +%Y-%b-%d_%H_%M_%S).mkv"
[ -n "$1" ] && OUTPUT="$1.mkv"

command -v ffmpeg >/dev/null || { echo "ffmpeg is not installed"; exit 1; }

test_audio() {
  # play sound and check on stream if sound is being played
  timeout 3 mpv --no-audio-display --no-video ~/scripts/personal/audio.mp3 >/dev/null 2>&1
  sleep 7 && timeout 3 mpv --profile=overlay "$OUTPUT" >/dev/null 2>&1
}
test_audio &

# -s size (dimension)
# -f format (x/alsa)
# -i input (x display/pulse/default)
# -y to overwrite files
# -r framerate
# -preset fast ~30% ultrafast ~20% cpu

ffmpeg -s $(xdpyinfo | grep dimensions | awk '{ print $2 }') \
  -f x11grab -i :0.0 \
  -f alsa -i pulse \
  -r 20 \
  -threads 0 \
  -vcodec libx264 \
  -preset fast \
  "$OUTPUT"
# -r 30 \

  # -acodec pcm_s16le -vcodec libx264 -preset fast -crf 0 -threads 0 \

# adapt quality/size options
## https://ubuntuforums.org/showthread.php?p=8746719#post8746719

# change the recording device in pavucontrol
##  https://askubuntu.com/questions/682144/capturing-only-desktop-audio-with-ffmpeg
