#! /bin/sh

COMIC_DIR=~/comics
SEPERATOR="-----------------------------------------------------------"

if [ "$1" = "--help" ] || [ "$1" = "help" ] || [ -z "$1" ]; then
  echo "rename-comic: <comic> [<more-comics>]"
  echo "Format comic names and move them into the comic dir"
  echo ""
  echo "The accpected format is the one of running issues from getcomics.info:"
  echo "Input format:  Oblivion Song 011 (2019) (Digital) (Zone-Empire).cbr"
  echo "Output format: oblivion-song-011.cbr"
  echo ""
  echo "Parameters:"
  echo "  \$1+: comic path(s)"
  echo ""
  echo "Example:"
  echo "  $ rename-comic Gideon\ Falls\ 015\ \(2019\)\ \(Digital\)\ \(Mephisto-Empire\).cbr Outpost\ Zero\ 011\ \(2019\)\ \(Digital\)\ \(Zone-Empire\).cbr "
  exit
fi

echo "moving comics to comic dir at:\n  '$COMIC_DIR'"
echo $SEPERATOR

for COMIC in "$@"; do
  DIR_NAME=$(format-comic-name.js "$COMIC" nameonly)
  mkdir -p "$COMIC_DIR/$DIR_NAME"

  COMIC_NAME=$(format-comic-name.js "$COMIC")
  OUT_FILE="$COMIC_DIR/$DIR_NAME/$COMIC_NAME"

  echo "moving\n  '$COMIC'\nto\n  '$OUT_FILE'"
  mv "$COMIC" "$OUT_FILE"

  echo $SEPERATOR
done

