#! /bin/sh

if [ "$1" = "--help" ] || [ "$1" = "help" ]; then
  echo "$ repo"
  echo "Open github repository of current npm package in $BROWSER"
  exit
fi

if [ -e "package.json" ]; then
  LINK="$(jq ".repository" < package.json | sed -e 's/"//g' | awk '{ printf "https://github.com/"$1 }')"
  $BROWSER "$LINK" >/dev/null 2>&1 &
else
  echo package.json does not exist in this directory
fi

