#! /bin/sh

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  cat << EOF
$ sleeptimer <++>
<++>

Parameters:
  \$1: <++>
  [\$1]: <++>

Example:
  $ sleeptimer <++>
EOF
  exit
fi

TIMER="$1"

command -v mpvctl >/dev/null || { echo "mpvctl is not in PATH"; exit 127; }
# command -v <++> >/dev/null || { echo "<++> is not installed"; exit 127; }

pause() {
  if mpvctl get name >/dev/null 2&>1; then
    mpvctl key Q # quit, save state
  else
    ~/scripts/sxhkd/control-mpd.sh toggle
  fi
}

sleep "$TIMER" && pause
