#! /bin/sh

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  cat << EOF
$ sleeptimer TIME
Set a sleeptimer to stop mpv/mpd after

Parameters:
  \$1: timer given to sleep

Example:
  $ sleeptimer 20m
EOF
  exit
fi

TIMER="$1"

command -v mpvctl >/dev/null || { echo "mpvctl is not in PATH"; exit 127; }
command -v control-mpd >/dev/null || { echo "control-mpd is not installed"; exit 127; }

pause() {
  if mpvctl get name >/dev/null 2&>1; then
    mpvctl key Q # quit, save state
  else
    control-mpd pause
  fi
}

sleep "$TIMER" && pause
