#! /bin/bash

TMP_DIR=~/tmp
TMP_COOKIE=$TMP_DIR/.spc
PDF_VIEWER=zathura
USERNAME=s0...
PASSWORD="" # needs to be url encoded
  # for example with:
  #   node -e "console.log( encodeURIComponent( 'p@$$word!' ) )"

function updateCookie() {
  curl -Ssi https://lsf.htw-berlin.de/qisserver/rds\?state\=user\&type\=1 -d "username=$USERNAME&password=$PASSWORD&submit=Einloggen" |
    grep -F "JSESSIONID" | grep -Po "JSESSIONID=.*?\.ajp13_qis5" | cut -d= -f2 | tee >(cat > $TMP_COOKIE)
}

SESSION_COOKIE=""
if cat $TMP_COOKIE 1>/dev/null 2>/dev/null; then
  SESSION_COOKIE=$(cat $TMP_COOKIE)
else
  echo "Updating session cookie"
  SESSION_COOKIE=$(updateCookie)
fi

if [ "$1" = "--help" ] || [ "$1" = "help" ]; then
  echo "$ sp"
  echo "Get current Stundenplan from HTW website and open it"
  echo ""
  echo "Parameter:"
  echo "  [\$1]: week modifier, e.g. +1 to show next week, -1 for last week, etc."
  echo ""
  echo "Flags:"
  echo "  --no-viewer, only works as \$2"
  exit
fi

command -v $PDF_VIEWER >/dev/null || { echo "PDF_VIEWER ('$PDF_VIEWER') is not installed"; exit 1; }
mkdir -p $TMP_DIR

[ "$2" = "--no-viewer" ] && PDF_VIEWER=""

WEEK=$(($(date +%U)+1))
[ -n "$1" ] && WEEK=$(($WEEK $1))

YEAR=$(date +%Y)
FILE="$TMP_DIR/stundenplan-$YEAR-$WEEK.pdf"

if [ ! -e "$FILE" ]; then
  WEEK_YEAR=$WEEK"_"$YEAR
  curl -Ss "https://lsf.htw-berlin.de/qisserver/rds?state=pdfplan&moduleCall=freePositionPlanStudy&week=$WEEK_YEAR&planid=0" -b "JSESSIONID=$SESSION_COOKIE" > "$FILE"

  if cat "$FILE" | grep "Die aufgerufene Funktion kann aufgrund von fehlenden Zugriffsrechten nicht" >/dev/null; then
    echo "Updating session cookie"
    SESSION_COOKIE=$(updateCookie)
    curl -Ss "https://lsf.htw-berlin.de/qisserver/rds?state=pdfplan&moduleCall=freePositionPlanStudy&week=$WEEK_YEAR&planid=0" -b "JSESSIONID=$SESSION_COOKIE" > "$FILE"
  fi
fi

[ -n "$PDF_VIEWER" ] &&
  $PDF_VIEWER "$FILE" || exit 0

