#! /bin/sh

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  printf "$ todays-events <++>
Print todays entries in khal.
"; exit
fi

command -v khal >/dev/null || { echo "khal is not installed"; exit 1; }

khal list Today Today -f "{title} [{start-time}-{end-time}]" -df "" | sed "s/:00//g; s/ /_/g" | xargs printf "%60s\n" | tr "_" " " | grep -v "No events"

exit 0

