#! /bin/bash

if [[ $1 = "--help" ]] || [[ $1 = "help" ]]; then
  echo "$ trim"
  echo "Trim whitespace of \$1"
  echo ""
  echo "Parameters:"
  echo "\$1: String to be trimmed"
  echo ""
  exit
fi

STR=$1
STR="$(echo -e "${STR}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
echo -n $STR

