#! /bin/bash

# Source: https://wiki.archlinux.org/index.php/Mirrors#Fetching_and_ranking_a_live_mirror_list

MIRROR_LIST=/etc/pacman.d/mirrorlist

if [[ $1 = "--help" ]] || [[ $1 = "help" ]]; then
  echo "$ update-mirrors"
  echo "Update $MIRROR_LIST with the 5 fasted mirrors from DE/SE"
  echo ""
  echo "Dependencies:"
  echo "  pacman-contrib"
  exit
fi

N=5
if [[ -n $1 ]]; then
  N=$1
fi

curl -s "https://www.archlinux.org/mirrorlist/?country=DE&country=SE&protocol=https&use_mirror_status=on" | sed -e 's/^#Server/Server/' -e '/^#/d' | rankmirrors -n $N -v - | sudo tee $MIRROR_LIST

