#! /bin/bash

if [[ $1 = "--help" ]] || [[ $1 = "help" ]]; then
  echo "$ sudo hostsup"
  echo "Update /etc/hosts & /etc/hosts.deny files from"
  echo "  https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist"
  exit
fi

HOSTS=/etc/hosts
HOSTS_DENY=/etc/hosts.deny
OG_HOSTS=/home/jneidel/code/dotfiles/manjaro/etc/hosts

echo "Setting $HOSTS"
sudo rm $HOSTS 2> /dev/null
sudo cp $OG_HOSTS $HOSTS
curl -sSL https://hosts.ubuntu101.co.za/hosts \
  | sed -e '1,55d' \
  | sed "/0.0.0.0 soundcloud.com/d" \
  | sed "/0.0.0.0 imagecomics.com/d" \
  | sed "/0.0.0.0 humblebundle.com/d" \
  | sed "/0.0.0.0 www.humblebundle.com/d" \
  | sed "/0.0.0.0 store.steampowered.com/d" \
  | sed "/0.0.0.0 steampowered.com/d" \
  | sed "/0.0.0.0 forums.steampowered.com/d" \
  | sed "/0.0.0.0 meetup.com/d" \
  | sed "/0.0.0.0 musicbrainz.org/d" \
  | sed "/0.0.0.0 xkcd.com/d" \
  | sed "/0.0.0.0 www.namecheap.com/d" \
  | sed "/0.0.0.0 1337x.to/d" \
  | sed "/0.0.0.0 larrysanger.org/d" \
  | sed "/0.0.0.0 www.theguardian.com/d" \
  | sed "/0.0.0.0 www.heise.de/d" \
  | sed "/0.0.0.0 heise.de/d" \
  | sed "/0.0.0.0 turbobit.net/d" \
  | sed "/0.0.0.0 www.catb.org/d" > /tmp/hosts
sudo mv /tmp/hosts $HOSTS

echo "Setting $HOSTS_DENY"
sudo rm $HOSTS_DENY > /dev/null
sudo wget -q https://hosts.ubuntu101.co.za/superhosts.deny -O $HOSTS_DENY

