#! /bin/sh

if [ "$(pwd)" = "$HOME" ]; then
  if tmux list-sessions | grep attached | grep main >/dev/null && \
    tmux list-windows | grep active | grep ^1 >/dev/null; then
    /bin/nvim
  else
    echo "Don't open vim from the home directory!"
  fi
else
  /bin/nvim $@ 2>/dev/null
fi
