#! /bin/sh

if [ "$(pwd)" = "$HOME" ]; then
  if tmux list-sessions | grep attached | grep main >/dev/null && \
    tmux list-windows | grep active | grep ^1 >/dev/null; then

    if [ -e "/bin/nvim" ]; then
      /bin/nvim 2>/dev/null
    elif [ -e "/usr/bin/nvim" ]; then
      /usr/bin/nvim 2>/dev/null
    elif [ -e "/usr/local/bin/nvim" ]; then
      /usr/local/bin/nvim 2>/dev/null
    fi
  else
    echo "Don't open vim from the home directory!"
  fi
else
  if [ -e "/bin/nvim" ]; then
    /bin/nvim "$@" 2>/dev/null
  elif [ -e "/usr/bin/nvim" ]; then
    /usr/bin/nvim "$@" 2>/dev/null
  elif [ -e "/usr/local/bin/nvim" ]; then
    /usr/local/bin/nvim "$@" 2>/dev/null
  fi
fi
