#! /bin/sh

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ -z "$1" ]; then
  echo "$ vx <script-name>"
  echo "Create a new executable file,"
  echo "add a --help menu and open the file in vim."
  echo ""
  echo "Parameters:"
  echo "  \$1: name of the script file to be created"
  echo ""
  echo "Example:"
  echo "  $ vx connect.sh"
  exit
fi

command -v vim >/dev/null || { echo \"vim is not installed\"; exit 1; }

FILE="$1"

echo "#! /bin/sh

if [ \"\$1\" = \"--help\" ] || [ \"\$1\" = \"-h\" ] || [ \"\$1\" = \"help\" ]; then
  printf \"$ $FILE <++>
<++>

Parameters:
  \\\$1: <++>
  [\\\$1]: <++>

Example:
  $ $FILE <++>
\"
  exit
fi

command -v <++> >/dev/null || { echo \"<++> is not installed\"; exit 1; }
" >> "$FILE"

chmod +x "$FILE"
vim "$FILE"

