#! /bin/sh

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ -z "$1" ]; then
  cat <<EOF
$ vx FILENAME
Create a new executable file,
add a --help menu and open it in vim.

Parameters:
  \$1: name of the script to be created

Example:
  $ vx connect.sh
EOF
  exit
fi

command -v $EDITOR >/dev/null || { echo "$EDITOR is not installed or \$EDITOR var not set" 1>&2; exit 127; }

FILE="$1"
file_content() {
  cat <<EOF
#! /bin/sh

if [ "\$1" = "--help" ] || [ "\$1" = "-h" ] || [ "\$1" = "help" ]; then
if [ "\$1" = "--help" ] || [ "\$1" = "-h" ] || [ "\$1" = "help" ] || [ -z "\$1" ]; then
  cat <<EOF
$ $FILE <++>
<++>

Parameters:
  \\\$1: <++>
  [\\\$1]: <++>

Flags:
  -<++>

Example:
  $ $FILE <++>
$(printf EOF)
  exit
fi

hash <++> || exit 127

while getopts ":<++>:" opt; do
  case "\$opt" in
    <++>) ="\$OPTARG";;
    :) printf '%s\n' "error: -\$OPTARG requires an argument" >&2; exit 2 ;;
 esac
done
shift \$((OPTIND - 1))

EOF
}
file_content >>"$FILE"

chmod +x "$FILE"
$EDITOR "$FILE"
