#! /bin/sh

CITY="berlin"

if [ "$1" = "--help" ] || [ "$1" = "help" ]; then
  echo "$ wttr"
  echo "Show todays weather report from wttr.in for $CITY"
  echo ""
  echo "Flags:"
  echo "  -f: Show the 3 day weather report"
  exit
fi

WTTR_FLAGS="FQ1"

[ "$1" = "-f" ] && WTTR_FLAGS="${WTTR_FLAGS:0:-1}" # remove 1 from WTTR_FLAGS

WEATHER=$(curl -s "wttr.in/$CITY?${WTTR_FLAGS}")

# remove wind speed, by dynamically replacing the length of the matched str with spaces (minus color codes)
# src: https://stackoverflow.com/a/7338118
WEATHER=$(perl -e '$ARGV[0] =~ s!((↓|↙|←|↖|↑|↗|→).*?km/h)!" " x (length($1) -36)!eg; print $ARGV[0]' "$WEATHER")
perl -e '$ARGV[0] =~ s!(\d+)\skm!" " x (length($1) +3)!eg; print $ARGV[0]' "$WEATHER" | # remove x km
  sed "s/0.0\smm\s|\s0%/           /g" | # remove 0% rain chance
  sed "s/0.0\smm/      /" | # remove 0.0 mm from current panel
  sed "s/Morning/   8   /g" | sed "s/Noon/  12/g" | sed "s/Evening/   18  /g" | sed "s/Night/  22 /g" | # replace timeofday with numbers
  sed "s/$(date "+%a %d %b")/  Today   /" | # replace current date with 'today'
  sed "s/$(date -d "+1 days" "+%a %d %b")/Tomorrow  /" | # replace next day with 'tomorrow'
  sed "s/$(date -d "+2 days" "+%a %d %b")/ $(date -d "+2 days" "+%a") (+2) /" # replace today+2
echo "" # remove % from the last line

