#! /bin/bash

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  printf "$ YRL
YACReaderLibrary wrapper because it does not want to start for me via rofi
"; exit
fi

command -v YACReaderLibrary >/dev/null || { echo "YACReaderLibrary is not installed"; exit 1; }
command -v kitty >/dev/null || { echo "kitty is not installed"; exit 1; }

kitty --class "YACReaderLibrary" YACReaderLibrary &
