#! /bin/sh

# show clicks, date

YT_FILTER_FILE=~/scripts/personal/ytfilters
export TS_SOCKET=/tmp/tsp-mpv-queue

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  printf "$ yts QUERY
Select a video to play from a list of results for the given query

Example:
  $ yts dark
  #=> opens prompt to choose a video on the topic 'dark'
"; exit
fi

command -v dmenu >/dev/null || { echo "dmenu is not installed"; exit 127; }

QUERY="$(echo $@)"
[ -z "$1" ] && QUERY="$(rofi -dmenu -lines 0 -width 35 -p yts)"
[ -z "$QUERY" ] && exit 1

if [ -e "$YT_FILTER_FILE" ]; then
  if echo "$QUERY" | grep -if $YT_FILTER_FILE >/dev/null; then
    rofi -e "Prohibited query" -width 35
    exit 2
  fi
fi

QUERY=$(node -e "console.log( encodeURIComponent( '$QUERY' ) )")

TMP=$(mktemp)
LINKS=/tmp/yt_links
TITLE=/tmp/yt_titles
LENS=/tmp/yt_len
printf "" > $TITLE

get() {
  echo "querying..."
  curl -sS "https://www.youtube.com/results?search_query=$QUERY" | \
    grep -P "/watch\?v=\K.+?\"" | grep -Fv ";list=" > $TMP
}

parse() {
  grep -Po "title=\"\K.+?\"" $TMP | uniq | grep -ve "Bestätigt" -e "http" -e "Mehr ansehen" | sed "s/.$//; s|&amp;|\&|g; s|&quot;|\"|g; s|&#39;|\'|g" > $TITLE
  grep -Po "Dauer:\ \K.+?<" $TMP | uniq | sed 's/.$//' > $LENS
  grep -Po "/watch\?v=\K.+?\"" $TMP | uniq | sed 's/.$//' > $LINKS
}

while [ -z "$(< $TITLE)" ]
do
  get
  parse
done

PICK="$(paste -d ' ' $TITLE $LENS | dmenu -p yts)"
[ "$?" -gt 0 ] && exit 1

# get corresponding link
paste -d " " $LINKS $TITLE $LENS | grep "$PICK" | cut -d\  -f1 | \
  awk '{ print "https://youtube.com/watch?v="$1 }' | \
  xargs -r tsp mpv --profile=overlay 2>/dev/null
