#! /bin/bash
BIN=extractmo
OUT=~/music/Monstercat/singles-current

if [[ $1 = "--help" ]] || [[ $1 = "help" ]]; then
  echo "$ $BIN"
  echo "Extract, tag and move monstercat singles"
  echo "Singles will be moved to: $OUT"
  echo ""
  echo "Format:"
  echo "'<song-title> (320 MP3).zip' -> '<song-title> (320 MP3)' -v"
  echo "'<artist> - 1 <song-title>.mp3', 'cover.jpg'"
  exit
fi

echo "Running $BIN in $(pwd)"

for F in *\(320\ MP3\)*; do
  echo "---"
  echo "Starting: $F"
  extract $F > /dev/null 2>&1

  # get title, song path
  TITLE=$(echo $F | cut -d "/" -f 2)
  TITLE=$(echo $TITLE | cut -d "(" -f 1)
  TITLE=$(trim $TITLE)
  SONG=$(echo "$TITLE"*/*"$TITLE"*)
  echo "Matched song: $SONG"

  # Ensure match before continuing
  SONG_GREP=$(echo $SONG | grep "*/*")
  if [[ -n $SONG_GREP ]]; then
    echo "EXIT: invalid grep */*"
    exit
  fi

  echo "tagging"
  id3tag -s "$TITLE" "$SONG" > /dev/null 2>&1
  mid3v2 --TPE2 "Monstercat" -A "Mixed" "$SONG" > /dev/null 2>&1

  echo "cleanup"
  mv "$SONG" $OUT
  rm -r "$TITLE"* # remove dir & zip
done

