#! /bin/sh

DEFAULT_LOCATION=/mnt

if [ "$1" = "--help" ] || [ "$1" = "help" ]; then
  echo "$ cryptumount"
  echo "Unmount an luks encrypted disk"
  echo ""
  echo "Parameters:"
  echo "  [\$1]: alternative mount location; default $DEFAULT_LOCATION"
  echo ""
  echo "Example:"
  echo "$ cryptumount"
  echo "$ cryptumount /media/hd"
  echo "$ cryptumount /mnt ext"
  exit
fi

LOCATION=$DEFAULT_LOCATION
if [ -z "$1" ]; then
  [ ! -d $LOCATION ] && {
    echo "Default location '$LOCATION' does not exist."
    echo "Either create it or pass your own."
    exit 1
  }
else
  [ ! -d "$1" ] &&
    LOCATION="$1" ||
    {
      echo "Passed location '$1' does not exist."
      exit 1
    }
fi

DEFAULT_MAPPER=cryptluks
DEFAULT_MAPPER2=cryptext
DEFAULT_MAPPER3=cryptfallback
if [ -n "$2" ] && [ -e /dev/mapper/$2 ]; then
  MAPPER=$2
elif [ -e /dev/mapper/$DEFAULT_MAPPER2 ]; then
  MAPPER=$DEFAULT_MAPPER2
elif [ -e /dev/mapper/$DEFAULT_MAPPER3 ]; then
  MAPPER=$DEFAULT_MAPPER3
else
  MAPPER=$DEFAULT_MAPPER
fi

# umount
sudo umount -R $LOCATION || exit 1
echo "Unmounted"

# close luks
sudo cryptsetup close $MAPPER
echo "Luks closed"

