#! /bin/sh

MOUNT_LOCATION="$HOME/tmp/android"

if [ "$1" = "--help" ] || [ "$1" = "help" ]; then
  echo "$ umoan"
  echo "Unmount android device from $MOUNT_LOCATION"
  exit
fi

fusermount -u "$MOUNT_LOCATION" && echo "umounted android" || echo "unmounting failed"

