#! /bin/sh

MOUNT_LOCATION="~/tmp/android"

if [ "$1" = "--help" ] || [ "$1" = "help" ]; then
  echo "$ umoan"
  echo "Unmount android device from $MOUNT_LOCATION"
  exit
fi

umount "$MOUNT_LOCATION" && "umounted android" || "unmounting failed"

