#! /bin/sh

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  cat << EOF
$ transmission-startup
Start the transmission-daemon with prefered flags
EOF
  exit
fi

command -v transmission-daemon >/dev/null || { echo "transmission-daemon is not installed"; exit 127; }

echo "Starting transmission-daemon"
nice transmission-daemon -c ~/Downloads --encryption-preferred --paused
