#! /bin/sh

if [ "$1" = "--help" ] || [ "$1" = "help" ]; then
  cat << EOF
$ transmission-clear
Remove finished torrents from transmission
EOF
  exit
fi

tsr -l | grep e "100%" -e "Done" | # match completed torrents
  awk '{print $1}' | # get their id
  xargs -n 1 -I % tsr -t % -r | # pass id to transmission to remove
  awk '{ print "tsm-clear: "$0 }' # prefix output with script name

