#! /bin/sh

if [ "$1" = "--help" ] || [ "$1" = "help" ]; then
  echo "$ transmission-kill"
  echo "Kill running transmission-daemon & tsmw"
  exit
fi

kill $(ps aux | grep "watch.*tsr" | grep -v grep | awk '{ print $2 }') 2> /dev/null
kill $(ps aux | grep transmission-daemon | grep -v grep | awk '{ print $2 }') 2> /dev/null && echo "Killed transmission-daemon"
exit 0

