#! /bin/sh

if [ "$1" = "--help" ] || [ "$1" = "help" ]; then
  echo "$ transmission-add"
  echo "Script version of tsmadd alias for sxhd"
  echo ""
  echo "Parameters:"
  echo "  \$1: magnet link to add to tsm"
  exit
fi

CLIP=$(xclip -sel clipboard -o 2>/dev/null)

echo "$CLIP" > ~/tmp/clip

if tsr -a "$CLIP" >/dev/null; then
  notify-send "Added magnet link to tsm" -t 800
  tsr -t "$CLIP" --start
else
  notify-send "Adding the magnet failed" -t 1000
fi

