#! /bin/bash

if [[ $1 = "--help" ]] || [[ $1 = "help" ]]; then
  echo "$ transmission-clear"
  echo "Remove finished torrent from transmission"
  exit
fi

transmission-remote -l | grep 100% | grep Done | awk '{print $1}' | xargs -n 1 -I % transmission-remote -t % -r

echo "Killing transmission-daemon"
fkill transmission-da

