#! /bin/bash

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  cat << EOF
$ tsr CMD
Pass a command to transmission-remote
EOF
  exit
fi

command -v transmission-remote >/dev/null || { echo "transmission-remote is not installed"; exit 127; }
command -v transmission-startup >/dev/null || { echo "transmission-startup script is not in PATH"; exit 127; }

if ! transmission-remote -l >/dev/null 2>&1; then
  transmission-startup
  sleep 7
fi

transmission-remote "${@:1}" || exit 1
