#!/bin/sh

battery_status() {
case $1 in
  "Discharging")
    ext="No";;
  "Charging")
    ext="Yes";;
esac

ioreg -c AppleSmartBattery -w0 | \
grep -o '"[^"]*" = [^ ]*' | \
sed -e 's/= //g' -e 's/"//g' | \
sort | \
while read key value; do
  case $key in
    "MaxCapacity")
      export maxcap=$value;;
    "CurrentCapacity")
      export curcap=$value;;
  esac
  if [[ -n "$maxcap" && -n $curcap ]]; then
    echo $(( 100 * $curcap / $maxcap ))
    break
  fi
done
}

BATTERY_STATUS=`battery_status $1`

echo $(echo ${BATTERY_STATUS} + 2 | bc)%

