#! /bin/sh

if [ "$1" = "--help" ] || [ "$1" = "help" ]; then
  echo "$ transmission-running"
  echo ""
  echo ""
  echo "Parameters:"
  echo "  \$1: "
  echo ""
  echo "Example:"
  echo "$ transmission-running"
  exit
fi

STATUS=$(transmission-status)
[ "$STATUS" -gt 0 ] && echo " tsm $STATUS "

