#! /bin/sh

hash muted-run || exit 127

if [ "$1" = "kill" ]; then
  echo "Killing processes"
  fkill steam
  fkill steamwebhelper
  exit
fi

# if is-focus-challenge >/tmp/out 2>&1; then
#   rofi -e "$(cat /tmp/out)" 2>/dev/null
# else
# fi
# if between 16 22; then
    muted-run /usr/bin/steam
# else
#   rofi -e "Only after 16:00" 2>/dev/null
# fi
