#! /bin/sh

BERLIN=12459

# Todo: how does the script know that I am in dresden after the day of the bus ride?

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  printf "$ toggle-location
Toggle a local location file for determining the location for the weather script.

Toggles between: Berlin & Dresden
"; exit
fi

command -v khal >/dev/null || { echo "khal is not installed"; exit 1; }

LOCATION_FILE="$(dirname $0)/location"

write_loc() {
  printf "$1" >"$LOCATION_FILE"
  echo "Location: $1"
}

toggle_loc() {
  case "$(cat $LOCATION_FILE)" in
    $BERLIN) write_loc 01099;;
    dresden) write_loc $BERLIN;;
    *) write_loc $BERLIN;;
  esac
}

toggle_loc
