#! /bin/sh

CITY="berlin"
WTTR_FLAGS="FQ1"

if [ "$1" = "--help" ] || [ "$1" = "help" ]; then
  echo "$ wttr"
  echo "Show todays weather report from wttr.in for $CITY"
  echo ""
  echo "Flags:"
  echo "  -f: Show the 3 day weather report"
  exit
fi

LOCATION_FILE=~/scripts/weather/location
[ -e "$LOCATION_FILE" ] && CITY="$(cat $LOCATION_FILE)"

if [ "$1" = "-f" ] || [ "$2" = "-f" ]; then
  WTTR_FLAGS="${WTTR_FLAGS:0:-1}" # remove 1 from WTTR_FLAGS
fi

WEATHER=$(curl -s "wttr.in/$CITY?${WTTR_FLAGS}")
EXIT=$?

# remove wind speed, by dynamically replacing the length of the matched str with spaces (minus color codes)
# src: https://stackoverflow.com/a/7338118
WEATHER=$(perl -e '$ARGV[0] =~ s!((↓|↙|←|↖|↑|↗|→|↘).*?km/h)!" " x (length($1) -36)!eg; print $ARGV[0]' "$WEATHER") # remove wind direction
perl -e '$ARGV[0] =~ s!(\d+)\skm!" " x (length($1) +3)!eg; print $ARGV[0]' "$WEATHER" | # remove wind speed
  sed "s/0.0\smm\s|\s0%/           /g" | # remove 0% rain chance
  sed "s/0.0\smm |/        /; s/0.0\smm/      /" | # remove 0.0mm precipitation w/ & w/o pipe
  sed "s/Morning/   8   /g; s/Noon/  12/g; s/Evening/   18  /g; s/Night/  22 /g" | # replace timeofday with numbers
  sed "s/$(date "+%a %d %b")/  Today   /" | # replace current date with 'today'
  sed "s/$(date -d "+1 days" "+%a %d %b")/Tomorrow  /" | # replace next day with 'tomorrow'
  sed "s/$(date -d "+2 days" "+%a %d %b")/ $(date -d "+2 days" "+%a") (+2) /" | # replace today+2
  sed "s/$(date "+%a %d %b" --date yesterday)/Yesterday /" # replace current date with 'today'
echo "" # remove % from the last line

if [ "$EXIT" -gt 0 ]; then
  false
else
  true
fi
