#! /bin/sh

LOGO=`dirname $0`/arch-logo.png
IMG=/tmp/screen_locked.png
PARTS=/tmp/lock_parts_
PART1=${PARTS}0.jpg
PART2=${PARTS}1.jpg

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  cat << EOF
$ lock
Lock screen
EOF
  exit
fi

command -v scrot >/dev/null || { echo "scot is not installed"; exit 1; }
command -v convert >/dev/null || { echo "convert (imagemagick) is not installed"; exit 1; }
command -v i3lock >/dev/null || { echo "i3lock is not installed"; exit 1; }

# take a screenshot
scrot -o $IMG

add_logo_user() {
  # add small arch logo to screen center
  convert $1 $LOGO -gravity center -geometry +0-10 -composite $1

  # add user@hostname above the logo
  convert $1 -font Roboto-Mono-for-Powerline -fill grey -pointsize 16 -gravity center -draw "text 0,-110 '$USER@$(hostname)'" $1
  ## list of fonts: identify -list font
}

process_image() {
  # blur logo, to give it a glow
  add_logo_user $1

  # blur screenshot
  convert $1 -blur 0x6 $1
  ## see for customizing blur: https://www.imagemagick.org/Usage/blur/#blur_args

  # clear logo over the blur
  add_logo_user $1
}

if [ "$(xrandr --listmonitors | head -n1 | awk '{ print $2 }')" -ge 2 ]; then # 2 monitors
  convert $IMG -crop 2x1@ $PARTS%d.jpg

  process_image $PART1
  process_image $PART2

  convert $PARTS*.jpg +append $IMG
else
  process_image $IMG
fi

i3lock -i $IMG --ignore-empty-password
