#! /bin/sh

LOGO=`dirname $0`/arch-logo.png
IMG=/tmp/screen_locked.png

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  cat << EOF
$ lock
Lock screen
EOF
  exit
fi

command -v scrot >/dev/null || { echo "scot is not installed"; exit 1; }
command -v convert >/dev/null || { echo "convert (imagemagick) is not installed"; exit 1; }
command -v i3lock >/dev/null || { echo "i3lock is not installed"; exit 1; }

# take a screenshot
scrot -o $IMG

# blur screenshot
convert $IMG -blur 0x6 $IMG
## see for customizing blur: https://www.imagemagick.org/Usage/blur/#blur_args

# add small arch logo to screen center
convert $IMG $LOGO -gravity center -geometry +0-10 -composite $IMG

# add user@hostname above the logo
convert $IMG -font Roboto-Mono-for-Powerline -fill grey -pointsize 16 -gravity center -draw "text 0,-110 '$USER@$(hostname)'" $IMG
## list of fonts: identify -list font

i3lock -i $IMG --ignore-empty-password
