#! /bin/sh
echo "# Installing yacreader"

YACV=9.0.0
# 9.5.0 is broken and will overwrite your library.ydb

# See: <9  : https://bitbucket.org/luisangelsm/yacreader/downloads
# See: >9.5: https://github.com/YACReader/yacreader/releases

echo "## Downloading v$YACV"
wget https://bitbucket.org/luisangelsm/yacreader/downloads/yacreader-$YACV-src.tar.xz -O yacreader.tar.xz
# for >9.5: wget https://github.com/YACReader/yacreader/releases/download/$YACV/yacreader-$YACV-src.tar.xz -O yacreader.tar.xz

tar xf yacreader.tar.xz
rm yacreader.tar.xz
cd yacreader-$YACV

echo "## qmake-qt5"
qmake-qt5
echo "## make"
make
echo "## make install"
sudo make install

echo "## Cleanup"
cd ..
rm -rf yacreader-$YACV

# You might need these install dependencies:
#   pacman: poppler-qt5 qt5-multimedia qt5-script
#   aur   : libunarr
